ScoopInstaller/Scoop

bucket/rsync.json

rsync 3.1.1

---

bucket/gibo.json

gibo 1.0.4

---

bucket/scriptcs.json

fixed installation bug introduced in last commit

ScriptCS 0.13.0 (Installation Bug Fix)

---

bucket/php.json
bucket/php54.json
bucket/php55.json

php-5.4.36 -> php-5.4.37
php-5.5.20 -> php-5.5.21
php-5.6.4 -> php-5.6.5

Updated PHP bucket

---

bucket/scriptcs.json

https://github.com/scriptcs/scriptcs/releases/tag/v0.13.2

Bug Fix: ScriptCs 0.13.2

---

lib/core.ps1

Command aliases

---

libexec/scoop-create.ps1

* Abort when url is invalid
* Show usage when no url is provided

scoop-create Bugfixes

---

bucket/git.json

https://github.com/msysgit/msysgit/releases/tag/Git-1.9.5-preview20150319

Git 1.9.5-preview20150319

---

lib/commands.ps1
libexec/scoop-help.ps1

Revert "Added support for custom commands"

---

lib/commands.ps1

Changed `$env:scoop` to `$scoopdir`

Custom commands

---

lib/install.ps1
libexec/scoop-update.ps1

Ignores cache when updating an app. Indirectly solves #181

Added --no-cache option to scoop update

---

libexec/scoop-home.ps1

Implemented suggestion by @lukesampson in #211

Added scoop-home command

---

bucket/busybox.json

seems like I've forgot to update the hash for this

busybox 1.24.0-TIG-1778 hash fix

---

bucket/vim.json

I think this should be ready now!

edit vim.json

---

bucket/ninja.json

Another build system for low level applications. Ninja is more like make instead of cmake, designed for lightning fast C/C++ builds.

Add ninja build system

---

bucket/nim.json

Removed nim_debug.exe (doesn't exist anymore), added nimble.exe (nim's package manager).

Update nim to 0.11.2

---

bin/install.ps1
libexec/scoop-reset.ps1
test/Scoop-Reset.Tests.ps1

Added a custom reset when calling `scoop reset scoop`

Add ability to reset scoop (also adds Git Bash support)

---

bucket/nginx.json

1.9.0 is the current mainline version.

Update nginx to 1.9.0

---

bucket/premake5.json

Updating premake5 to latest alpha release, adding checkver info.

Updating premake5 to 5.0-alpha3.

---

bucket/cmake.json

I just changed the `filename` and the `checksum`, however I was wondering what's the proper testing procedure?

Updated CMAKE to version 3.2.2

---

bucket/dart.json

Can't get this to work via
```
scoop install .\dart.json
```
Please take a look if you can.

refactor dart manifest

---

lib/commands.ps1
libexec/scoop-alias.ps1
test/Scoop-Alias.Tests.ps1

Add scoop-alias command

---

bucket/hugo.json

Hugo is a Fast and Flexible Static Site Generator
http://gohugo.io/

Add Hugo manifest

---

bucket/php.json

Fix broken url. PHP 5.6.10

---

bucket/ant.json

Updated ant to version 1.9.6

---

bucket/innounp.json

Necessary to update Mercurial to 3.5.

Update innounp to 0.43

---

bucket/php.json

Updated PHP to 5.6.12

---

bucket/dart.json

Upgrade the Dart SDK from 1.11.1 to 1.11.3.

upgrade dart to 1.11.3

---

bucket/pcregrep.json

* command-line perl compatible grep
* see [pcre.org](http://pcre.org)
* BSD license; meets all criteria in issue #451

add `pcregrep` to main bucket

---

bucket/jq.json

Update jq to 1.5

---

bucket/haskell.json

Interactive shell is convenient for debugging and learning.

Add ghci to Haskell bins

---

bucket/pshazz.json

Is there anything else required to create a shim?

Shim askpass.exe

---

bucket/grails.json
bucket/openjdk.json

Updated to latest release of grails and openjdk

changed grails to 3.0.9

---

bucket/erlang.json

Update to Erlang 18.1

---

bucket/dart.json

Upgrade dart stable to 1.12.1.

upgrade dart stable to 1.12.1

---

bucket/dart.json

Rev dart from 1.12.1 to 1.12.2.

dart 1.12.2

---

bucket/openjdk.json

Updated hash for openjdk

---

bucket/pdftk.json

Added pdftk v2.02

---

bucket/docker-compose.json

https://github.com/docker/compose/releases/tag/1.5.1

docker-compose 1.5.1

---

bucket/make.json
bucket/which.json

Please consider adding GNU Make to the main Scoop bucket

Added GNU Make

---

bucket/which.json

Please consider adding GNU which to the main Scoop bucket.

Added GNU which

---

bucket/r.json

Addresses the issue in [#587](https://github.com/lukesampson/scoop/issues/587)

Hash in r.json was out of date.

---

test/00-Project.Tests.ps1

* includes code refactoring/improvements and improved test descriptions

improve project "style contraints" testing

---

bucket/openssh.json

Revert "Update OpenSSH to 7.1p1"

---

bucket/openssh.json

Revert "Revert "Update OpenSSH to 7.1p1""

---

bucket/openssh.json

Revert to openssh 5.4p1-1

---

bucket/docker-machine.json

https://github.com/docker/machine/releases/tag/v0.5.6

docker-machine 0.5.6

---

bucket/nodejs.json

https://github.com/nodejs/node/blob/v5.5.0/CHANGELOG.md

Node.js 5.5.0

---

bucket/nodejs4.json

Updated yesterday to 4.2.5, and just a few hours later new version is available…

Update to NodeJS 4.2.6

---

lib/buckets.ps1
lib/core.ps1
lib/depends.ps1
lib/install.ps1
test/Scoop-Core.Tests.ps1

- TODO: support install of same name apps from different buckets?

Support for scoop install <bucket>/<app>

---

bucket/julia.json

Julia v0.4.3

---

lib/install.ps1
libexec/scoop-uninstall.ps1

Startmenu Shortcut Support 

---

bucket/mozjpeg.json
bucket/optipng.json

Add well known open source image optimizers

Add OptiPNG and mozjpeg

---

bucket/fix.json
bucket/forge.json

https://github.com/fsprojects/Forge

Project name changed to Forge

---

bucket/ffmpeg.json

FFmpeg 3.0 "Einstein"

---

bucket/apache.json

Check on https://www.apachelounge.com/download/VC14/binaries/httpd-2.4.18-win32-VC14.zip.txt

Update Apache hash

---

bucket/nuget.json

I'm also updating the homepage property to reflect its new online home.

Update nuget to 3.3.0

---

bucket/nodejs.json

https://github.com/nodejs/node/blob/v5.7.0/CHANGELOG.md

Node.js 5.7.0

---

bucket/docker.json

https://github.com/docker/docker/releases/tag/v1.10.2

docker 1.10.2

---

libexec/scoop-update.ps1

...to prevent connection reset. ~~(in a special country)~~

Use https protocol

---

bucket/ffmpeg.json

Update to latest version of FFmpeg.

FFmpeg 3.0 (20160310-git-689211d)

---

bucket/git-with-openssh.json
bucket/git.json

Yet another pull request to update versions in main.
_Side note_: in the future, would you rather me continue doing these as per-package PRs, or would you prefer fewer, larger PRs?

Update `git` to 2.7.4.windows.1

---

bucket/ffmpeg.json

Update to latest version of FFmpeg.

FFmpeg 3.0 (20160330-git-be746ae)

---

bucket/r.json

Updated R to version 3.2.4

---

lib/install.ps1

Reverts lukesampson/scoop#781, in response to #785.

Revert "Bringing back download progress"

---

bucket/apache.json

Apache httpd version upgrade to 2.4.20

---

bucket/apache.json

The file hash is incorrect for the binaries 64bit

Change the apache file hash - 64bit

---

bucket/ffmpeg.json

Update to Zeranoe FFmpeg. SHA-256 hash taken from 7-zip.

Update FFmpeg to version 2016-04-28

---

bucket/git.json

Update to git. SHA-256 hash taken from 7-zip.

Update Git to version 2.8.2.windows.1

---

bucket/git-with-openssh.json

Update to git with openssh. SHA-256 hash taken from 7-zip.

Update Git with OpenSSH to version 2.8.2.windows.1

---

bucket/php.json

- add php-cgi as available command

Update PHP to 7.0.6

---

bucket/mysql.json

MD5 taken from http://dev.mysql.com/downloads/mysql/.

Update MySQL to 5.7.12

---

bucket/bfg.json

SHA-256 taken from 7zip. (Note to self, must use later and look at later.)

Update BFG to 1.12.12

---

bucket/far.json

Update Far Manager to 3.0.4545

---

bucket/git-up.json

Update git-up to 1.4.0

---

bucket/elixir.json

Update Elixir to 1.2.5

---

bucket/glide.json

Update glide to 0.10.2

---

bucket/openssl.json

Update openssl link

---

bucket/groovy.json

Update Groovy to 2.4.6

---

bucket/innounp.json

Update Inno Setup to 0.46

---

bucket/llvm.json

llvm manifest tested on external bucket.

Update LLVM to 3.8.0

---

bucket/lua.json

lua manifest tested on external bucket.

Update Lua Windows to 5.1.5-51

---

bucket/kotlin.json

kotlin.bat found in "bin" folder
-> added "bin\\\kotlin.bat" to shim

Update Kotlin to 1.0.1-2

---

bucket/invoke-build.json

Update Invoke Build to 2.14.4

---

bucket/7zip.json

7zip 15.14 -> 16.00

---

bucket/mercurial.json

SHA-256 taken from 7zip and shasum;
auto-fixed indent on vim (gg=G);
mercurial manifest tested on external bucket.

Update Mercurial to 3.8.1

---

bucket/7zip.json

SHA-256 taken from shasum-cygwin

Update 7zip to 16.02

---

bucket/aria2.json
bucket/cmake.json
bucket/dart.json
bucket/go.json
bucket/julia.json
bucket/nano.json
bucket/packer.json
bucket/perl.json
bucket/rust-msvc.json
bucket/rust.json
bucket/sbcl.json
bucket/sliksvn.json

It's late, I forgot to base changes off of upstream's master branch. This is based off of my last PR. I'll clean it up in the coming days (unless my PR gets pulled in first, of course).
I took a pass at fixing broken regex for bucket items that had the property set. I will try to add url/regex to items that are lacking it at all in the near future.

[WIP] checkver fixup

---

bucket/go.json
bucket/packer.json

Latest versions of both. :beer:

Update go and packer to latest version

---

bucket/aria2.json

SHA-256 taken from shasum-cygwin.

Update aria2 to 1.23.0

---

bucket/invoke-build.json

Updated to the latest version.

Invoke-Build v2.14.5

---

bucket/invoke-build.json

Updated to the latest version.

Invoke-Build v2.14.6

---

bucket/mercurial.json

Update Mercurial to 3.8.2

---

bucket/modd.json

Add modd v0.3

---

bucket/imagemagick.json

Updated ImageMagick to version 7.0.1-8.

Bump ImageMagick to 7.0.1-8

---

lib/buckets.ps1
libexec/scoop-bucket.ps1

To make it more user-friendly to know which buckets are known to scoop.

Add a new subcommand "list-known" to command "bucket"

---

bucket/nim.json

+ nimsuggest is now added to PATH
- nimble is no longer shipped with the distro for some reason

Update Nim to 0.14.0

---

bucket/ffmpeg.json
bucket/git-with-openssh.json
bucket/git.json
bucket/mercurial.json
bucket/redis.json

Updated `git`, `git-with-openssh`, `ffmpeg`, `mercurial`, and `redis`.

Update several packages

---

bucket/nim.json

Update Nim to 0.14.2

---

bucket/less.json

Hello. Are these wanted? (md5 -> sha256 hashes)
If so, I can submit patches for the packages using md5 / sha1.

less: sha256 hashes

---

bucket/invoke-build.json

Invoke-Build v2.14.7

---

bucket/erlang.json

erlc is the Erlang compiler which actually makes binaries from Erlang source.

Erlang: erlc.exe added to PATH.

---

bucket/pngcrush.json

see previous discussion in #950

pngcrush 1.8.1 multi-arch

---

bucket/invoke-build.json

Invoke-Build v3.0.0

---

bucket/vagrant.json

Update vagrant to 1.8.5

---

bucket/r.json

Update R to 3.3.1 released June 21, 2016

Update R to 3.3.1

---

bucket/r.json

I neglected to update the version member from 3.3.0 to 3.3.1 in my previous pull request.

Version number was missed in #982

---

bucket/apex.json

a servlerless framework powered by AWS lambda. More info here: http://apex.run/ and https://github.com/apex/apex/

add apex.run serverless framework 0.10.2

---

bucket/git-with-openssh.json
bucket/git.json
bucket/nodejs.json
bucket/thrift.json

I'm updating some packages to their new versions
I'm also fixing an additional http on thrift homepage that was preventing ```checkver.ps1``` to run as expected.
Thanks,
Gustavo

Updates git, node and thrift

---

bucket/php.json

Fixes #1005 
Note: The 32 bit .dll does not exist anymore. The repo got removed. We should upload it somewhere else :/

Update PHP to 7.0.10

---

bucket/nvm.json

https://github.com/coreybutler/nvm-windows/releases/tag/1.1.1

Update nvm-windows to v1.1.1.

---

bucket/git-with-openssh.json

Update git-with-openssh to 2.10.0.windows.1

---

bucket/mercurial.json
bucket/openssl.json

At this time I'm updating mercurial and openssl packages.
Thanks,
Gustavo

Update mercurial and openssl

---

bucket/7zip.json
bucket/nodejs.json

I'm updating ```node``` and ```7zip``` packages.
Thanks,
Gustavo

Update Node to 6.7.0 and 7zip to 16.03

---

bucket/rust-msvc.json

Rust 1.12 - https://blog.rust-lang.org/2016/09/29/Rust-1.12.html

Update rust-msvc to 1.12.0

---

bucket/vim.json

update vim to 8.0

---

bucket/nim.json

Reverts lukesampson/scoop#1053

Revert "Update Nim to 0.15.0"

---

bucket/git-with-openssh.json

I forgot to update the `version` in #1073.

Update the version of git-with-openssh

---

bucket/pt.json

Added [the platinum searcher](https://github.com/monochromegane/the_platinum_searcher) by [monochromegane](https://github.com/monochromegane)

Added the platinum searcher

---

bucket/caddy.json

@lukesampson Is there a way to rename the bin after extraction?
I'd like to rename `caddy*.exe` to `caddy.exe`.

Add Caddy Bucket

---

bucket/apex.json
bucket/eventstore.json
bucket/far.json
bucket/ffmpeg.json
bucket/git-lfs.json
bucket/imagemagick.json
bucket/latex.json
bucket/mercurial.json
bucket/mongodb.json
bucket/nano.json
bucket/nodejs.json
bucket/packer.json
bucket/pngcrush.json
bucket/premake5.json
bucket/puppet.json
bucket/rancher-compose.json
bucket/sbcl.json
bucket/sqlite.json
bucket/terraform.json
bucket/upx.json
bucket/vagrant.json
bucket/vault.json
bucket/youtube-dl.json

Fixes #1068 
There has to be a better way than manually downloading all new versions, creating sha256 and copying the new urls into the manifests... :/

Update a bunch of programs

---

bucket/nodejs.json

Still requires a shorter path (#249) to install

update nodejs to 7.0.0

---

bucket/mercurial.json

[Mercurial 4.0](https://www.mercurial-scm.org/wiki/WhatsNew#Mercurial_4.0_.282016-11-1.29) shipped today.

Update mercurial to 4.0

---

bucket/curl.json

https://curl.haxx.se/changes.html

curl security update 7.51.0

---

bucket/clink.json

Added support for CLINK app.
Clink is an open source cmd.exe autocomplete and history manager.
https://mridgers.github.io/clink/

Support for CLINK App

---

bucket/rust-msvc.json

[Rust 1.13.0](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html)

Update rust-msvc to 1.13.0

---

libexec/scoop-update.ps1

I´m thinking in something like this. But i don´t know how to test. Can you provide some instructions?
Also, what does '-ea stop' means?
fixes #1118

Command 'scoop update' delete scoop if download fail. 

---

bucket/leiningen.json

Bumped leiningen version

---

bucket/nmap.json

Add Nmap/Zenmap

---

bucket/php-nts.json
bucket/php.json

resolving 404 error and updated version of PHP 7

Updated PHP to new version 7.0.14

---

bin/checkver.ps1
bin/formatjson.ps1
bucket/go.json
bucket/nginx.json
bucket/nodejs-lts.json
bucket/nodejs.json
bucket/nuget.json
bucket/octave.json
bucket/php-nts.json
bucket/php.json
bucket/yarn.json
lib/autoupdate.ps1
lib/install.ps1
lib/json.ps1
lib/manifest.ps1

New features
- Pretty json output
- new script to reformat json files (`bin/formatjson.ps1`)
- correct manifest encoding
- option to create hash from downloaded file
- more ...
App updates including autoupdate definition
- php 7.1.0
- nodejs 7.2.1
- nodejs-lts 6.9.2
- go 1.7.4
- nginx 1.11.6
- yarn 0.17.10

Autoupdate support / Updates php, nodejs, go, yarn, nginx

---

bucket/service.json
bucket/srvman.json

we have two alias - srvman and service
some useful command for development
sudo service start apache
sudo service stop nginx
sudo service restart php-cgi
sudo service add <file.exe/file.sys> [service name] [display name] [/type:<service type>] [/start:<start mode>] [/interactive:no] [/overwrite:yes]
sudo service delete mysql
if you want to use add, edit or delete command please refer official documents. - http://tools.sysprogs.org/srvman/

service management

---

bucket/srvman.json

used zip directly from the website
added hash
fixed checkver

Fixes for srvman

---

bucket/nssm.json

srvman is command line based service management which is great if someone is familiar with it.
But new devs will not be that confortable, I think NSSM will help them to install services fast and understand how it works

nssm - 2.24 gui/command line based service managment

---

bucket/nssm.json

nssm hash update 

---

bucket/aria2.json
bucket/chromedriver.json
bucket/curl.json
bucket/ffmpeg.json
bucket/imagemagick.json
bucket/nssm.json

Tested both 32 bit and 62 bit installations

Update selected apps

---

bucket/cmake.json

cmake 3.7.1

---

bucket/packer.json
bucket/terraform.json
bucket/vagrant.json
bucket/vault.json

* packer: autoupdate using checksums
* terraform: update 0.8.4 and autoupdate using checksums
* vagrant: autoupdate using checksums
* vault: autoupdate using checksums

I call it the hashicorp-update 🏢

---

lib/autoupdate.ps1

Version variables can now be used in `extract_dir` property and in the hashfile url if `$url.sha256` is not enough.

Add version substitutions in hashfile urls and extract_dir property

---

bucket/openjdk.json

Requires the changes from #1226

Update openjdk autoupdate (requires #1226)

---

bucket/gradle.json

gradle: upgrade to 3.3

---

libexec/scoop-search.ps1

As the first point in #1289 is a simple change, I went ahead with it.
Let me know if it should be changed or if it's unwanted. 👍

Notify empty results for scoop-search

---

bin/auto-pr.ps1

Use manifest/* as branch name for automatic pullrequests so it can be collapsed in GUI clients (convince feature)

Create branches for auto pullrequests under manifest/*

---

bucket/curl.json

See https://github.com/lukesampson/scoop/commit/f4c76238ea5b0e2b5e1c2655b357dff487179ecd

Switch curl provider to https://bintray.com/vszakats/generic/curl/

---

bucket/cacert.json

Maybe it could now be added as a dependency to wget and curl

Add cacert.pem as its own package

---

bucket/cacert.json
bucket/curl.json

Per https://github.com/lukesampson/scoop/pull/1352#issue-210426165

Update curl with cacert's pem file

---

bucket/cdrtools.json
bucket/handbrake_cli.json
bucket/metastore.json
bucket/netcat.json
bucket/pciutils.json
bucket/poppler.json
bucket/smartmontools.json
bucket/sslscan.json
bucket/tesseract.json
bucket/tidy.json
bucket/unrar.json
bucket/unzip.json
bucket/wkhtmltopdf.json
bucket/x264-10bit.json
bucket/x264.json
bucket/xmlstarlet.json
bucket/zip.json

Sorry about the errant merge commit.

Migrate selected CLI apps from rasa/scoops (fixes #1358)

---

bucket/fossil.json

Had more patience this morning and got checkver and autoudpate running--though I'm not 100% sure for how long, since it looks like they *might* be moving the download location.

Update Fossil to 2.0 and add autoupdate/checkver

---

bucket/invoke-build.json

P.S. Thank you for autoupdate, it is really handy.

invoke-build 3.3.0

---

bin/checkver.ps1
lib/autoupdate.ps1
lib/core.ps1
lib/install.ps1

A solution for #368 but needs testing
This should not effect any sites, because browsers will send in anyway.

Add referer-header to all webrequests

---

lib/install.ps1

Throttle progress bar output

---

lib/autoupdate.ps1

Lots of servers block HEAD requests so it's not worth our trouble
maintaining a list of servers

Remove check_url function

---

bucket/gradle.json

This also fixes links to the homepage and install pages.

Update latest release to Gradle 3.5

---

bucket/dd.json

Really easy to use tool, thanks! :)

Adding dd for windows

---

bucket/curl.json

Update Curl 7.54.0 hash for win64

---

lib/install.ps1
test/Scoop-Core.Tests.ps1
test/Scoop-Install.Tests.ps1
test/Scoop-Versions.Tests.ps1

In response to #1417 I started to write some basic unit tests for the install functions.
I think we have some functions that are worth to test, what do you think?

[WIP] Add more unit tests

---

bucket/allure.json

Hello, we would really appreciate if you could add our commandline tool for the [Allure reporting framework](https://github.com/allure-framework) to Scoop. Thanks!

Add Allure Framework commandline tool 

---

bucket/nim.json

From https://nim-lang.org/install_windows.html

SHA 256 update

---

buckets.json

I hope it's useful enough to be merged

Add PHP as known bucket

---

bucket/allure.json

- updated allure2 version to the latest one, which contains a number of fixes;

Allure2 version update

---

bucket/latex.json

The current url results in error:
```shell
Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones.
URL http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable-2.9.6361.exe#/dl.7z is not valid
````

update latex url

---

bucket/less.json

Add lesskey.exe
Add autoupdate & checkver
Move from gnuwin32 to https://www.guysalias.tk/misc/less/

Update less to 487

---

bucket/file.json

Move to msys2's build
Add autoupdate & checkver
Add 64bit build

Update file to 5.30-1

---

bucket/grep.json

Add egrep and fgrep aliases
Move from gnuwin32 to msys
Add autoupdate and checkver
Add 64-bit version

Update grep to 3.0-1

---

bucket/micro.json

https://micro-editor.github.io/

Added micro, the command-line editor

---

bucket/prometheus.json

This is my first bucket with autoupdate, could someone take a look at so i didn't mess it up?
Also, this is the current **stable** release of prometheus. 2.0 will be released soonish.

add prometheus

---

bucket/rustup.json

This pull request adds rustup, which is a toolchain manager for rust and is the preferred method of installation for the Rust programming language.

Add rustup v1.3.0.

---

bucket/gof.json

Added gof v0.0.1

---

libexec/scoop-cleanup.ps1

this pull request adds a cleanup command to scoop which will remove older versions of apps while preserving persistent data.

add cleanup command

---

bucket/cowsay.json

Noticed it was missing while installing a bunch of stuff.

added hash for cowsay

---

bucket/msys2.json
bucket/ruby.json

Ruby 2.4.1-2

---

bin/checkver.ps1

Use the correct Regex.Matches method

---

bucket/rclone.json

Add rclone which is "rsync for cloud storage" - Google Drive, Amazon Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Cloudfiles, Google Cloud Storage, Yandex Files (https://rclone.org)

Add rclone

---

bucket/flyway.json

This pull request adds the flyway database migration tool
https://flywaydb.org/

Add flyway

---

bucket/nodejs-lts.json
bucket/nodejs.json

This pull request updates Node.js to the latest version.

Update nodejs to version 8.7.0

---

bucket/mono.json

This updates Mono to the latest version.

Update Mono to version 5.4.0

---

bucket/glide.json

Implement `autoupdate`
Update to 0.13.0

Update glide to version 0.13.0

---

bucket/gibo.json

Implement `autoupdate`
Update to version 1.0.5

Update gibo to version 1.0.5

---

bucket/nmap.json

Implement `autoupdate`
Update to 7.60

Update nmap to version 7.60

---

bucket/ag.json

Update regular expression
Update to version 2.1.0-5-g1791664

Update ag to version 2.1.0-5-g1791664

---

bucket/julia.json

Updated to use URLs from public website
Updated to version 0.6.1

Update julia to version 0.6.1

---

bucket/helm.json

Update helm to version 2.7.0
`.zip` -> `.tar.gz`

Update helm to version 2.7.0

---

bucket/consul.json

Add [consul](https://www.consul.io) - current version 1.0.0

Add consul version 1.0.0

---

bucket/cloc.json

I have added a manifest for [cloc](https://github.com/AlDanial/cloc).

add manifest for cloc

---

bucket/qpdf.json

Hello,
I have added a JSON manifest for [QPDF](http://qpdf.sourceforge.net/) a command-line program that does structural, content-preserving transformations on PDF files.

add JSON manifest for qpdf-7.00

---

bucket/apache.json

Update hashes for apache

---

bucket/nvm.json

Update nvm to 1.1.6

---

bucket/dotnet-sdk.json

- Update to version 2.0.2
- Add checkver

Update dotnet-sdk to version 2.0.2

---

bucket/bfg.json

This commit fixes the powershell start script for bfg. Bfg did not start at all.

fix bfg powershell script

---

bucket/nim.json

I have removed `bin` from `PATH` and added `.nimble` to it.

Nim: remove bin from PATH, add .nimble to PATH

---

bucket/mozjpeg.json

- Implement autoupdate
- Update to version `3.2`

Update mozjpeg to version 3.2

---

bucket/win32-openssh.json

- Update to version 0.0.24.0
- Implement architectures
- Fix auto updates

Update win32-openssh to version 0.0.24.0

---

lib/git.ps1
lib/install.ps1
lib/psmodules.ps1

Use fixed path to cmd.exe

---

bucket/cygwin.json
bucket/docker.json
bucket/du.json
bucket/erlang.json
bucket/exiftool.json
bucket/fnproject.json
bucket/go.json
bucket/llvm.json
bucket/neko.json
bucket/node-chakracore.json
bucket/nvm.json
bucket/pcregrep.json
bucket/pngcrush.json
bucket/qaac.json
bucket/radare2.json
bucket/sbt.json
bucket/unrar.json

- Flip `http` -> `https` where possible
- Format all files

Format json, convert http to https

---

bucket/optipng.json

- Implement autoupdate
- Update to 0.7.7

Update optipng to version 0.7.7

---

bucket/faas-cli.json

openfaas 0.5.2

---

bucket/win32-openssh.json

Update win32-openssh hash

---

bucket/letsencrypt-win-simple.json

* Fixed URL in the manifest file

Add letsencrypt-win-simple

---

bucket/ack.json
bucket/bzip2.json
bucket/composer.json
bucket/dosbox.json
bucket/erlang.json
bucket/git-up.json
bucket/haskell.json
bucket/jetbrains-toolbox.json
bucket/julia.json
bucket/llvm.json
bucket/lynx.json
bucket/nano.json
bucket/nim.json
bucket/nmap.json
bucket/node-chakracore.json
bucket/nodejs-lts.json
bucket/nodejs.json
bucket/nvm.json
bucket/perl.json
bucket/r.json
bucket/ruby19.json
bucket/smartmontools.json
bucket/unrar.json
bucket/wget.json

Untested. Please review carefully.

 Add quotes around $dir/$persist_dir vars where needed

---

bucket/inadyn-mt.json

Moving from https://github.com/rasa/scoops/blob/master/inadyn-mt.json

Add inadyn-mt at 02.28.10

---

bucket/git.json

Patch: https://github.com/git-for-windows/git/commit/60d8d6eae36358696027f95f0dc1a2dffc3b066b

Update git to version 2.16.1.windows.3

---

README.md

Noticed a minor issue and corrected.

corrected enable powershell executionpolicy

---

bucket/mono.json

Update mono checkver

---

bucket/less.json

- Update to 530
- Fix issues in autoupdate

Update less to version 530

---

bucket/yarn.json

feat(yarn): set and persist offline mirror

---

bucket/cygwin.json

Hashfix for cygwin!

---

lib/core.ps1

core.substitute() for arrays

---

bucket/minisign.json

while browsing thru scoop buckets I sorely miss description on what is the package supposed to do, so I will try to provide description tags for those

added descritpion field

---

bucket/zstd.json

Added zstd v1.3.3! #2066 
PS: I'm only push because there is no word from the @alejandro5042 within 24 hours!

Added zstd v1.3.3!

---

bucket/mongodb.json

Add vcredist2017 suggestion to mongodb

---

bucket/graphicsmagick-q16.json
bucket/graphicsmagick-q8.json

Added GraphicsMagick-Q8/Q16 version 1.3.28! #2086 Feel free to fix any mistake!
Be advice: installer args not working. First time passing them! Fell free to fix them or teach me how to fix!

Added GraphicsMagick-Q8/Q16 version 1.3.28!

---

bucket/openshift-origin-client.json

Add OpenShift Origin client at 3.7.1

(openshift-origin-client) Add OpenShift Origin client at 3.7.1

---

bucket/minishift.json

Add Minishift - OpenShift Origin utility at 1.14.0

(minishift) Add Minishift - OpenShift Origin utility at 1.14.0

---

bucket/kompose.json

Add Kompose - Kubernetes utility at 1.10.0

(kompose) Add Kompose - Kubernetes utility at 1.10.0

---

bucket/qpdf.json

fix qpdf 8.0.2 hashes

---

bucket/pngquant.json

pngquant is a lossy PNG optimizer.

Add pngquant

---

bucket/gnupg1.json

I think this wants to live in the main bucket, but I'm happy to move it to versions, if deemed advisable.

Add gnupg1 at 1.4.22

---

bucket/radare2.json

Added installer version of radare2 v2.3.0!

---

bucket/latex.json

Miktex url is not working, we have to use CTAN. #2129

Changing miktex url to ctan!

---

bucket/cutter.json

Added cutter v1.3!

---

bucket/atomicparsley.json
bucket/bochs.json
bucket/cdrtools.json
bucket/ctags.json
bucket/dosbox.json
bucket/exiftool.json
bucket/gcc.json
bucket/gdb.json
bucket/inadyn-mt.json
bucket/msys.json
bucket/msys2.json
bucket/optipng.json
bucket/pngcrush.json
bucket/premake4.json
bucket/qpdf.json
bucket/sbcl.json
bucket/smartmontools.json
bucket/xmlstarlet.json

Otherwise Scoop just loads a web-page instead of the archive.
#2109 #2161

Use downloads.sourceforge.net URLs

---

bucket/armor.json
bucket/tunnel.json

Signed-off-by: Vishal Rana <vr@labstack.com>

Add armor (https://github.com/labstack/armor) and tunnel (https://github.com/labstack/tunnel)

---

bucket/armor.json
bucket/tunnel.json

Signed-off-by: Vishal Rana <vr@labstack.com>

Fixed bin name for armor & tunnel

---

bucket/astyle.json

astyle the command line style formater for C-like languages

Add AStyle

---

bucket/cppcheck.json

Cppcheck is a static analysis tool for C/C++ code
http://cppcheck.sourceforge.net/

Add cppcheck

---

bucket/docker.json

Solves #2219 
Duplicates the [docker-compose.json](https://github.com/lukesampson/scoop/blob/master/bucket/docker-compose.json) and [docker-machine.json](https://github.com/lukesampson/scoop/blob/master/bucket/docker-machine.json) manifests, plus adding Kitematic.
Maybe not the prettiest, but it does it's job.

Docker 18.03.0-ce

---

lib/core.ps1

Fixed ps1/jar->ps1 shims args handling

---

bucket/forego.json

I didn't find any contribution guide. So this is an attempt to the best of my knowledge. Please let me know, if and what needs improving.

Add forego

---

bucket/s3deploy.json

https://github.com/bep/s3deploy

Add s3deploy

---

README.md

I added some references to environment variables and its uses, as well as explain what the basic setup gives in term of directory layout.

Added reference to environment variables

---

bucket/usql.json

usql is an universal command-line interface for SQL databases.

Add usql version 0.7.0

---

bucket/mill.json

Replaces https://github.com/lukesampson/scoop-extras/pull/1001

Add Mill, a next generation Scala build tool

---

bucket/gifsicle.json

I haven't added anything for a while so I wanted to do it the official way to make sure everything is all good with this one :)

Add gifsicle 1.89

---

bucket/potrace.json

The manifest includes both 64 and 32 bit version as well as
checkver-autoupdate mechanism.
Also incorporated regexp suggestions by @r15ch13 and @rasa.

Add potrace (v1.15)

---

libexec/scoop-info.ps1

Improve scoop-info license attributes output

---

bucket/gcc.json

gcc: correct file url

---

bucket/yubico-piv-tool.json
bucket/yubikey-personalization.json

see [scoop-extras#1061](https://github.com/lukesampson/scoop-extras/pull/1061)

Add YubiKey CLI Tools

---

lib/install.ps1

**Please review before merging.**
Should fix #2394

Support persisting no file extension files

---

lib/core.ps1

Also I removed `?r=&ts=` since it's not needed afaik.

Change sf regex not to break some manifests. Fixes #2474

---

README.md

Follow up #2487 and https://github.com/lukesampson/scoop/commit/00a944e2e89dea6f7e48d8a0e954fc604e2f464a

Update requirements note

---

bucket/seqcli.json

This pull-request adds an app manifest for [`seqcli`](https://github.com/datalust/seqcli).
- Releases from Github
- Extract directory: `SeqCli`
- Binaries: `seqcli.exe`

Add seqcli

---

lib/install.ps1

Write permission for Users to global persist dir

---

lib/manifest.ps1
libexec/scoop-info.ps1

feature(scoop-info): support url manifest

---

bucket/python.json

Haven't tested installing.
Force autoupdate work.

Python3: Add hash to autoupdate

---

lib/autoupdate.ps1
lib/install.ps1

This should fix #2480 and https://github.com/lukesampson/scoop-extras/issues/1126

Add metalink support for aria2c

---

bucket/dotnet-sdk.json

It should also fix the auto update

Update dotnet-sdk to version 2.1.401

---

bucket/armclient.json

https://github.com/projectkudu/ARMClient
ARMClient is a simple command line tool to invoke the Azure Resource Manager API.

Added ARMClient bucket

---

bin/checkurls.ps1
bin/checkver.ps1
bin/describe.ps1
bin/formatjson.ps1
bin/missing-checkver.ps1

Resolve checkver issue on Powershell >6.1.0

---

bucket/terragrunt.json

Adds [terragrunt](https://github.com/gruntwork-io/terragrunt), a wrapper for Terraform.
Closes: https://github.com/gruntwork-io/terragrunt/issues/578

Add terragrunt

---

bucket/windows-application-driver.json

Adding windows application driver to the main scoop bucket and closing the pull request on the extras bucket.

windows application driver

---

bucket/omnisharp.json

Omnisharp is a .NET development platform based on roslyn workspaces

Add omnisharp.

---

bucket/vim.json

PR to fix [Issue 2653](https://github.com/lukesampson/scoop/issues/2653). I also ran into this when updating. Confirmed hash manually as well.

Update Vim hash

---

bucket/mariadb.json

Fixes #2645 , follow up https://github.com/lukesampson/scoop/commit/1ee5ca62bc3041e5b894a462747d21bfb991585a.

mariadb: remove mysql_client_test shim

---

buckets.json

This PR adds Calinou's games bucket to the official bucket list

Add games bucket to official buckets list

---

bucket/dosbox.json

* Updates dosbox to version 0.74-2
* Adds `-` as possible version symbol

dosbox: Update to version 0.74-2

---

test/Scoop-Alias.Tests.ps1
test/Scoop-Config.Tests.ps1
test/Scoop-GetOpts.Tests.ps1
test/Scoop-Linting.Tests.ps1
test/Scoop-Manifest.Tests.ps1
test/Scoop-Versions.Tests.ps1

I was on a roll and went ahead and added the 4.0 Pester syntax to the rest of the test files.

add Pester 4.0 syntax to multiple files

---

bucket/svtplay-dl.json

* Fix bin reference
* Add ffmpeg suggestion
* Format json

Fix and improve svtplay-dl

---

bucket/allure.json
bucket/dotnet-sdk.json
bucket/jq.json
bucket/nasm.json
bucket/resharper-clt.json
bucket/scholdoc.json
bucket/tunnel.json

Add or fix autoupdate in some app manifest

---

bucket/allure.json

allure: Update to 2.8.0

---

bucket/pngquant.json

pngquant: 2.12.1 -> 2.12.2

---

bucket/powerping.json

Ref lukesampson/scoop-extras#1420

Add PowerPing v1.2.0

---

bucket/ldc.json

from https://dlang.org/ ,
> D is a general-purpose programming language with static typing, systems-level access, and C-like syntax. With the D Programming Language, write fast, read fast, and run fast. 
ldc is LLVM based dlang compiler.

ldc: add ldc manifesto

---

lib/json.ps1

Everything relates to json.ps1 I tested on binaris, which was ok. 😐😕
- Closes #2767

[json] Apparently I cannot use variable

---

bucket/casperjs.json

[casperjs] Bump to 1.1.4-2

---

libexec/scoop-reset.ps1

Persist data on reset

---

bucket/rustup.json

https://www.virustotal.com/#/url/d7d84d4a87e31ce7e2646a91876145799ae283419b83fe3b195a5ecc2a1d08d2/details

fix rustup hash

---

bucket/swig.json

add swig 3.0.12

---

bucket/mozjpeg.json

I hope it's an okay solution to #2780

mozjpeg: update to 3.3.1 and change binary source to garyzyg/mozjpeg-windows

---

bucket/highlight.json

- Source code was moved to [Gitlab](https://gitlab.com/saalen/highlight#user-content-overview) and Github repository is archived
- Added description

highlight: Bumped to 3.47

---

bucket/chroma.json
bucket/cobalt.json
bucket/gopass.json

> Chroma: A general purpose syntax highlighter in pure Go 
> https://github.com/alecthomas/chroma
> gopass: The slightly more awesome standard unix password manager for teams
> https://github.com/gopasspw/gopass
> Cobalt: Static site generator written in Rust
> https://cobalt-org.github.io/

Add chroma, cobalt, gopass

---

lib/depends.ps1

Fix empty bucket name

---

bucket/sslscan.json

- Added checkver and autoupdate

sslscan: Bumped to 1.11.11

---

libexec/scoop-update.ps1

Fixed persisting bug when force update app with same version.

---

bucket/gdrive.json

- Closes lukesampson/scoop-extras#1364

Add gdrive cli

---

bucket/runasti.json

Add RunAsTi

---

lib/buckets.ps1

Fix regression from #2878

---

bucket/docfx.json

add docfx v2.40.4

---

bin/install.ps1
lib/core.ps1
libexec/scoop-update.ps1

Fix. Scoop does not update itself automatically for the first time.

---

bucket/jhead.json

jhead: Bumped to 3.02

---

bucket/nvs.json

Fix creating a dummy 'null' file while un/installation.
Sorry for my stupid error...

nvs: Fix output null

---

bin/install.ps1

Modified miss related at #2906

'Fix bug for lastupdate'

---

bucket/rust-msvc.json
bucket/rust.json

My first little commit here. Please check that I did not miss anything important. ;-)

Adjust checkver for rust and rust-msvc autoupdate

---

bucket/acmesharp.json
bucket/adb.json
bucket/ammonite.json
bucket/ant.json
bucket/apache.json
bucket/axel.json
bucket/bazel.json
bucket/bfg.json
bucket/blink1-tool.json
bucket/busybox.json
bucket/cacert.json
bucket/composer.json
bucket/dart.json
bucket/dep.json
bucket/devd.json
bucket/diffutils.json
bucket/dig.json
bucket/digdag.json
bucket/dirhash.json
bucket/docfx.json
bucket/docker-compose.json
bucket/docker-machine.json
bucket/docker.json
bucket/dosbox.json
bucket/dotnet-sdk.json
bucket/dotnet.json

Add some descriptions to programs that were missing them.
I also built a small tool to list and help add these descriptions: https://scoop-programs.glitch.me/

Add some missing descriptions

---

bucket/helmfile.json

- Add description
- Remove shortcut
- Simplify checkver
- Relate lukesampson/scoop-extras#1580

Move helmfile from extras

---

bucket/doctl.json

This is a command line tool for Digital Ocean services made by Digital Ocean.

Add Digital Ocean Commandline Tool 1.12.2

---

bucket/boxes.json

This is a command line filter program that draws ASCII art boxes around your input text.

Add boxes 1.2

---

bucket/mach2.json

This is a feature control multi-tool for Windows 10.

Add mach2 0.3.0.0

---

bucket/mro.json

Add MRO v3.5.1, an enhanced distribution of R from Microsoft Corporation.
- Name: Microsoft R Open
- Description: Microsoft R Open is the enhanced distribution of R from Microsoft Corporation. The current release, Microsoft R Open 3.5.1, is based the statistical language R-3.5.1 and includes additional capabilities for improved performance, reproducibility and platform support.
- Version: 3.5.1
- Homepage: https://mran.microsoft.com

Add Microsoft R Open v3.5.1

---

bucket/hygen.json

https://github.com/jondot/hygen/commit/98295af2840c5afd5d51fc288efa2699ff3e7057

hygen: Update to version 2.1.1

---

bucket/openssh.json

Fixed OpenSSH infinite link. #2927

---

bucket/kubefwd.json

The PR was moved from lukesampson/scoop-extras#1609 as requested by @Ash258

Add kubefwd 1.4.10

---

bucket/sops.json

https://github.com/mozilla/sops

Add sops 3.2.0

---

bucket/smimesign.json

https://github.com/github/smimesign

Add smimesign 0.0.10

---

bucket/cht.json

https://github.com/chubin/cheat.sh#windows-command-line-client

Add cht.exe 0.6

---

bucket/tldr.json

https://github.com/isacikgoz/tldr

Add tldr 0.5.0

---

bucket/gunk.json

Adding Gunk, a modern frontend and syntax for Protocol Buffers.

Add gunk version 0.1.0

---

bucket/mysql.json

Quick fix for the mentioned issue.

Closes #3019, remove deprecated utility

---

bucket/bat.json

Updated license and alternative apps list.

Update bat manifest

---

bucket/kops.json

Signed-off-by: Maciej Bryński <maciek@brynski.pl>
Kubernetes Operations (kops) - Production Grade K8s Installation, Upgrades, and Management

Add kops manifest

---

bucket/genact.json

Add the command-line tool [genact](https://github.com/svenstaro/genact/).

Add genact v0.6.0

---

bucket/plex-server.json

It's only deamon, which run in background and you connect to it using browser / player so i rather pushed it to main bucket.
Since binary contains spaces I rather rename it in first place.

Add Plex Server 1.14.1.5488-cc260c476

---

bucket/psutils.json

https://ci.appveyor.com/project/lukesampson/scoop/builds/21982425

psutils: lint manifest

---

bucket/gitkube.json

https://github.com/hasura/gitkube

Add hasura/gitkube 0.3.0 manifest

---

bucket/sccache.json

https://github.com/mozilla/sccache

Add sccache

---

bucket/editorconfig.json
bucket/elm.json
bucket/lynx.json
bucket/mono.json
bucket/nasm.json
bucket/red.json

Add descriptions, when missing
Red - Add hash extraction

[Multiple manifests] Convert http homepages into https.

---

bucket/nssm.json

Nssm: Add hash extraction

---

bucket/gitversion.json

- Add `description`
- Use portable version in choco
- Add `au.hash`

gitversion: Add description and au.hash, move download url to choco

---

bucket/lf.json

lf: fix checkver and update to correct version

---

bucket/git-interactive-rebase-tool.json

https://gitrebasetool.mitmaro.ca/
Already bundled by Homebrew

add git-interactive-rebase-tool

---

libexec/scoop-uninstall.ps1

Uninstall: Print purge step to console

---

bucket/haskell.json

haskell: add 32bit

---

lib/buckets.ps1
lib/git.ps1

Basicly duplicate of #2799 with limiting to github and supporting of ssh and https remotes

Correct bucket URL for new issues

---

bucket/jq.json

- Add description
See: <https://stedolan.github.io/jq/download/#checksums_and_signatures>

jq: Add hash extraction

---

bin/auto-pr.ps1

[auto-pr] App parameter

---

bucket/msmpi.json

This updates msmpi to version 10.

Updating msmpi to version 10

---

bucket/micronaut.json

[Micronaut](https://micronaut.io) is a modern, JVM-based (Java, Groovy, Kotlin), full-stack framework for building modular and testable microservice and serverless applications.
Currently the [install](https://micronaut.io/download.html) is supported on Linux/Mac using SDKMAN 
With the power of Scoop Windows smooth and easy install, uninstall & update will be supported as well.

Add Micronaut - Modern JVM (Java, Groovy, Kotlin), microservice and serverless applications

---

bucket/scriptcs.json

- Change `checkver` to Choco
- Modify `url` and `au.url` to avoid redirection

ScriptCs: Modify url and checkver

---

bucket/git-tfs.json

git-tfs: Add manifest

---

bucket/xpdf-tools.json

New manifest for xpdf-tools.
Some command-line tools to extract text and other data from PDFs. Very useful for scripts.

Add xpdf-tools

---

bin/checkhashes.ps1
lib/core.ps1
lib/install.ps1

- Closes #2348
Should be working, but maybe I missed some use-case or something else.
For external buckets use: something like [this](https://github.com/Ash258/scoop-Ash258/blob/master/bin/checkhashes.ps1)

Present new binary for checking hashes

---

bucket/terraform.json

Fixed hashes for terraform 0.11.13

---

bucket/dark.json
bucket/mro.json
bucket/plex-server.json

- Add dark v3.11
- Modify `mro` and `plex-server` which using `dark` as extractor

dark: Add version 3.11 (and mod apps using dark)

---

bucket/plex-server.json

Close #3224 
Sorry, I don't use this software and just modify the depends, so I didn't noticed the broken url. 
I've also checked `extras/plex-player`, and it's okay.

plex-server: Fix download url

---

bucket/editorconfig.json

editorconfig: Fix checkver

---

bucket/bazel.json
bucket/cacert.json
bucket/lynx.json
bucket/wget.json

Otherwise global installs fail.

Add $global to appdir calls

---

README.md

docs(readme): add discord chat badge

---

bucket/wp-cli.json

Add wp-cli version 2.1.0

---

bucket/kubeval.json

Add kubeval

---

libexec/scoop-update.ps1

Fix typo. (Sorry i am idiot 😢, who cannot write)
- Closes se35710/scoop-java#43
- Closes se35710/scoop-java#42
- Closes se35710/scoop-java#38
- Closes se35710/scoop-java#39
- Closes se35710/scoop-java#41
- Closes #3250
/cc @se35710 Please merge this and all java bucket issues will be closed automatically

[scoop-update] Fix update with cookies

---

bucket/mailsend-go.json
bucket/mailsend.json

mailsend-go: Add v1.0.3 and mod mailsend

---

bucket/nero-aac.json

No update anymore, for https://github.com/lukesampson/scoop-extras/pull/1911

nero-aac: Add version 1.5.4.0

---

bucket/sendmail.json

sendmail: Add version 32

---

bucket/opus-tools.json

opus-tools: Add version 0.2

---

bucket/jd-cmd.json

Jd-cmd: Move from extras

---

bucket/jar2app.json

https://github.com/Jorl17/jar2app

Manifest for jar2app

---

bucket/mono.json

Add 64bit installer (64bit has not Gtk# which is 32bit only)

mono: Add 64bit installer

---

bin/checkhashes.ps1
bucket/blat.json
bucket/coreutils.json
bucket/file.json
bucket/findutils.json
bucket/gawk.json
bucket/grep.json
bucket/gzip.json
bucket/iconv.json
bucket/patch.json
bucket/png2jpeg.json
bucket/pngcrush.json
bucket/sed.json
bucket/tar.json
bucket/telnet.json
bucket/which.json
bucket/xmlstarlet.json

#2199
Also fix small typo in checkhashes

Convert sourceforge urls to use downloads mirror

---

lib/git.ps1
libexec/scoop-update.ps1

sync the fix to develop branch.

fix(scoop-update): fix branch switching

---

lib/decompress.ps1

fix: correct deprecation function name

---

lib/core.ps1

For [`extras/mpv`](https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv.json) and [`extras/mpv-git`](https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv-git.json)

shim: Add '.com'-type shim

---

lib/decompress.ps1

- Close https://github.com/scoopinstaller/scoop-main/issues/19
- Close https://github.com/scoopinstaller/scoop-main/issues/20

Expand-ZipArchive: Compatible with Pscx

---

lib/core.ps1
libexec/scoop-hold.ps1
libexec/scoop-list.ps1
libexec/scoop-status.ps1
libexec/scoop-unhold.ps1
libexec/scoop-update.ps1

Allows un/locking a program to the current version and enable/disable updates.
Close https://github.com/lukesampson/scoop/issues/3232

feature(update): Add hold/unhold command

---

lib/depends.ps1

It produces circular dependency.

fix(depends): don't force adding dark dependency

---

index.md

Fix main repo link

---

test/bin/init.ps1

- Closes #3468
This simple check should be enough

feat(tests): Do not force maintainers to have `scoop_helpers` environment

---

libexec/scoop-update.ps1

- Closes #3683 
- Closes #3607

feature(update): allow updating apps from local manifest or URL

---

.editorconfig
appveyor.yml
bin/checkurls.ps1
lib/autoupdate.ps1
lib/buckets.ps1
lib/core.ps1
lib/decompress.ps1
lib/help.ps1
lib/install.ps1
lib/psmodules.ps1
libexec/scoop-help.ps1
libexec/scoop-info.ps1
libexec/scoop-install.ps1
libexec/scoop-uninstall.ps1
libexec/scoop-update.ps1
schema.json
test/bin/init.ps1

Reverts lukesampson/scoop#3695

Revert "Update 2019-10-18"

---

bin/install.ps1

also with a tiny script formatting.

fix(install) execution policy check

---

lib/autoupdate.ps1

Mentioned in https://github.com/lukesampson/scoop-extras/pull/2124/files#r282758151

feat(autoupdate): Add $urlNoExt and $basenameNoExt substitutions

---

README.md
buckets.json
libexec/scoop-hold.ps1
libexec/scoop-unhold.ps1
libexec/scoop-update.ps1

chore(hold): Replace "locked" terminology with "held" for consistency

---

lib/install.ps1

Hotfix for #3785 
Sorry, bugs always came after fixes 😅 
Ping @r15ch13

fix(install): `[Array]::Reverse` error

---

lib/install.ps1

feat(aria2): Inline progress

---

_layouts/default.html
stylesheets/styles.css

This pr adds tags that discord can read, and uses the built in tags instead of ids

Fix webpage

---

bin/checkhashes.ps1
bin/checkurls.ps1
libexec/scoop-update.ps1
libexec/scoop-virustotal.ps1

Fixes https://github.com/ScoopInstaller/Scoop/issues/4185
A continuation of https://github.com/ScoopInstaller/Scoop/pull/4342

Fix incompatible with Pansies url PowerShell alias

---

libexec/scoop-reset.ps1
supporting/shims/kiennq/.gitignore

Manifest.md

---

schema.json

See 	https://github.com/ScoopInstaller/Main/blob/3590444367de0178ad6a35d861a24c9f105fd466/bucket/x265.json#L2

Fix schema to support + in version

---

README.md

which now includes almost all of the 250+ available utilities.

updated notes about the NirSoft bucket,

---

lib/install.ps1

Use newer function - fixes #4534

---

lib/install.ps1

- Close https://github.com/ScoopInstaller/Main/pull/3026
- Close https://github.com/ScoopInstaller/Versions/pull/331

fix(install): 'env_add_path' doesn't append '.'

---

lib/depends.ps1

Closes #XXXX
Relates to https://github.com/ScoopInstaller/Scoop/issues/4285

fix(depends): Prevent error on no URL

---

schema.json
test/Scoop-Manifest.Tests.ps1

**HOTFIX**: Fix AppVeyor error
Relates to https://github.com/ScoopInstaller/Scoop/pull/4594#issuecomment-1001076388

fix(schema): Add 'license' definition

---

CHANGELOG.md

Generated by [git-chglog](https://github.com/git-chglog/git-chglog) and manually reorganized.
~Commits before https://github.com/ScoopInstaller/Scoop/releases/tag/2019-05-12 and those don't follow [Conventional Commits](https://www.conventionalcommits.org/) will be added soon.~
Hope this should be done ONLY ONCE 😭 
Ref: [Conventional Commits](https://www.conventionalcommits.org/) / [Git Commit Msg](https://karma-runner.github.io/latest/dev/making-changes.html)
```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```
- **feat** (Features) for a new feature for the user, not a new feature for build script. Such commit will trigger a release bumping a MINOR version.
- **fix** (Bug Fixes) for a bug fix for the user, not a fix to a build script. Such commit will trigger a …

docs(changelog): Add 'CHANGLOG.md'

---

libexec/scoop-install.ps1
libexec/scoop-virustotal.ps1

feat(install|virustotal): Allow skipping update check

---

.vscode/settings.json
CHANGELOG.md

Since https://github.com/PowerShell/vscode-powershell/issues/1019 is fixed, remove this setting
Relates to https://github.com/ScoopInstaller/Extras/pull/2446

build(vscode-settings): Remove formatOnSave trigger

---

.github/workflows/ci.yml
CHANGELOG.md

See also https://github.com/ScoopInstaller/Tests/pull/3#issuecomment-1013843685

fix(ci): Run on each commit in a PR

---

CHANGELOG.md
libexec/scoop-update.ps1

This is follow-up content of https://github.com/ScoopInstaller/Scoop/pull/4670#discussion_r786441580
- Remove 'Done.'
- Filter git log by `--grep` to keep colorful output
Relates to #4670

fix(scoop-update): Remove 'Done.' output

---

CHANGELOG.md
lib/install.ps1
lib/psmodules.ps1

- `rmdir` -> `Remove-Item -Force`
- `rmdir /s` -> `Remove-Item -Recurse -Force`
- `del` -> `Remove-Item -Force`
- Style `lib/psmodules.ps1`
Relates to https://github.com/ScoopInstaller/Scoop/pull/4687#issuecomment-1021427462

refactor(rmdir): Use 'Remove-Item' instead of 'rmdir'

---

bin/scoop.ps1
lib/buckets.ps1
lib/core.ps1
lib/git.ps1
libexec/scoop-status.ps1
libexec/scoop-update.ps1

Consolidate all git calls in a single function 
Relates to #4697
No functionality changes

refactor(git): Remove unused functions

---

CHANGELOG.md
lib/core.ps1
lib/install.ps1
libexec/scoop-hold.ps1
libexec/scoop-info.ps1
libexec/scoop-prefix.ps1
libexec/scoop-unhold.ps1
test/Scoop-Core.Tests.ps1

Use a new function `currentdir` to point to `current` or latest versioned dir (if `NO_JUNCTIONS` is set).
- Closes #4474
- Closes #4350

fix(no-junction): Fix error when 'NO_JUNCTIONS' is been set

---

CHANGELOG.md

Rearrange `CHANGELOG.md` to make it tidy and move some items that seems to be misplaced.
Use `,` to link hotfix items and move some items under `Refactoring`.

docs(changelog): Rearrange CHANGELOG

---

CHANGELOG.md

Bump CHANGELOG to ~v0.9.0~ v0.1.0 and change tag's URL to tag comparison.

docs(changelog): Bump to v0.1.0

---

CHANGELOG.md
libexec/scoop-update.ps1

Skip logs starting with `(chore)` instead of `chore`
Closes #4799

fix(update): Skip logs starting with `(chore)`

---

CHANGELOG.md
README.md

Fix badges for Gitter and CI Tests
Closes #4829
N/A

doc(readme): Fix badges for Gitter and CI Tests

---

CHANGELOG.md

docs(changelog): Bump to v0.2.0

---

CHANGELOG.md

Final preparation for version 0.2.1, left 3 days for testing.

docs(changelog): Update CHANGELOG

---

CHANGELOG.md

Correct misplaced entry
Relates to #4970

docs(changelog): Fix CHANGELOG

---

CHANGELOG.md

docs(changelog): Update CHANGELOG for v0.2.2

---

CHANGELOG.md
lib/manifest.ps1
libexec/scoop-search.ps1

- Refactor `search` to return PowerShell objects.
- Rectify rate limit error if `gh_token` exists.
- Improve error handling.
Closes #4202
Closes #4574 
Closes #4852 
Closes #3853
Relates to #3446

refactor(scoop-search): Output PSObject, use API token

---

CHANGELOG.md
bin/scoop.ps1
libexec/scoop-alias.ps1
libexec/scoop-depends.ps1
libexec/scoop-download.ps1
libexec/scoop-help.ps1
libexec/scoop-install.ps1

fix(chore): Update help documentation

---

CHANGELOG.md
libexec/scoop-export.ps1
libexec/scoop-update.ps1

Options were not being shown for the `export` command.
Relates to https://github.com/ScoopInstaller/Scoop/pull/5014#issuecomment-1172536818
Relates to https://github.com/ScoopInstaller/Scoop/pull/4992#issuecomment-1172410889

fix(chore): Fix help output of scoop-export

---

CHANGELOG.md

docs(changelog): Prepare for v0.2.3

---

CHANGELOG.md

docs(changelog): Prepare for version 0.2.4

---

.vscode/settings.json
CHANGELOG.md

Use Constant String and Correct Casing in VSCode
Just VSCode Setting

builds(vscode): Tweak VSCode setting

---

CHANGELOG.md
bin/checkurls.ps1

Similar to #4254 but for `.\bin\checkurls.ps1`.
Closes #5150
I have made the changes locally and ran the command successfully.
Before:
```powershell
$ .\bin\checkurls.ps1
[U]RLs
| [O]kay
|  | [F]ailed
|  |  |
[1][0][1] ignition
> The remote server returned an error: (403) Forbidden. (https://files.inductiveautomation.com/release/ia/8.1.20/20220823-1339/Ignition-windows-x86-64-8.1.20.zip)
[1][1][0] jython
```
After:
```powershell
$ .\bin\checkurls.ps1
[U]RLs
| [O]kay
|  | [F]ailed
|  |  |
[1][1][0] ignition
[1][1][0] jython
```

feat(checkurls): Allow checking URLs from private_hosts

---

CHANGELOG.md
schema.json

`schema.json` error
Relates to #5113

builds(schema): Remove 'object' from 'anyOf' under 'sourceforge'

---

CHANGELOG.md
lib/autoupdate.ps1

Don't know when, but SF changes the webpage source.

fix(hash): Fix SF hash extraction

---

libexec/scoop-config.ps1

Small linguistical error corrected in the list/example of configurable options.
I suppose it's not really _required_, and it's definitely not by any means high priority, but I usually like documentation to be properly written without error. Having said that, if these typo edits are undesired, feel free to just reject and let me know! 👍🏻 
This change does not affect functional code.
_I'm unsure about whether this would be necessary for literally a one character change, but no, I've not done this so far. If it's required I'll definitely do so (this PR or in any future edits)_

docs(config): Copyedit config description

---

CHANGELOG.md
lib/diagnostic.ps1
libexec/scoop-checkup.ps1

checkup: Add Windows Developer Mode check
Prompt users if Developer Mode is not enabled, operations relevant to symlinks may fail.

feat(checkup): Add Windows Developer Mode check

---

CHANGELOG.md
README.md
buckets.json

I've made a `scoop-sysinternals` bucket and ready to be added to `known`.
Hmm, or I could transfer the bucket to `ScoopInstaller`?

feat(sysinternals): Add 'sysinternals' bucket to known

---

CHANGELOG.md

Update version number in CHANGELOG

docs(changelog): Prepare for version 0.3.1

---

CHANGELOG.md
test/Import-Bucket-Tests.ps1

The manifest validation will be run on all manifests if non-json file is changed, and this PR will fix it. (Ref: https://github.com/ScoopInstaller/Main/actions/runs/3568299963/jobs/5997015642)
Relates to https://github.com/ScoopInstaller/Main/pull/4177
A simple refactor.

test(bucket): Skip manifest validation if no manifest changes

---

CHANGELOG.md
lib/shortcuts.ps1

fix(shortcuts): Output correctly formatted path

---

.github/dependabot.yml
CHANGELOG.md

ci(dependabot): Add dependabot.yml for GitHub Actions

---

CHANGELOG.md
README.md
buckets.json

Per https://github.com/ScoopInstaller/Scoop/discussions/5293

feat(bucket): Switch nirsoft bucket to ScoopInstaller/Nirsoft

---

CHANGELOG.md
lib/core.ps1

Check for `lastUpdate` and then rewrite config file (#5116)
- Closes #5434

fix(core): Rewrite config file when needed

---

CHANGELOG.md
libexec/scoop-info.ps1

Closes #XXXX
```
current on  develop
❯ scoop help info
Usage: scoop info <app> [--verbose]
current on  develop
❯ g checkout scoop-info
Switched to branch 'scoop-info'
current on  scoop-info
❯ scoop help info
Usage: scoop info <app> [options]
Options:
-v, --verbose   Show full paths and URLs
```

docs(scoop-info): Fix help message

---

CHANGELOG.md

Closes #5595
Relates to #5519 #5549

docs(CHANGELOG): add missing brackets for the links

---

CHANGELOG.md
libexec/scoop-virustotal.ps1

fix(scoop-virustotal): continue exec when no app but -a provided

---

CHANGELOG.md
lib/core.ps1
lib/install.ps1
lib/manifest.ps1
libexec/scoop-config.ps1
schema.json

Nothing special, just codes cleanup.
Config file migration codes should be removed after 2023/06/30 (nearly 1yr for the codes), and `msi` section is deprecated about 7yrs ago.
All tests passed, and no new test added.

refactor(core): Cleanup some old codes, e.g., `msi` section and config migration

---

CHANGELOG.md
lib/system.ps1

Fix a bug introduced by #5836
- Relates to #5836

fix(system): Remove EnvVar only if existed

---

CHANGELOG.md
libexec/scoop-cache.ps1

Closes #5941
Relates to #5929
`scoop cache rm <app>`

fix(scoop-cache): Fix regression in 36026f18

---

CHANGELOG.md
lib/buckets.ps1
lib/database.ps1
libexec/scoop-bucket.ps1

Update cache when adding bucket.
- Relates to #5851

fix(database): Update cache when adding bucket

---

CHANGELOG.md
lib/core.ps1

`innounp` could not handle Inno Setup v6.3+, and there's many `decompress error` for this new version installer.
There's a forked edition of `innounp` by J. Rathlev (https://www.rathlev-home.de/tools/prog-e.html#unpack), and I added it in https://github.com/ScoopInstaller/Versions/pull/1809, and this PR use that edition as default if installed.
This will fix many issues related to `ollama` and `inno-setup`
- Relates to https://github.com/ScoopInstaller/Main/pull/5920
Install `innounp-unicode` and then:

feat(decompress): Use `innounp-unicode` as default Inno Setup Unpacker

---

CHANGELOG.md

Update CHANGLOG version to 0.5.0

(chore): Update changelog

---

CHANGELOG.md
lib/buckets.ps1

Implement error handling for failed bucket addition
- Closes #6048
It should work...

fix(bucket): Implement error handling for failed bucket addition

---

CHANGELOG.md

chore(chglog): Update CHANGELOG for v0.5.1

---

CHANGELOG.md
lib/json.ps1
libexec/scoop-virustotal.ps1

Likes https://github.com/ScoopInstaller/Scoop/pull/6044 ,just modify the function body instead of the caller
Closes #6064

fix(json): Don't serialize jsonpath return if only one result

---

CHANGELOG.md

docs(chglog): Update CHANGELOG for v0.5.2

---

CHANGELOG.md

docs(chglog): Update to 0.5.3
