bucket/groovy.json

FYI - I used http://hash.online-convert.com/sha256-generator to generated the SHA 256 hash for groovy-2.4.0.zip. I think this should be correct, because I generated the same hash value for 2.3.7.zip using this site. Please let me know if you have any questions. Thanks!

Updated groovy.json for the groovy 2.4.0 release

---

bucket/php53.json

Currently, version 5.3 is in archives directory

Updated PHP 5.3 location on php.net

---

libexec/scoop-create.ps1

In the same vein of the Homebrew `brew create` command I was entertaining the idea of something similar for scoop. 
I wouldn't consider this complete or foolproof. Just would like to discuss the idea.

scoop-create command to help with creating app manifests

---

bucket/dnvm.json
bucket/kvm.json

* kvm is the current version that may be deprecated soon
* dnvm is the new version that is still in heavy development
They may not play well together, but they both work individually.

Add kvm and dnvm (ASP.NET vNext command line tools)

---

lib/commands.ps1
libexec/scoop-help.ps1

Custom commands `scoop-*` that are in the `$env:scoop\shims` directory
can now be run using scoop as well as the built-in commands

Added support for custom commands

---

lib/install.ps1
libexec/scoop-update.ps1

When an app versioned as "nightly" is installed (or updated),
the current date is appended to the version which changes the
version directory to nightly-yyyymmdd.
Fixes #181

Added simplistic nightly support

---

bin/install.ps1
libexec/scoop-status.ps1
libexec/scoop-update.ps1

Uses git to update scoop instead of downloading the zip every time
Issues
---------
* Changing repos/branch is not possible after initial update
Usage
---------
If you want to test this out do the following:
```powershell
iex (new-object net.webclient).downloadstring("https://gist.githubusercontent.com/deevus/864ce870042ae1235fe2/raw/9eae811a59c070a9f384b3cfb6b54f8f329be02c/scoop-install.ps1")
scoop config SCOOP_REPO "https://github.com/deevus/scoop"
scoop config SCOOP_BRANCH "scoop-update-git"
scoop update
```
Let me know if I've missed anything

Scoop update git

---

.build.ps1
appveyor.yml

Continuous integration using [Invoke-Build](https://github.com/nightroman/Invoke-Build) and [AppVeyor](http://www.appveyor.com/)
The motivation is trying to automate the testing process so we can catch problems early and often.

Appveyor CI

---

bucket/premake4.json
bucket/premake5.json

The premake build tools are similar to cmake, except they use lua to describe projects.

Add premake build tools

---

test/Scoop-Manifest.Tests.ps1
test/fixtures/parse_json/wget.json

The manifest-validation test iterates through each json in the main
bucket to ensure that required fields (url, version) are not empty

Add manifest validation tests

---

bucket/invoke-build.json

Invoke-Build 2.12.0 contains a number of fixes and improvements since 2.9.14. Also, some scripts are excluded from the package as redundant. Thus, "bin" in json is updated accordingly.

invoke-build.json: Invoke-Build 2.12.0

---

bucket/scholdoc.json

ScholDoc is a command-line utility that converts ScholarlyMarkdown documents
to HTML5, LaTeX, and Docx

Add ScholDoc 0.1.3-alpha

---

bucket/invoke-build.json

Minor change - updated version to the latest stable 2.12.1
Major change - replaced installation of "bin" shims with "env_add_path".
Invoke-Build is designed to be installed either together with a project
(NuGet does this) or in the path (scoop may do this as proposed).
Here is the analysis of why the approach with shims does not work well for
Invoke-Build:
- *invoke-build.ps1*
- PowerShell help is not available, the help file *Invoke-Build-Help.xml*
is not together with the shim. And even if it were help would not work
because the shim parameters do not match.
- The original script *Invoke-Build.ps1* provides the special dot-sourced
mode. The shim invokes the original script as `& $path`. Thus, this mode
is not available. And even if it were Invoke-Build would not set the
correct start …

Invoke-Build 2.12.1 and replaced "bin" with "env_add_path" (explained)

---

bin/scoop.ps1
lib/core.ps1
libexec/scoop-bucket.ps1
libexec/scoop-cache.ps1
libexec/scoop-config.ps1
libexec/scoop-depends.ps1
libexec/scoop-export.ps1
libexec/scoop-help.ps1
libexec/scoop-home.ps1
libexec/scoop-install.ps1
libexec/scoop-list.ps1
libexec/scoop-reset.ps1
libexec/scoop-search.ps1
libexec/scoop-status.ps1
libexec/scoop-uninstall.ps1
libexec/scoop-update.ps1
libexec/scoop-which.ps1

This is a possible fix for #351. What it does:
1. Resets common Powershell aliases to their defaults in Scoop's script scope (e.g. ls, gcm). This was already being done with script-scoped functions, but this change does it with script-scoped aliases instead.
2. Prioritises local functions over user-defined aliases with the same name.
3. Doesn't require renaming functions to make them more obscure in the hope that they won't collide with user's aliases.
4. Gives more protection against invasive aliases.
On my machine this adds about 30ms execution time to each scoop command issued.
I'm going to think about this one before committing. Comments welcome.

A brute force fix for powershell alias problems

---

bucket/mediainfo.json

There are two versions: a GUI and a CLI version. The CLI one seemed more appropriate.
thanks
--oleg

Added mediainfo-cli 0.7.73

---

bin/install.ps1
lib/core.ps1
test/Scoop-Core.Tests.ps1

Add ensure_robocopy_in_path method to core.ps1 which checks if
robocopy is available, then shims it if not.

Fix #376 Robocopy is not always in PATH

---

lib/install.ps1
libexec/scoop-update.ps1

This:
```
$ scoop update *
the latest version of 7zip (9.20) is already installed.
run 'scoop update' to check for new versions.
the latest version of apache (2.4.12) is already installed.
run 'scoop update' to check for new versions.
the latest version of bfg (1.12.3) is already installed.
run 'scoop update' to check for new versions.
the latest version of busybox (1.24.0-TIG-1778) is already installed.
run 'scoop update' to check for new versions.
the latest version of cmake (3.2.2) is already installed.
run 'scoop update' to check for new versions.
the latest version of concfg (0.2014.03.17.3) is already installed.
run 'scoop update' to check for new versions.
the latest version of conemu (150408) is already installed.
run 'scoop update' to check for new versions.
the latest version of …
```

Add --quiet opt to update command to suppress extraneous messages

---

bucket/python.json
bucket/python27.json

These will fix the issue that pywin32 extension installer being unable to find python installed with scoop.
pywin32 installer : http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/
Reference : http://tech.valgog.com/2010/01/after-installing-64-bit-windows-7-at.html

Let PyWin32 extension installer find this python

---

bucket/perl.json

* disable the File::HomeDir override performed by Portable.pm
- achieved by removing the HomeDir section from "portable.perl" via post_install
- ref: https://rt.cpan.org/Ticket/Display.html?id=105395 @@ https://archive.is/q7BYq
.# DISCUSSION
Strawberry Portable Perl is written to be usable from a non-privileged storage location, such as a plug-in USB drive. So, it is designed to be usable without access to the host filesystem beyond it's own directory.
As part of the machinations making this possible, Portable.pm overrides File::HomeDir to return resultant paths which are within the perl installation directory (specifically, "INSTALL_DIR/data"). Obviously, this obscures the user's true home directory and can be very inconvenient for common perl scripts which depend on access to data …

FIX portable perl to allow normal access to user's home directory

---

bucket/dart.json

Upgrade to dart 1.11.1. This PR also changes the refs from /latest (had been 1.11.0) to a specific version. The contents of /latest will change every time there's a new release, and the checksum will no longer be valid. We now point to a specific version and use that version's checksum.

upgrade to dart 1.11.1

---

.editorconfig

* re-enforce requested project file formats and basic character-level coding style
* emphasize the Win/DOS requirement that BAT/CMD files *must* have CRLF line endings
.# Discussion
Using [EditorConfig](http://editorconfig.org) style rules helps devs to maintain the file formatting and style of the project, even while using different editors. This minimizes the semi-invisible, but, paradoxically, visually noisy, whitespace differences between commits. It can also help enforce file format requirements (such as the Win/DOS CMD shell requiring CRLF line endings for correct functioning of BAT/CMD files).

Add `.editorconfig` style rules

---

appveyor.yml

.# Discussion
Appveyor doesn't have partial `appveyor.yml` suppression. So, unless the
`appveyor.yml` configuration file is completely suppressed, non-primary devs
receive notification errors with every build/test of the application. By
removing the user-specific notifications, other devs can now build/test the
application code (via the recipe specified within `appveyor.yml`) without
receiving notification errors.
For any given developer, personalized notification settings can be added on
top of the repo `appveyor.yml` project settings via the "Settings / Notifications"
section.

Fix appveyor.yml, removing user-specific notification settings

---

lib/core.ps1
libexec/scoop-which.ps1

Shim paths are now relative when created, and `scoop-which` was modified to work within this as well.
/cc #427

Make shim paths relative

---

test/Scoop-Alias.Tests.ps1
test/Scoop-Core.Tests.ps1

* Scoop-Alias: remove erroneous output from dot-sourcing the source file
* Scoop-Alias: using "TestDrive:\" for mocked shimdir
- reduced cleanup
- improved robustness; excution is now independent of CWD
* Scoop-Core: corrected directory location code
- improved robustness; execution is now independent of CWD

fix/improve Scoop-Alias and Scoop-Core tests

---

test/00-Project.Tests.ps1

* checks all .ps1 and .psm1 files in the Project repository
* NOTE: this is just simple syntax checking, but it can catch a lot of simple mistakes

add simple syntax checking for all PowerShell script/module files

---

test/Scoop-Core.Tests.ps1

* fixes tests by coercing the `test-unzip` return value back into a valid path string
* fixes #476
.# Discussion
For Win10 machines, `test-unzip` returns a bugged value, causing test failures.
Investigation shows that the combination of Pester, COM (used within unzip_old), and
Win10 leads to the odd/bugged return value. The return value contains the correct
string, but it is prefaced with a leading space which arises de-novo during the
execution return process from `test-unzip`. The value is correct and usable at the end
of `test-unzip` but is bugged upon receiving the value at the caller. Removing the COM
call from within `unzip_old` or using a Windows version earlier than Win10 fixes the
problem, but are obviously not useful as solutions.
Given the nature of the returned value and COM …

fix Scoop-Core tests for Win10 (#hack)

---

bucket/r.json

The R 3.1 binaries were moved to an `old` directory on CRAN mirrors, so I updated the URL. I also updated `r.json` to use 3.1.3 instead of 3.1.1.
Note that R 3.2 packages now seem to have `bin/R,1.exe` and `bin/R,2.exe` instead of `bin/R.exe` and `bin/Rscript.exe`, which I am not sure how to handle. Might be a good idea to shim the architecture-dependent executables instead.

Corrected r.json and updated from R 3.1.1 to 3.1.3

---

bucket/php.json

Avoids 404 error on new installs.

PHP bucket upgrade to 5.6.13

---

bucket/php55.json

it will avoid errors when pulling PHP 5.5 via Scoop.

Update to PHP 5.5.30

---

bucket/gibo.json

When i try to install gibo, the following error occurred.
```posh
> scoop install gibo
installing gibo (1.0.4)
downloading https://github.com/simonwhitaker/gibo/archive/master.zip...done
checking hash...hash check failed for https://github.com/simonwhitaker/gibo/archive/master.zip. expected: b358ab0a2d39e304b3a79660ffebf6b0e99496a8b73854e0d230218cb49fc309, actual: 998c45acb27cd7bca5381312e5be360d85523f2bf849a69f39285c853243c1b3!
```
This pr specifies version 1.0.4 url to prevent hash check error.

Fix hash for gibo

---

bucket/git.json
bucket/ruby.json

Scoop failed to update git and ruby for me due to hash mismatches. I manually downloaded the files that failed the hash check and checked them myself, then corrected the hashes in the JSON files.

Fix hashes for git and ruby

---

bucket/nuget.json

NuGet also changed the location where they publish their binaries (and they're just a straight binary now), so this PR accounts for that change as well.

Updates NuGet to 3.2.0

---

bucket/rust-msvc.json
bucket/rust.json

My one concern about this at the moment is that the MSVC version of the compiler only supports x86_64 in this release, is there anything that should be done about this?

Updates Rust to 1.4.0, adds MSVC variant

---

bucket/docker-machine.json

`docker-machine.exe` needs the driver `.exe` files to be in `PATH`.

docker-machine 0.5.0 fix

---

bucket/pshazz.json

I'm just not sure about *hash* because as is written in https://github.com/lukesampson/scoop/wiki/App-Manifests I made SHA256 hash of URL, but as I tried SHA256 on original URL from app manifest then result was not `b8ee4ccffa719bbe97b47856457592f13ce4103e92b6bb41ff421a00f21bb08a`.
Did I do something wrong?
Thanks!

Update Pshazz app to latest commit

---

bucket/curl.json
bucket/nginx.json
bucket/php-nts.json
bucket/php52.json

**php** 5.6.15 (*including NTS version*)
**curl** 7.45.0
**nginx** 1.9.6
Dropped PHP 5.2 (**php52**) per https://secure.php.net/supported-versions.php

+php 5.6.15, +curl 7.45.0, +nginx 1.9.6, -php52

---

bucket/leiningen.json

JSON config for installing leiningen (Clojure) via Scoop. Originally found the how-to details at this blog: `http://offbytes.com/2015/02/03/scoop-leiningen.html`

Added leiningen.json to /bucket

---

bucket/wget.json

It seems that the URL has changed, causing a hash check fail, when trying to install or update.

Update the wget URL

---

bucket/php.json

Changed filenames and SHA1 checksums in php.json for 5.6.16 update (current version now returns a 404 when attempting to retrieve).

PHP updated to 5.6.16

---

bucket/php.json

PHP 5.6.16 moves to php56 bucket. Upgrades default install to PHP 7.0.0

Upgrade to PHP 7.0

---

bucket/php56.json

Create new bucket for PHP 5.6 at current stable version PHP 5.6.16 to upgrade PHP main bucket to PHP 7.0.0

Move PHP 5.6 to new bucket

---

bucket/r.json

Addresses issue [#589](https://github.com/lukesampson/scoop/issues/589).
The R installer delivers the 32 as well as the 64 bit versions of R. I
added a pre_install to r.json to choose the correct version depending on
the user's architecture.
Additionally I added a new shim for 'rterm.exe' to have an alternative
way to start R without removing the 'r' alias in powershell.

Fixed an issue with the 32/64 bit versions of R

---

appveyor.yml

* add $env:APPVEYOR_CHOCO_PESTER_OPTIONS to the `choco` install command for the `pester`
test runner within the "appveyor.yml" config file
* NOTE: AppVeyor testing will issue advisory note when the variable is non-NULL
* allows customization of `pester` install, eg, version pinning, without requiring any
further, future changes to "appveyor.yml", avoiding log noise
* mitigates test failures due solely to the test runner
.# Discussion
This change was implemented in response to multiple automated test failures which occurred due to a regression within the `pester` test runner. The change adds the ability to specify the `pester` version (aka, "version pinning") on AppVeyor via the "test-time" configurable environment variable, $env:APPVEYOR_CHOCO_PESTER_OPTIONS.
By using this …

add optional "test-time" customization of AppVeyor test runner

---

bucket/vagrant.json

Vagrant has recently updated to 1.8.0: https://www.hashicorp.com/blog/vagrant-1-8.html

Update vagrant to 1.8.0

---

bucket/openssl.json

Updated the OpenSSL bucket to the current version. The old one is not available any more from the download site (it leads to an HTTP 404 error).

Update to OpenSSL 1.0.2e.

---

bucket/nodejs4.json

Since `node-5.x.x` is a bleeding edge, I think it will be great if scoop 
would also support an LTS version `node-4.x.x`.
#538

Add node-v4.2.4

---

bucket/git.json

As git is a prerequisite for "scoop update" and "scoop add bucket", 32 bits version of scoop is broken.

Fix typo in git 2.7.0 manifest

---

bucket/apache.json

It is reported in Issue [#629](https://github.com/lukesampson/scoop/issues/629). The url was out of date.

Update Apache to 2.4.18

---

bucket/openssh.json

Issue [#461](https://github.com/lukesampson/scoop/issues/461)
This version of OpenSSH 7.1p1 was released by Microsoft.
[https://github.com/PowerShell/Win32-OpenSSH/releases](https://github.com/PowerShell/Win32-OpenSSH/releases)

Update OpenSSH to 7.1p1

---

bucket/youtube-dl.json

Windows binary has Python already baked in, no need to require it as runtime dependency.

Update youtube-dl to version 2016.01.15

---

bucket/aria2.json

aria2 download utlity.
Proposal: add to main bucket, as this tool is comparable to the already contained wget utility (otherwise please move to the extra bucket instead)

Add aria2 utility

---

bucket/maven.json

In addition to bumping Maven to 3.3.9, I've removed the dependency on OpenJDK. Since Scoop's OpenJDK is stuck at 1.7.0, this gets wonky if you're also using Oracle's JDK 8 or 7. Rather than making Maven depend on a specific distribution of Java, I've added the note property to inform the user that they would likely need to install a JDK and how to do it.

Bumped Maven, removed dependency on OpenJDK 7

---

lib/buckets.ps1
libexec/scoop-search.ps1

By using githubs api we can search known buckets that haven't been added
to the local scoop instance. When a local search doesn't return any
results, other known buckets will be searched via github. If the rate
limit has been reached (60 per hour as of impl) the search won't occur.

Add ability to search known buckets that haven't been added locally

---

bucket/imagemagick.json

Old version returns 404 now when scoop attempts to download zip file

New ImageMagick version was released

---

buckets.json

Seems like you renamed the extras repo? Failed for me at least, had to add it manually with name and the complete adress.

Update path to scoop-extras

---

lib/core.ps1

If the `SCOOP` environment variable is not set, scoop will install to the users home directory. In cases where an organization has decided to set a users home directory to another location, such as network drive, the use of `~\appdata\local\scoop` will cause scoop to perform poorly as it will install itself on the network drive. By using `$env:LOCALAPPDATA\scoop` will use users home directory on the local drive even if the `HOMEDRIVE` has been set to use a remote volume.

Changed $scoopdir to use $env:LOCALAPPDATA\scoop from ~\appdata\local\scoop

---

bucket/git.json
bucket/nodejs.json
bucket/nodejs4.json

Updated Git from `2.7.0.windows.1` to version `2.7.1.windows.2` and bumped Node.js to `5.6.0` and `4.3.0`

Bumped versions for Git and Node.js

---

bucket/forge.json

Regenerated the hash for forge as the MD5 hash currently mismatches. This issue has been raised in the Forge repo https://github.com/fsprojects/Forge/issues/47

Correct the MD5 hash for 0.6.0 forge release

---

bucket/go.json

Go 1.6 just [shipped](http://blog.golang.org/go1.6) so let's update the bucket.

Update go to 1.6

---

bucket/rust-msvc.json

Let's update the MSVC ABI build of Rust 1.6.0 as well.

Update rust-msvc to 1.6.0

---

bucket/ruby19.json

Let's update ruby19 to [1.9.3-p551](https://www.ruby-lang.org/en/news/2014/11/13/ruby-1-9-3-p551-is-released/), which has a security fix for the REXML module.

Update ruby19 to 1.9.3-p551

---

bucket/ruby19.json

It looks like omitting the hash from the Ruby DevKit URL's caused them not to extract properly to the devkit folder.  I'm adding the hash URL's back in.

Fix ruby19 to include omitted hash from URL's

---

bucket/ruby.json

It looks like omitting the hash from the Ruby DevKit URL's caused them not to extract properly to the devkit folder.  I'm adding the hash URL's back in.

Fix ruby to include omitted hash from URL's

---

bucket/leiningen.json

I also changed the URL to point to 2.6.1 instead of stable, because stable changes as new versions are released.

Update leiningen to 2.6.1

---

bucket/docker-compose.json

Also use 'pre_install' hook to rename download to 'docker-compose.exe'
(This mirrors the way the 'docker-machine' package is set up)

Bump 'docker-compose' from 1.6.0 to 1.6.2

---

bucket/rust.json

[Rust 1.7](http://blog.rust-lang.org/2016/03/02/Rust-1.7.html) was just released so here's an update.

Update rust to 1.7.0

---

bucket/rust-msvc.json

Here's the MSVC update for [Rust 1.7](http://blog.rust-lang.org/2016/03/02/Rust-1.7.html).

Update rust-msvc to 1.7.0

---

bucket/erlang.json

According to the downloads page, since OTP 18.0, Erlang/OTP is released under Apache License 2.0 so I updated the license property as well.

Update erlang to 18.2.1

---

bucket/openssl.json

1.0.2f actually leads to a 404, so OpenSSL can't be installed with the 1.0.2f manifest :/

Updates OpenSSL to 1.0.2g

---

bucket/apache.json

The checksums/hashes provided in the current manifest are wrong according to the Apache Lounge website ([64-bit](https://www.apachelounge.com/download/VC14/binaries/httpd-2.4.18-win64-VC14.zip.txt), [32-bit](https://www.apachelounge.com/download/VC14/binaries/httpd-2.4.18-win32-VC14.zip.txt)), and attempting to execute `scoop install apache` yields an error that the hash check failed.
There could have been a silent update or just old hashes kept when updating versions, but either way this change should fix the problem.

Update Apache checksums/hashes

---

bucket/mysql.json

This new manifest provides a MySQL installation. The manifest itself should be pretty self-explanatory, but I'll explain the steps of the post-install script a little more below just for the sake of clarity:
1. The data directory is initialized without generating a root password (this is left for the user if they need it; hence the `--initialize-insecure` option)
2. The existing `my-default.ini` provided with the ZIP archive is copied to `my.ini`, where MySQL is expecting it to be
3. Default client configuration is appended to the `my.ini` file to allow connection on the command line with just `mysql` rather than `mysql --user=root`
This should leave MySQL entirely configurable, yet functioning well enough out-of-the-box for a development machine.
Credit: this manifest is based on [one …

Add mysql app manifest

---

lib/install.ps1

With some installers/uninstallers, there is no need to add arguments when running the executable, and scoop returns an error when there are no arguments present. 400284a fixes this by adding a check if there are arguments present in the manifest, only attempting to pass those arguments if they exist to avoid the error.
Additionally, the current installation method _always_ removes installers after installation; however, with programs such as the Visual C++ Redistributables, the installer is the same as the uninstaller, and needs to be kept for uninstalling in the future. Thus, ee57da6 adds a "keep" flag to the manifest, and does not remove the installer if that flag is present and set to the string "true". This change is fully backwards-compatible, and existing manifests without this flag …

Make installers/uninstallers more flexible

---

bucket/php.json

Add a command to the `post-install` script changing `php.ini` to look in an installation-relative folder for extensions. The default is to look in `C:\php\ext`, which defeats the self-contained nature of scoop apps, and makes them not work out-of-the-box.
Also correct a minor indentation issue by adding a space to a line.

Enable PHP extensions to be found in installation-relative folder

---

lib/install.ps1

Very minor change. I noticed that on some of the test install/uninstalls that I was doing from the `extras` bucket, the shortcuts weren't being removed from the correct start menu group.

Remove shortcuts from `Scoop Apps` on uninstall

---

bucket/apache.json
bucket/php.json
bucket/vc-redist14.json

Reverts the changes in #756, and restores a separate app manifest for the Visual C++ Redistributables, which both `apache` and `php` depend on.
Fixes #763, so this pull request can be merged to restore functionality if there is not another solution found in that issue thread that keeps the preferred method of direct DLL downloads.

Restore separate app for Apache/PHP Visual C++ dependency

---

bucket/git-with-openssh.json
bucket/git.json

Updated Git to 2.8.0 due to new release:
https://github.com/git-for-windows/git/releases/tag/v2.8.0.windows.1

Updated Git to 2.8.0

---

bucket/git-with-openssh.json
bucket/git.json

Update Git to 2.8.1:
https://github.com/git-for-windows/git/releases/tag/v2.8.1.windows.1

Update Git to 2.8.1

---

bucket/ghostscript.json

To convert PDFs to images or vice versa Ghostscript is needed. This installs Ghostscript and gives access to the main app `gswin32c.exe` which is most often needed by other programs (like ImageMagick's apps).

Added Ghostscript. Useful in combination with ImageMagick.

---

bucket/rust.json

The Rust team announced the latest version of Rust, [1.8](http://blog.rust-lang.org/2016/04/14/Rust-1.8.html).

Update rust to 1.8.0

---

bucket/rust-msvc.json

The Rust team announced the latest version of Rust, [1.8](http://blog.rust-lang.org/2016/04/14/Rust-1.8.html).

Update rust-msvc to 1.8.0

---

bucket/apache.json
bucket/r.json

Finally the user can choose wether he or she wants to install the 32bit or 64bit version, thanks to the new `pre-install` feature in the architecture block of the manifest.
Thanks for that, @lukesampson!

Moved the pre-install in r.json to the architecture specific part

---

bucket/php.json

The repository that used to hold the .dll file no longer exists.
This changes the URL to the .dll file and updates the hash to
the new file's md5 hash.
I could not find the 32-bit dll on my system, so that is still missing :disappointed:

Fix URL to 64-bit vcruntime140.dll in php.json

---

bucket/terraform.json

0.6.15 is out now and has increased Windows support for vSphere

Bump Terraform Version

---

bucket/premake5.json

SHA-256 taken from 7-zip; zipped executable premake5.exe still consistent.

Update Premake (alpha) to 5.0.0-alpha8

---

bucket/aria2.json

confirmed repository relocation from github.com/tatsuhiro-t/aria2 to github.com/aria2/aria2.

Update aria2 to 1.22.0

---

bucket/ant.json

url http://mirror.ventraip.net.au/apache//ant/binaries/apache-ant-1.9.6-bin.zip and common mirrors not found;
url changed to mirror www-us.apache.org;

Update Apache Ant to 1.9.7

---

bucket/casperjs.json

confirmed extract directory and bin file casperjs.exe;
confirmed repository relocation of github.com/n1k0/casperjs/ to github.com/casperjs/casperjs/.

Update casperjs to 1.1.1

---

bucket/cmake.json

SHA-256 taken from 7zip, confirmed with https://cmake.org/files/v3.5/cmake-3.5.2-SHA-256.txt.

Update cmake to 3.5.2

---

bucket/dig.json

zip date: 4/28/16, 10:41:00 PM.

Update dig (BIND9) to 9.9.9

---

bucket/doxygen.json

doxysearch.cgi.exe is added to bin.
zip content differences from 1.8.8:
- doxysearch.cgi is replaced with doxysearch.cgi.exe;
- libclang.dll is added.

Update doxygen to 1.8.11

---

bucket/ghostscript.json

gs919w64 contains gswin64.exe & gswin64c.exe
-> replaced "bin": ["bin\\\gswin32c.exe"] with "env_add_path": "bin";
Ghostscript manifest tested on external bucket.
[Ghostscript releases from 9.19 have been moved to GitHub](http://downloads.ghostscript.com/public/).
Current links are inaccessible (9.18):
http://downloads.ghostscript.com/public/gs918w64.exe
http://downloads.ghostscript.com/public/gs918w32.exe
Working links (9.18):
http://downloads.ghostscript.com/public/old-gs-releases/gs918w64.exe
http://downloads.ghostscript.com/public/old-gs-releases/gs918w32.exe

Update Ghostscript to 9.19

---

bucket/git-lfs.json

extract directory now exists in release zip
-> added "extract_dir" for both architectures.
git-lfs manifest tested on external bucket.

Update git-lfs to 1.2.0

---

bucket/nodejs.json

**Notable Changes**
- assert: deep{Strict}Equal() now works correctly with circular references. (Rich Trott) #6432
- debugger: Arrays are now formatted correctly in the debugger repl. (cjihrig) #6448
- deps: Upgrade OpenSSL sources to 1.0.2h (Shigeki Ohtsu) #6550
- net: Introduced a Socket#connecting property. (Fedor Indutny) #6404
- Previously this information was only available as the undocumented, internal _connecting property.
- process: Introduced process.cpuUsage(). (Patrick Mueller) #6157
- stream: Writable#setDefaultEncoding() now returns this. (Alexander Makarenko) #5040
- util: Two new additions to util.inspect():
- Added a maxArrayLength option to truncate the formatting of Arrays. (James M Snell) #6334
This is set to 100 by default.
- Added a showProxy option for formatting …

Upgrade NodeJS to 6.1.0

---

bucket/hub.json

confirmed Windows package tar.gz change to zip following 2.2.2
-> removed "extract_dir" for both architectures;
-> changed "bin": ["hub.exe"] to "bin": ["bin\\\hub.exe"]
hub manifest tested on external bucket:
````
~$ hub version
git version 2.8.2.windows.1
hub version 2.2.3
````
package content differences from 2.2.0 & 2.2.1:
- extract directory folder removed
- hub manual "hub.html" moved
- "etc" and "man" build folders removed
- hub.exe moved to package "bin" folder

Update hub to 2.2.3

---

bucket/nuget.json

SHA-256 taken from 7zip.
There exists a ["latest"](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) download location for NuGet, but corresponding version link is used.

Update NuGet to 3.4.3

---

bucket/mediainfo.json

SHA-256 taken from 7zip.
Alternative downloads from main site available:
x86: http://mediaarea.net/download/binary/mediainfo/0.7.85/MediaInfo_CLI_0.7.85_Windows_i386.zip
x64: http://mediaarea.net/download/binary/mediainfo/0.7.85/MediaInfo_CLI_0.7.85_Windows_x64.zip

Update MediaInfo to 0.7.85

---

bucket/mariadb.json

MD5 taken from site.
[Multiple stable releases exist for MariaDB;](https://downloads.mariadb.org/mariadb/+releases/)
Update taken from 10.0 series.

Update MariaDB to 10.0.25

---

bucket/imagemagick.json

magick.exe found in packages for both architectures
-> added magick.exe to shim
imagemagick manifest tested on external bucket (assumed no change to package file structure)
Unavailable links (6.9.3-8):
http://www.imagemagick.org/download/binaries/ImageMagick-6.9.3-8-portable-Q16-x64.zip
http://www.imagemagick.org/download/binaries/ImageMagick-6.9.3-8-portable-Q16-x86.zip
[Binary releases](http://www.imagemagick.org/download/binaries/) contain only latest modern and latest legacy version.
[Existing releases](http://www.imagemagick.org/download/windows/releases/) contain only versions to latest following 6.4.9-10 (all stopping at hotfix 10).

Update ImageMagick to 7.0.1-2

---

lib/git.ps1
libexec/scoop-bucket.ps1
libexec/scoop-status.ps1
libexec/scoop-update.ps1

Commands that call git from scoop will now pass proxy details. The
command is executed using `cmd` to avoid polluting the user's
environment as the variables set will die with the process.
Fixes #842

Fix scoop not using proxy for git commands

---

bucket/curl.json

[curl manifest file tested on external bucket](http://puu.sh/oQq83/d131b4a4fa.png)
Mirror changes:
- mirror confusedbycode.com looks abandoned;
- mirror bintray.com from list Win32/Win64 - Generic (Viktor Szakáts) was chosen
- build project page for windows is hosted on https://github.com/vszakats/harbour-deps

Update cURL to 7.48.0

---

bucket/nodejs.json

Notable changes
- buffer: fix lastIndexOf and indexOf in various edge cases (Anna Henningsen) #6511
- child_process: use /system/bin/sh on android (Ben Noordhuis) #6745
deps:
- upgrade npm to 3.8.9 (Rebecca Turner) #6664
- upgrade to V8 5.0.71.47 (Ali Ijaz Sheikh) #6572
- upgrade libuv to 1.9.1 (Saúl Ibarra Corretgé) #6796
- Intl: ICU 57 bump (Steven R. Loomis) #6088
- repl:
- copying tabs shouldn't trigger completion (Eugene Obrezkov) #5958
- exports Recoverable (Blake Embrey) #3488
- src: add O_NOATIME constant (Rich Trott) #6492
- src,module: add --preserve-symlinks command line flag (James M Snell) #6537
- util: adhere to noDeprecation set at runtime (Anna Henningsen) #6683
As of this release the 6.X line now includes 64-bit binaries for Linux on Power Systems running in big endian …

Update NodeJS to 6.2.0

---

bucket/terraform.json

Previous update updated the version and the zip files to be downloaded but failed to update the hashes.
Also adds two shims that are new with the latest terraform version.

Fix terraform.json

---

libexec/scoop-search.ps1

invoke-webrequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.

#864 Fix following issue when searching on a new Win10

---

bucket/imagemagick.json

Download for 7.0.1-2 returns a 404 since only the latest binary is stored
Bumped to 7.0.1-6 and updated hashes

bump imagemagick 7.0.1-2 -> 7.0.1-6

---

bucket/mozjpeg.json

mozjpeg.codelove.de appears to have switched to https.
updated the download url

use https to fix mozjpeg.codelove.de 301/404

---

bucket/openssl.json

External apps depend on DLLs exported by openssl (ssleay32.dll and libeay32.dll in my particular case), so I thought it would be nice to have the in PATH automatically after installation.

OpenSSL: Add executables and DLLs to PATH.

---

bucket/nvm.json

This will install a working copy of nvm, it also installs all the nodes in the dir where scoop install nvm, which is nice because unless installed Globally should allow users to use different nodes versions. 
Sorry for taking so long. Fixes #783

Added NVM to the bucket

---

bucket/rust.json

Rust [1.9](http://blog.rust-lang.org/2016/05/26/Rust-1.9.html) is out.

Update rust to 1.9.0

---

bucket/rust-msvc.json

Rust [1.9](http://blog.rust-lang.org/2016/05/26/Rust-1.9.html) is out.

Update rust-msvc to 1.9.0

---

bucket/php-nts.json

- Core:
- Fixed bug #72172 (zend_hex_strtod should not use strlen).
- Fixed bug #72114 (Integer underflow / arbitrary null write in fread/gzread). (CVE-2016-5096)   Fixed bug #72135 (Integer Overflow in php_html_entities). (CVE-2016-5094)
- GD:
- Fixed bug #72227 (imagescale out-of-bounds read). (CVE-2013-7456)
- Intl:
- Fixed bug #64524 (Add intl.use_exceptions to php.ini-*).
- Fixed bug #72241 (get_icu_value_internal out-of-bounds read). (CVE-2016-5093)
- Postgres:
- Fixed bug #72151 (mysqli_fetch_object changed behaviour).

Update php-nts to 5.6.22

---

bucket/php.json

- Core:
- Fixed bug #72162 (use-after-free - error_reporting).
- Add compiler option to disable special case function calls.
- Fixed bug #72101 (crash on complex code).
- Fixed bug #72100 (implode() inserts garbage into resulting string when joins very big integer).
- Fixed bug #72057 (PHP Hangs when using custom error handler and typehint).
- Fixed bug #72038 (Function calls with values to a by-ref parameter don't always throw a notice).
- Fixed bug #71737 (Memory leak in closure with parameter named $this).
- Fixed bug #72059 (?? is not allowed on constant expressions).
- Fixed bug #72159 (Imported Class Overrides Local Class Name).
- Curl:
- Fixed bug #68658 (Define CURLE_SSL_CACERT_BADFILE).
- DBA:
- Fixed bug #72157 (use-after-free caused by dba_open).
- GD:
- Fixed bug #72227 …

Update to php 7.0.7

---

bucket/nodejs.json

* **buffer**: Ignore negative lengths in calls to `Buffer()` and `Buffer.allocUnsafe()`. This fixes a possible security concern (reported by Feross Aboukhadijeh) where user input is passed unchecked to the Buffer constructor or `allocUnsafe()` as it can expose parts of the memory slab used by other Buffers in the application. Note that negative lengths are not supported by the Buffer API and user input to the constructor should always be sanitised and type-checked. (Anna Henningsen) [#7051](https://github.com/nodejs/node/pull/7051)
* **npm**: Upgrade npm to 3.9.3 (Kat Marchán) [#7030](https://github.com/nodejs/node/pull/7030)
- [`npm/npm@42d71be`](https://github.com/npm/npm/commit/42d71be2cec674dd9e860ad414f53184f667620d) [npm/npm#12685](https://github.com/npm/npm/pull/12685) When using …

Update NodeJs to 6.2.1 (security update)

---

bucket/nodejs.json

- http:
- req.read(0) could cause incoming connections to stall and time out under certain conditions. (Fedor Indutny) #7211
- When freeing the socket to be reused in keep-alive Agent wait for both prefinish and end events. Otherwise the next request may be written before the previous one has finished sending the body, leading to a parser errors. (Fedor Indutny) #7149
- npm: upgrade npm to 3.9.5 (Kat Marchán) #7139

Upgrade nodejs to 6.2.2

---

bucket/resharper-clt.json

I just discovered your amazing package manager for Windows and I've immediately moved from Chocolatey. It's really well designed and maintaining apps are cheap, expressive and clear.
I would like to add ReSharper Command Line Tools which is free to use to the main bucket. I think many of .NET developers that relies on ```scoop``` will benefit by having it.
By the way, thanks for [pshazz](https://github.com/lukesampson/pshazz) :+1:

Adding ReSharper Command Line Tools 2016.1.2

---

bucket/php.json

- Core:
- Fixed bug #72218 (If host name cannot be resolved then PHP 7 crashes).
- Fixed bug #72221 (segfault, past-the-end access).
- Fixed bug #72268 (Integer Overflow in nl2br()).
- Fixed bug #72275 (Integer Overflow in json_encode()/json_decode()/ json_utf8_to_utf16()).
- Fixed bug #72400 (Integer Overflow in addcslashes/addslashes).
- Fixed bug #72403 (Integer Overflow in Length of String-typed ZVAL).
- FPM:
- Fixed bug #72308 (fastcgi_finish_request and logging environment variables).
- GD:
- Fixed bug #72298 (pass2_no_dither out-of-bounds access).
- Fixed bug #72337 (invalid dimensions can lead to crash) (Pierre)
- Fixed bug #72339 (Integer Overflow in _gd2GetHeader() resulting in heap overflow).
- Fixed bug #72407 (NULL Pointer Dereference at _gdScaleVert).
- Intl:
- Fixed bug …

Update PHP to 7.0.8

---

bucket/php.json

When upgrading PHP version, the php.ini file is reset. So, I used PHP_INI_SCAN_DIR $env var to add an additional path to load php config files: /php/conf/.
I think this little change can simplify the PHP upgrading process.

Add the ability to have an additional php.ini file

---

bucket/python.json

changed checksums from md5 to sha256.
also only tested the 64bit version, but checksums was calculated from the correct binary so it "should work"

python 3.5.2

---

bucket/mariadb.json

only verified install of 64-bit build, but 32-bit binary checksum was calculated from https://downloads.mariadb.org/f/mariadb-10.1.14/win32-packages/mariadb-10.1.14-win32.zip so that too "should" work. verified install worked by manually starting mysqld.exe

mariadb: 10.1.14

---

bucket/curl.json

again, only verified the 64-bit install. 32-bit checksum was calculated from https://bintray.com/artifact/download/vszakats/generic/curl-7.49.1-win32-mingw.7z, so it "should" work too

curl 7.49.1

---

bucket/mongodb.json

tested 32+64 bit install, verified 64-bit install working by starting mongod.exe and connecting using robomongo gui (https://robomongo.org)
there's an error on my 64bit system when starting the 32-bit mongod.exe:
```
scoop mongodb * $ mongod
2016-07-05T12:49:36.427+0200 I CONTROL  [main]
2016-07-05T12:49:36.429+0200 W CONTROL  [main] 32-bit servers don't have journaling enabled by default. Please use --journal if you want durability.
2016-07-05T12:49:36.429+0200 I CONTROL  [main]
2016-07-05T12:49:36.523+0200 I CONTROL  [main] Hotfix KB2731284 or later update is not installed, will zero-out data files
2016-07-05T12:49:36.526+0200 I CONTROL  [initandlisten] MongoDB starting : pid=10600 port=27017 dbpath=C:\data\db\ 32-bit host=xxx
2016-07-05T12:49:36.527+0200 I CONTROL  [initandlisten] …
```

mongodb 3.2.7

---

bucket/nginx.json

this version of nginx has HTTP/2 support.
note: both the previous packaged nginx and this new one errors out on startup with this error, so additional post-install would be better. unsure what to do to improve situation
```
nginx: [alert] could not open error log file: CreateFile() "logs/error.log" failed (3: The system cannot find the path specified)
2016/07/05 13:05:10 [emerg] 12452#10072: CreateFile() "C:\Users\m\dev\scoop/conf/nginx.conf" failed (3: The system cannot find the path specified)
```

nginx 1.11.1

---

bucket/php.json

Please note: https://raw.githubusercontent.com/MPLew-is/scoop-wamp/master/visual-c-redistributables/14/32-bit/vcruntime140.dll no longer exists, so I could not test the 32-bit install of this bucket

php: sha256 hash

---

bucket/php-nts.json

with this patch (and the previous ones) all sha1 & md5 hashes should be eradicated

php-nts 7.0.8

---

bucket/dotnet.json

Allows scoop to install .NET Core CLI and SDK.

Add .NET Core app manifest

---

bucket/nodejs.json

* **buffer**: Added `buffer.swap64()` to compliment `swap16()` & `swap32()`. (Zach Bjornson) [#7157](https://github.com/nodejs/node/pull/7157)
* **build**: New `configure` options have been added for building Node.js as a shared library. (Stefan Budeanu) [#6994](https://github.com/nodejs/node/pull/6994)
- The options are: `--shared`, `--without-v8-platform` & `--without-bundled-v8`.
* **crypto**: Root certificates have been updated. (Ben Noordhuis) [#7363](https://github.com/nodejs/node/pull/7363)
* **debugger**: The server address is now configurable via `--debug=<address>:<port>`. (Ben Noordhuis) [#3316](https://github.com/nodejs/node/pull/3316)
* **npm**: Upgraded npm to v3.10.3 (Kat Marchán) [#7515](https://github.com/nodejs/node/pull/7515) & (Rebecca Turner) …

Update nodejs to 6.3.0

---

bucket/latex.json

Previously, only pdflatex and latex were added to PATH. However, xelatex and mpm and all the other stuff is useful from time to time. I'm not 100% sure this is the right decision, but it definitely is for me as an extensive LaTeX user.

LaTeX: The whole zoo of executables is now added to PATH

---

bucket/php.json

- Core:
- Fixed bug #72508 (strange references after recursive function call and "switch" statement).
- Fixed bug #72513 (Stack-based buffer overflow vulnerability in virtual_file_ex).
- Fixed bug #72573 (HTTP_PROXY is improperly trusted by some PHP libraries and applications).
- bz2:
- Fixed bug #72613 (Inadequate error handling in bzread()).
- CLI:
- Fixed bug #72484 (SCRIPT_FILENAME shows wrong path if the user specify router.php).
- COM:
- Fixed bug #72498 (variant_date_from_timestamp null dereference).
- Curl:
- Fixed bug #72541 (size_t overflow lead to heap corruption).
- Exif:
- Fixed bug #72603 (Out of bound read in exif_process_IFD_in_MAKERNOTE).
- Fixed bug #72618 (NULL Pointer Dereference in exif_process_user_comment).
- GD:
- Fixed bug #43475 (Thick styled lines have scrambled …

Upgrade PHP to 7.0.9

---

bucket/nodejs.json

* **buffer**:
* Improve performance of Buffer.from(str, 'hex') and Buffer#write(str, 'hex'). (Christopher Jeffrey) [#7602](https://github.com/nodejs/node/pull/7602)
* Fix creating from zero-length ArrayBuffer. (Ingvar Stepanyan) [#7176](https://github.com/nodejs/node/pull/7176)
* **deps**:
* Upgrade to V8 5.0.71.xx. (Ben Noordhuis) [#7531](https://github.com/nodejs/node/pull/7531)
* Backport V8 instanceof bugfix (Franziska Hinkelmann) [#7638](https://github.com/nodejs/node/pull/7638)
* **repl**: Fix issue with function redeclaration. (Prince J Wesley) [#7794](https://github.com/nodejs/node/pull/7794)
* **util**: Fix inspecting of boxed symbols. (Anna Henningsen) [#7641](https://github.com/nodejs/node/pull/7641)

Upgrade node to 6.3.1

---

bucket/php.json

When sha1 is used, we need to specify "sha1:" in the hash

fixing hash issue

---

bucket/minisign.json

* The default location of the secret key was changed to ~/.minisign/minisign.key.
* Generating a new set of keys (-G) doesn't replace an existing key pair any more; the additional -f switch is required in order to force this operation.
* Improved error messages and Windows compatibility.
* A man page was added.

Update to 0.7

---

bucket/thrift.json

I would like to suggest the addition of [Apache Thrift](http://thrift.apache.org) to the main repo.
Thrift is a developer tool to create distributed services with serialization across several programming language
Thanks,
Gustavo

Add Apache Thrift 0.9.3

---

bucket/imagemagick.json

Old version 7.0.1-8 returns a 404 as usual.
Bump to latest version 7.0.2-6 until it gets updated again.

Upgrade ImageMagick to 7.0.2-6

---

bucket/youtube-dl.json

Reverts lukesampson/scoop#984, due to failed hash check for some and Windows Defender detects malware (Win32/Tefau.A!cl).

Revert "Update youtube-dl to latest version"

---

bucket/cmake.json

Hashes available here: https://cmake.org/files/v3.6/cmake-3.6.1-SHA-256.txt

Update CMake to 3.6.1

---

bucket/youtube-dl.json

Youtube-dl updated again.
Here is a link to the file on virustotal in case there's worry about there being something wrong with it this time:
https://virustotal.com/en/url/c5d7188f77b19ed13a0f9f00690aece860b70088a2b280f1c3711c87a4dcd83b/analysis/1471039807/
I also changed the license to public domain, which is more correct than "unlicensed" and added a checkver function, because this app updates frequently.

Update youtube-dl to version 2016.08.12

---

bucket/openjdk.json

since https://github.com/alexkasko/openjdk-unofficial-builds is decomissioned, moving to https://github.com/ojdkbuild/ojdkbuild instead

upgrade to ojdkbuild 1.8.0_102-1

---

bucket/go.json

Go [1.7](https://blog.golang.org/go1.7) has just been released.

Update go to 1.7

---

bucket/pngcrush.json

the current formula is broken since they moved the 1.8.1 binaries to a "old-executables" folder on sourceforge :-/

pngcrush 1.8.4

---

bucket/rust.json

Rust [1.11](https://blog.rust-lang.org/2016/08/18/Rust-1.11.html) was recently released.

Update rust to 1.11.0

---

bucket/rust-msvc.json

Rust [1.11](https://blog.rust-lang.org/2016/08/18/Rust-1.11.html) was recently released.

Update rust-msvc to 1.11.0

---

bucket/resharper-clt.json
bucket/thrift.json

JetBrains launched an updated version of its popular ReSharper plugin and this PR update it to the latest version.
I've also fixed update checkers for thrift and resharper-clt packages as now I can use ```checkver.ps1``` script to detect new versions.
Thanks

Update ReSharper CLT to 2016.2

---

bucket/make.json

I've found a more updated ```make``` source for Windows at http://www.equation.com/servlet/equation.cmd?fa=make
I think it's a good idea to change the scoop location to it.
Thoughts?
Thanks,
Gustavo

Change make source

---

bucket/pngcrush.json

Version 1.8.4 was moved to an old_versions directory so this manifest wasn't functioning any more.
Updated urls to those from here: https://sourceforge.net/projects/pmt/files/pngcrush-executables/1.8.6/
Used sha1 hash as listed on sourceforge.

Update pngcrush manifest to version 1.8.6

---

bucket/imagemagick.json

Error:
> scoop install imagemagick
installing imagemagick (7.0.3-0)
downloading http://www.imagemagick.org/download/binaries/ImageMagick-7.0.3-0-portable-Q16-x64.zip...(79.6 MB) done
checking hash...hash check failed for http://www.imagemagick.org/download/binaries/ImageMagick-7.0.3-0-portable-Q16-x64.zip. expected: d43764a0134bb4c4ede1ea55e561ac
fb0e246c55ddf2130440ba13b12c20954c, actual: 4c266eb5786bc1b0ae604ffbd8993f648817b2b5ba2cfb1dd8df335980fcbffd!
Note: I assume 32bit hash is wrong too

Fixed ImageMagick 64bit package hash

---

bucket/openssl.json

The old installer for 1.1.0 seems to have been removed, so OpenSSL currently fails to install

Updates OpenSSL to 1.1.0b

---

bucket/rg.json

ripgrep is a new and very fast grep/ag/ack replacement written in rust.
introduction blog: http://blog.burntsushi.net/ripgrep/

add ripgrep 0.2.1

---

bucket/rust.json

Rust 1.12 - https://blog.rust-lang.org/2016/09/29/Rust-1.12.html

Update rust to 1.12.0

---

bucket/git-with-openssh.json

Again, simply copied and pasted the changes from #1067.
Should we add some kind of a comment to both manifests, so that maintainers are aware that there are two of them?

Update git-with-openssh to 2.10.1.windows.1

---

bucket/yarn.json

This bucket currently fails to install on my system, because "nodejs" path is too long (bug #1104)

yarn 0.16.1

---

libexec/scoop-cache.ps1

If cache is empty `$total_length` is null, and the output is:
```
λ scoop cache show some-non-existing-app
total: 0 files,  B
```
Cast sum to double to get '0 B' instead

Print '0 B' when cache is empty

---

bucket/vim.json

Vim uses a more specific version number than used in the bucket. The `vim80` link is always the newest version (currently 8.0.069).
I updated the links to the specific version, so the hash check does not fail after each update.
Checkver now checks for the more specific version (8.0.xxx)

update vim 8.0.069 / optimize checkver (fix #1111)

---

bucket/apache.json

It's the same version but compiled with newer OpenSSL versions
https://www.apachelounge.com/viewtopic.php?p=33747

update apache hashs (#1108)

---

bucket/aria2.json
bucket/cmake.json
bucket/ffmpeg.json
bucket/git-lfs.json
bucket/git-with-openssh.json
bucket/git.json
bucket/imagemagick.json
bucket/nodejs.json
bucket/packer.json
bucket/perl.json
bucket/php-nts.json
bucket/php.json
bucket/r.json
bucket/sbcl.json
bucket/sqlite.json
bucket/terraform.json
bucket/vagrant.json

I found the `bin/checkver` tool and was bored :-)
All apps expect `nano` (can't find a binary) and `rancher-compose` (not a stable release) are now up-to-date.

Update outdated apps

---

bucket/rust.json

[Rust 1.13.0](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html)

Update rust to 1.13.0

---

bin/checkver.ps1
bucket/nodejs.json
lib/autoupdate.ps1

Hi
Some time ago I added `checkver` informations to a lot of manifests, now we know that a lot of manifests are outdated. It will take a lot of work to update all those manifests manually.
I started implementing an easy way to update manifests. The idea is that the `checkver` script not only finds the newest version string but also the download urls and hashes for the files.
Most time the download url can be build by only knowing the version string, alternatively it can be extracted from the website. The hashes can be obtained from the download page (php etc.) or from a separate file (nodejs etc.) the last resort would be downloading the file and hash it locally.
I implemented a the base for it, the nodejs manifest contains the new `autoupdate` block. Running `bin/checkver.ps1 nodejs -u` …

First implementation of manifest autoupdate

---

bucket/ruby.json

version + hash changes only
hashes from https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.3.3#release

Update ruby to 2.3.3

---

bucket/apache.json

Installation was broken because the old distro was removed from the web page.

Update apache 2.4.23-->2.4.25.

---

bucket/rust.json

Rust [1.14.0](https://blog.rust-lang.org/2016/12/22/Rust-1.14.html) shipped today.

Update rust to 1.14.0

---

bucket/rust-msvc.json

Rust [1.14.0](https://blog.rust-lang.org/2016/12/22/Rust-1.14.html) shipped today.

Update rust-msvc to 1.14.0

---

bin/install.ps1

I've tested this by running updated script as below:
```iex (new-object net.webclient).downloadstring('https://gist.githubusercontent.com/mikhail-tsennykh/f65a3addf22b36681b1eb7c6d708bed2/raw/4040fe0c156512a63b1dcfea2fd5595b26e1a1f1/scoop%2520auto%2520set%2520execution%2520policy%2520test')```
nice to skip extra step (unless there is some good reason not to do it on scoop install).

set execution policy on scoop install

---

bucket/dotnet.json

The code release version is actually `1.0.0-preview2-1-003177`, however it is packaged as `1.1` in the official download page https://www.microsoft.com/net/download/core#/sdk/current. So I opt to `1.1` that instead of the never ending and non-distinguishable `1.0.0-preview2-*` versions

upgrade dotnet core to 1.1

---

bucket/git-with-openssh.json
bucket/git.json

Manager has apparently replaced the wincred helper as of 2.x.

Use manager credential helper for git

---

lib/decompress.ps1

Thank you for really great software!
I like scoop so much.
Please add support for extracting .lzh format.
Because in Japan, some softwares is provided this legacy format...
ex)  http://ftp.vector.co.jp/43/51/2176/SoftTilt111.lzh
7zip can extract .lzh format.

Add support for lzh format. (with 7zip)

---

bucket/far.json
bucket/git-lfs.json
bucket/git-up.json
bucket/imagemagick.json
bucket/kotlin.json
bucket/mercurial.json
bucket/modd.json
bucket/ninja.json
bucket/nodejs-lts.json
bucket/openjdk.json
bucket/rg.json
bucket/scriptcs.json
bucket/syncany-cli.json
bucket/xz.json
bucket/youtube-dl.json
lib/autoupdate.ps1

Updated apps
- nodejs-lts
- mercurial
- git-lfs
- youtube-dl
- syncany-cli
- _more following …_
Fixes
- autoupdate regression on hashing type `extract`
- autoupdate error when no `architecture` option was set
- far version number used another notation as checkver would report
- do not check chocolatey urls with HEAD request
New features
- `autoupdate.note` to show a message when autoupdate is run

Some updates and autoupdate fixes and improvements

---

bucket/adb.json

Google now provides a small package only containing `adb` and `fastboot`.
https://developer.android.com/studio/releases/platform-tools.html
Could be handy 👍

Add Android SDK Platform Tools adb and fastboot

---

lib/autoupdate.ps1

Works for [Semantic Versioning](http://semver.org/).
Version `3.7.1-rc.1`
Then: $majorVersion (3), $minorVersion (3.7), $patchVersion (3.7.1)
Now: $majorVersion (3), $minorVersion (7), $patchVersion (1), $preReleaseVersion (rc.1)

Change version templates

---

bin/checkver.ps1
lib/autoupdate.ps1

Now it's possible to use `$match1`, `$match2`, and so on in the url. Also named groups are supported.
A regex like `v(?<version>[\d\w.]+)\/PortableGit-(?<short>[\d.]+).*\.exe` will result in `$matchVersion` and `$matchShort`.
I wrote this change mainly for autoupdating git-for-windows, because of there strange versioning on github.
Example git bucket:
```
{
"_comment": "Maintainers: when updating this manifest to a new version, you might like to also update git-with-openssh.json",
"homepage": "https://git-for-windows.github.io/",
"license": "GPL2",
"version": "2.11.0.windows.3",
"architecture": {
"64bit": {
"url": "https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.3/PortableGit-2.11.0.3-64-bit.7z.exe#/dl.7z",
"hash": …
```

Add matching regex groups as url templates

---

bin/auto-pr.ps1

Automated creation of pull-requests for new manifest updates.
This needs to be tested a bit more.
This works a bit like greenkeeper.io but as a your own cronjob.
It runs `checkver.ps1 * -u`, commits every updated manifest to its own branch (named $app-$version). Then pushs it and creates a pull-request. Ideally you only need to click `merge` 👍

Proposing auto-pull-request command (needs testing 🔥)

---

bucket/resharper-clt.json

Updating Resharper CLT to latest version (2016.3.1).
Thanks,
Gustavo

Update Resharper CLT to 2016.3.1

---

bucket/haxe.json

Haxe 3.4.0-rc.2 config typo
Error:
```
installing haxe (3.4.0-rc.2)
loading https://haxe.org/website-content/downloads/3.4.0-rc.2/downloads/haxe-3.4.0-rc.2-win.zip from cache...
checking hash...ok
extracting...error moving directory:
-------------------------------------------------------------------------------
ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------
Started : Saturday, 21 January, 2017 19:35:27
Source : C:\Users\Zweimal\AppData\Local\scoop\apps\haxe\3.4.0-rc.2\_scoop_extract\haxe-3.4.0-rc.2\
Dest : C:\Users\Zweimal\AppData\Local\scoop\apps\haxe\3.4.0-rc.2\
Files : *.*
Options : *.* /S /E /DCOPY:DA /COPY:DAT /MOVE /R:1000000 /W:30
----------------------------------------------------------------------- …
```

Fix: Haxe 3.4.0-rc.2 bucket error moving dir

---

README.md

http://scoop.sh/ was updated to recommend `remotesigned` vs `unrestricted` but the README wasn't
Fixes #1221 - Change installation instructions to recommend RemoteSigned instead of Unrestricted

remotesigned in README fixes #1221

---

libexec/scoop-reset.ps1

`scoop reset` is currently erroring at an undefined `get_config` call:
```
$ scoop reset $app
resetting $app ($version)
get_config : The term 'get_config' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At $path\scoop\apps\scoop\current\lib\install.ps1:638 char:8
+     if(get_config NO_JUNCTIONS) { return $versiondir }
+        ~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (get_config:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
In this PR I just followed the other commands' structure and sourced `lib/config.ps1` from `scoop-reset.ps1`. Feel free to close this if it's not the correct approach …

Fix scoop-reset's undefined `get_config` error

---

lib/autoupdate.ps1

Remove -SkipLast to restore Powershell 3 compatibility (fixes #1278)

---

bucket/openjdk.json

releases/lastest isn't reliable. Using the announced version from the readme should work better.

Fix openjdk checkver

---

lib/autoupdate.ps1

NuGet-Galleries (such as nuget.org or chocolatey.org) don't seem to support `HEAD` requests.

Assume that nuget.org URLs are valid

---

test/Scoop-Manifest.Tests.ps1

Manifest validation should fail if there are untranslated variables left over in url or extract_dir

Improve manifest validation tests for url and extract_dir

---

lib/install.ps1

The download output was always rudimentary and I have toyed with the idea of being able to replace the downloader with something like aria2c or axel. Initially I aimed at a general refactor but once I started going I couldn't help but make the download progress a bit nicer

Download functionality refactor

---

bucket/yarn.json

Maybe `nvm` should also be listed as a Node.js alternative?

Suggest nodejs-lts as an alternative to nodejs

---

bucket/git-lfs.json

Fixes:
````
Extracting... Error moving directory:
-------------------------------------------------------------------------------    ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------    Started : Thu Feb 16 16:22:35 2017     Source :
C:\Users\ross\scoop\apps\git-lfs\1.5.6\_scoop_extract\git-lfs-windows-amd64-1.5.6\      Dest : C:\Users\ross\scoop\apps\git-lfs\1.5.6\      Files : *.*                Options : *.* /S /E
/COPY:DAT /MOVE /R:1000000 /W:30   ------------------------------------------------------------------------------  2017/02/16 16:22:35 ERROR 2 (0x00000002) Accessing Source Directory
C:\Users\ross\scoop\apps\git-lfs\1.5.6\_scoop_extract\git-lfs-windows-amd64-1.5.6\ The system cannot find the file …
```

Remove extract_dir from git-lfs

---

schema.json

* Use architecture definition
* Arrays of string shouldn't be empty
* Add back uniqueItems directive
* match version against pattern from [lib/install.ps1#L21](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L21))
* `extract_dir` in autoupdate only works with string (at the time)
* reindent

Improvements for schema.json

---

bucket/fossil.json

Fossil is the version control system used by sqlite, among others. I didn't quite get autoupdate working, because I can't find a single page that has only one version number on it, which is causing checkver to behave a bit unpredictably. That said, they do like four releases a year, tops; I'll just do this by hand.

Add fossil 1.37

---

bucket/curl.json

Upstream must have pushed a new build out, without bumping the version.

Fix hashes in curl

---

bin/checkver.ps1
lib/autoupdate.ps1
lib/install.ps1

do_dl() now rethrows an exception instead of aborting. this prevents killing the autoupdate process prematurely and thus skipping queued updates.

Better error handling for autoupdate and checkver

---

bin/checkver.ps1
bucket/bfg.json
bucket/dart.json
bucket/nuget.json
bucket/openssl.json
lib/autoupdate.ps1
lib/json.ps1
schema.json

* Add jsonpath support for checkver and hash extraction
* Unravel if-blocks in checkver
* Use new jsonpath for openssl, nuget, dart and bfg
Note: this is a basic implementation of http://goessner.net/articles/JsonPath/
only supporting array `[]` and property `.` selecting

jsonpath support, autoupdate and checkver refactor

---

lib/core.ps1

Use environment variable SCOOP_CACHE to override cache dir

---

bucket/openssh.json

I've been experiencing quite a bit of issues with the setting of $HOME env var causing failures in building Unreal Engine HTML5 WebGL: https://answers.unrealengine.com/questions/457972/could-not-find-file-epic-games412engineintermediat.html
Follow their support team's suggestions, I look around in my `scoop` installations for where $HOME was being set. And I noticed that `env_ensure_home` is commented out and the general direction in scoop is not to set $HOME:
https://github.com/lukesampson/scoop/blob/a6f6e5425f873098a565b4e85b7639053d0c894e/lib/install.ps1#L840
However I did find $HOME still being set in `openssh` which I have installed in my system. So that's what this PR is about.

remove unncessary setting of $HOME env var which causes other issues

---

bucket/pshazz.json

I assume the version of pshazz is just the date?

update pshazz – adds ssh hostname completion

---

bucket/dotnet.json

This updates the `dotnet` manifest to v1.1.1. Or, at least that's the version the ZIP-file has in it's name.
@yunspace @jggrant do these changes look right to you?

Update dotnet to 1.1.1

---

bucket/yarn.json

The Yarn package should use the official download URLs rather than the GitHub URLs 😃

Update URLs for Yarn

---

lib/install.ps1

Came across this when tried to install zip.
ContentLength is -1 when downloading from their server.

FTP SIZE request

---

bucket/axel.json

Repaired the axel app manifest to use maintainer release (https://github.com/ghuntley/cygwin-axel) instead of dropbox

Repaired the axel app manifest 

---

lib/core.ps1

In Windows 10, at least after the Creators update, $h is of type
PathInfo, which does not support String operations.  By toStringing it,
we turn it into a String and enable the expected String operations.
see https://github.com/lukesampson/scoop/issues/1440

Fixed bug where $home doesn't support .endswith

---

bucket/sbt.json

When trying to install latest sbt package (` 0.13.15`) .
It fails to copy extracted zip folders `sbt-launcher-packaging-0.13.15`.
It seems archive folder name is changed to "sbt" from v0.13.15.
I've confirmed next pre-release package `1.0.0-M5` use same folder naming.
<https://github.com/sbt/sbt/releases>

Fix sbt package installation problem

---

bucket/sonarqube-x86-64.json

This is a simple manifest for running [SonarQube](https://www.sonarqube.org/) in local machine.

sonarqube-x86-64 added

---

bucket/hugo.json

As of version 0.20.3 the script is no longer needed.
https://github.com/spf13/hugo/issues/3385#issuecomment-297148887

Fix hugo pre_install script

---

lib/install.ps1

Prevent failure, when path contains whitespaces

Quote source and target paths

---

lib/autoupdate.ps1

To allow something like this:
```
"license": "https://<some-site>/1.0.0/license/en.html",
"autoupdate": {
"url": "https://<some-site>/$version/<software>-$version.zip",
"license": "https://<some-site>/$version/license/en.html"
}
```

Version substitution for license property

---

bucket/cmder.json

Cmder starts complaining if these are not available.
I did not have to set them when I was using the full installation; this must just be an issue with the mini client.

Added Cmder env variables

---

bucket/git.json

The GIT_INSTALL_ROOT env is required by cmder, otherwise it starts giving "Found old git at C:\Users\<name>\scoop\apps, but not using..."

Set GIT_INSTALL_ROOT variable on installation

---

bucket/diffutils.json

because diff utils from msys crash under win10

use diffutils from msys2

---

bin/auto-pr.ps1
bin/checkurls.ps1
bin/checkver.ps1
lib/autoupdate.ps1
lib/core.ps1
lib/install.ps1
lib/psmodules.ps1
lib/unix.ps1
lib/versions.ps1
test/00-Project.Tests.ps1
test/Scoop-Core.Tests.ps1
test/Scoop-Install.Tests.ps1
test/Scoop-Manifest.Tests.ps1
test/Scoop-TestLib.ps1

These changes allow running maintenance jobs like `checkver.ps1` and `auto-pr.ps1` on Ubuntu or MacOS.
My main goals are to run these jobs on my Ubuntu server instead of using a Windows VM.
This includes:
- Fixing an error with Ssl3 which is no longer supported in Powershell 6
- Detecting `hub` correctly
- Setting up the correct paths for `$scoopdir`, `$globaldir` and `$cachedir`
- Using `sha256sum` on Linux and `shasum` on MacOS, because `system.security.cryptography.hashalgorithm::create` doesn't work
- Skipping some robocopy based tests
- Use write-output/remove-item/copy-item instead of aliases, because they run into problems with their build in counterparts
- Some path fixes for Unix
**checkver**
**auto-pr**

[WIP] Add Unix compatibility (for maintenance jobs and manifest testing)

---

bucket/nodejs.json

As of npm@5 supports offline install it worth to persist the cache

persist npm cache

---

bucket/nvm.json

#1546 
I've tested with this update manifest. 
1. The downloaded node versions will be persisted properly. 
2. The nvm created symlink lives in apps folder and is not persisted. 
3. This symlink seems to prevent scoop uninstall to delete the nvm folder in apps. It'll always say that the folder is in use. But after manually remove the symlink, uninstall will work fine.
4. I tried to put the symlink in the persist folder, but I am not sure how to properly add that symlink to path. ```"env_add_path": "$persist_dir\\nodejs"``` doesn't seem to work.
Please advise if more change is needed.

modify the bucket manifest to allow persist

---

libexec/scoop-status.ps1
libexec/scoop-update.ps1

When there is an update to Scoop and `scoop status` is run, the output is
```
Scoop is out of date. Run 'scoop update' to get the latest changes.
Everything is ok!
```
This is not ideal, because "Everything is ok!" is what it says when it has checked for package updates and there are none - but in this case it apparently doesn't even check.
The next step if I want to do anything is `scoop update`:
```
Updating Scoop...
Scoop was updated successfully!
```
Now to find out if there are updates to the installed packages, as was the original intention, `scoop status` needs to be run a second time, but I might not think of that, because it said "Everything is ok" earlier.
This PR improves the feedback in two places:
- Don't say "Everything is ok!" when Scoop is out of date; instead warn with …

Improve feedback when Scoop is outdated and updated

---

bucket/git-lfs.json

Sorry, I didn't see they moved it from https://github.com/github/git-lfs to https://github.com/git-lfs/git-lfs.

Fix autoupdate URLs in git-lfs

---

bucket/qemu.json

The version at https://cloudbase.it/qemu-img-windows/ is 2.3.0 which was released on 2015-04-24. See http://qemu.weilnetz.de/

Add qemu at version 2.9.0

---

lib/core.ps1

Rather use (Get-PsProvider 'FileSystem').home, in case the user
~ is not pointing to $home.
This can happen if the user wants to keep $home on $Env:USERPROFILE
but is working in a different folder and want it to be ~ (for simplicity).
I'm actually in this case:
* I'm working daily in C:\nicolas
* $home is in C:\USers\nicolas (with all dot files, ssh...)
And when I'm in powershell, I like that `cd ~` change to C:\nicolas

Make scoop home agnostic

---

bucket/gcc.json
bucket/gradle.json

The gcc in main bucket is quite old, I update it. I always use latest gradle and that in main bucket is a little old.

Update gcc version from version 6.3 to 7.1, gradle from 4.0 to 4.0.1

---

bucket/artifact.json

[Artifact](https://github.com/vitiral/artifact) is a design document tool for developers. I figured it would fit the main bucket well because it's a standalone tool with a single executable. I can submit the manifest on the extras repo instead if it doesn't belong here though!

Add artifact v0.9.0.

---

bucket/glslang.json

This pull request adds the glslang shader validation tool. Glslang is the official reference compiler front end for the OpenGL ES and OpenGL shading languages. It's a standalone executable, and it is often used by editor plugins to validate shader code.

Add glslangValidator version Overload400-PrecQual.1817.

---

bucket/artifact.json

For the artifact bucket, the windows ABI builds failed on appveyor so the releases didn't get posted to github but the gnu ABI builds consistently built correctly. It makes more sense to use these builds now in the bucket since they build more reliably.

Update artifact bucket to use gnu abi and new version format.

---

bucket/git-lfs.json

That way, people using `git-with-openssh` won't end up with two versions of Git installed.

Suggest Git instead of depending on it

---

bucket/cygwin.json

This pull request addresses some issues with cygwin manifest:
* The autoupdate regex was incorrect, which caused the version to be updated to '.' instead of the latest version. 
* The installer isn't kept after installation, so a user couldn't run the installer to download packages without downloading the installer manually.
* Lynx and wget are not installed by default, so [apt-cyg](https://github.com/transcode-open/apt-cyg) installation instructions wouldn't work. This means you would have to download the installer, re-run it, then install lynx and wget before you could use apt-cyg.
I corrected the regex, added the proper latest version of cygwin to the version tag, and told the manifest to keep the installer after installation as well as install lynx and wget along with the default …

Cygwin manifest fixes

---

lib/install.ps1
schema.json

Allow custom un/installer scripts without creating/downloading *.ps1 files (could also be used to clean-up `post_install` and `pre_install` scripts)
This idea came to me because of @matthewjberger's recent pull requests (https://github.com/lukesampson/scoop-extras/pull/501, https://github.com/lukesampson/scoop-extras/pull/503), where he creates un/installers with `pre_install`.

Add script to un/installer property

---

bucket/rustup.json

This pull request updates the rustup manifest to use script blocks in the install and uninstall sections instead of creating them in the 'pre_install' section. Thanks to @r15ch13's idea [from this pull request](https://github.com/lukesampson/scoop/pull/1657).

Update rustup manifest to use new un/installer script block syntax.

---

bucket/gource.json

Adds [gource](http://gource.io/), which is a tool for visualizing a source-controlled project's history

Add gource version 0.42.

---

bucket/haskell.json

Haskell currently does not provide 32bit, the autoupdate part is
"commented out".
Original note from the haskell page
> The 8.2.1 platform release is for 64 bit Windows only, due to issues
> with GHC 8.2.1 on 32 bit Windows. Future releases are anticipated to
> resume 32 bit support.

update haskell 8.2.1 / fix autoupdate / drop 32bit

---

bucket/dotnet-sdk.json
bucket/dotnet.json

The version number in the file name I mentioned in [#1396](https://github.com/lukesampson/scoop/pull/1396#issue-216351620) isn't correct anymore, they changed it from 1.1.1 to 1.0.1 at some point. So we can't update the old manifest to 1.0.4, because that would be lower than the old version.
I'm not sure about the deprecation note, I think we should rather remove the `dotnet` manifest for now. What do you think?

Add .NET SDK

---

bucket/miniconda3.json

When creating the manifest for miniconda3 I forgot to add the installer option that allows external tools to recognize anaconda as the system's python distribution and I also forgot to add the `bin` tag to link the python executable for anaconda. 
This pull request addresses those issues.

Fix miniconda3 manifest.

---

lib/install.ps1
libexec/scoop-install.ps1
libexec/scoop-update.ps1

This adds the $use_cache parameter to the install function. Hopefully that is an acceptable change.

fix #1628 (scoop update --ignore-cache option broken)

---

bucket/rustup.json

This installs rustup directly to the persistent data directory by setting the CARGO_HOME and RUSTUP_HOME environment variables for the process before running the rustup installer.

Simplify rustup installer.

---

bin/checkver.ps1
bucket/x264-10bit.json
bucket/x264.json
lib/autoupdate.ps1
schema.json

Add a reverse property to checkver.
If set to true, the regex matches get reversed.
This helps to find new versions in directory listings. (see x264)
Like: https://download.videolan.org/pub/x264/binaries/win64/
I know there are other programs with the same problem, but I can't remember them right now :grin:
**Needs testing on Unix!**

Add reverse property to checkver

---

bucket/elixir.json

The `mix` file is a small Elixir script that is needed when running `iex -S mix`. Otherwise, `iex` tries to parse `mix.cmd` as Elixir code.

elixir.json: include mix script in bin

---

libexec/scoop-export.ps1
libexec/scoop-list.ps1

Transforms `scoop list` from:
````
netcat (1.12)
notepadplusplus (7.4.2)
openssl10x (1.0.2L)
pciutils (3.5.5)
````
to:
````
netcat (1.12)
notepadplusplus (7.4.2) [extras] {32bit}
openssl10x (1.0.2L) [versions]
pciutils (3.5.5) {32bit}
````
I originally changed it to
````
netcat (1.12)
extras/notepadplusplus (7.4.2) {32bit}
versions/openssl10x (1.0.2L)
pciutils (3.5.5) {32bit}
````
but it didn't feel alphabetical any more.

Add bucket and arch to list/export output

---

bucket/vim.json

I've made a few adjustments to the Vim installation, to make it adhere more to Vim standards, and to be less intrusive.
The current installation has a few problems:
- Even if the user has an existing Vim configuration, eg. in `$HOME\vimfiles\vimrc,` a new vimrc file will be created at `$HOME\.vimrc` during installation. The new default configuration will take precedence over the existing configuration, and if the user deletes default vimrc file, a new one will be created next time Vim is updated.
- The installation will break any existing installation of Vim, as it sets the environment variable `VIM`.
To address these issues, I have made the following changes:
- Check for an existing vimrc file in (almost) all standard locations for Vim in Windows. (`:help vimrc`)
The installation checks …

Make Vim installation more standard and less intrusive

---

bucket/jruby.json

JRuby is a ruby implementation on JVM and thus requires a jdk in order to work. Since there are different jdks available, like openjdk or oracle jdk, it isn't explitely required as an dependency but only suggested.

added jruby

---

bin/checkver.ps1

Allows for more dynamic version extractions, eg when jsonpath doesn't exactly match the version, or when you want to rearrange the regexp matches for a better version string.
I've changed so now both `jp` and `re` are allowed at the same time. `jp` is executed first, and then `re` is applied on the jsonpath. If `replace` is defined, it is applied on the regexp match.
Examples:
```
"checkver": {
"url": "https://superduper.io/versions.json",
"jp": "$..name",
"re": "(?<version>[\\d.]+)",
"replace": "2.${version}"
},
```

Add replace for regexp, allow regexp and replace for jsonpaths

---

bucket/git-with-openssh.json
bucket/git.json

This useful git browser was added to the 2.14.2 release.
See
https://github.com/git-for-windows/git/releases/tag/v2.14.2.windows.1

git: add new tig.exe to bin

---

bucket/fnproject.json

[fnproject](http://fnproject.io) is an AWS Lambda-equivalent.  This is the CLI that is used on Windows to interface with Docker to pull the server and create, deploy, and administer your fn apps.

add fnproject

---

bucket/gource.json

Fix `checkver`, now using GitHub releases. 
Update project to 64bit; as of version 0.47 Windows builds will be 64bit: 
Update to version 0.47

Update Gource to version 0.47

---

bucket/go.json

This pull request sets the GOPATH for the go manifest to a persistent directory and adds the bin folder of that GOPATH to the PATH so that downloaded libraries (obtained with `go get`) are accessible after downloading.
I found myself having to add the default GOPATH (`%USERPROFILE%\go` after go 1.8) to the path manually so that libraries for linting and code completion were visible to Spacemacs after I obtained them with `go get`.
What do you think of this?

Add persistent GOPATH to go manifest.

---

bucket/gutenberg.json

Gutenberg is a static site generator written in Rust.
Note that currently, only 64-bit binaries are provided by upstream. Also, the binaries use the MSVC ABI, which require `vcredist` to be installed on the system in order to run, if I'm not mistaken.

Add Gutenberg to bucket

---

bucket/ruby.json

Correct `autoupdate` to match current url structure
Update to version 2.4.2-2

Update ruby to version 2.4.2-2

---

bucket/leiningen.json

Update to `2.8.0`. 
_Could_ use `autoupdate` and point to [latest stable](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat) but run the risk of the checkver and this diverging resulting in hash failures. Thoughts?

Update leiningen to version 2.8.0

---

bucket/radare2.json

Update to version 2.0.1
Update checkver to use the public website. The download page is more representative of the current version than the release tags for this project.

Update radare2 to version 2.0.1

---

bucket/minio-client.json

Remove 32bit as 32bit builds are no longer provided by maintainers (see [PR](https://github.com/minio/minio/pull/4811)).
Update to version 2017-10-14T00-51-16Z

Update minio-client to version 2017-10-14T00-51-16Z

---

bucket/minio.json

Remove 32bit as 32bit builds are no longer provided by maintainers (see [PR](https://github.com/minio/minio/pull/4811)).
Update to version 2017-10-27T18-59-02Z

Update minio to version 2017-10-27T18-59-02Z

---

bucket/bfg.json

The variable $version needs to be resolved during pre_install step. It is not set at shim rumtime.

bfg: version variable is not resolved properly

---

bucket/rustup.json

A few things here:
The manifest will now check the `Cargo.toml` for the rustup github project on its master branch, which will have the same version that the exe from the url provides. The tags on the github repo were behind and did not match the executable at the url in the manifest.
The VC2015 redistributable dependency turned out to be unnecessary. To use the MSVC ABI, rustup actually requires the Visual Studio 2015/2017 Build Tools. [I'm working on a manifest to install the build tools](https://github.com/matthewjberger/scoop-extras/blob/vs2017-build-tools/vs2017-build-tools.json), but it needs more testing. Defaulting to the stable-gnu toolchain allows users to build rust programs without having to install the Visual Studio Build Tools immediately. This is always available in Rustup. …

Update rustup manifest.

---

bucket/go.json

This change makes the script create shims in the scoop shims directory instead of adding another directory to the path env variable. I believe this might be prefered instead of adding to the path variable.

create go shims instead of adding dir to path var

---

bucket/casperjs.json

Update to version 1.1.4-1
Replaced note with suggest. Phantom 1.x is no longer a requirement; 2.x can be used with 1.1.x + of casperjs.

Update casperjs to version 1.1.4-1

---

bucket/flow.json

Update license to reflect Facebook's [change from BSD to MIT](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/). 😀

Update flow license to `MIT`

---

bucket/sqlite.json

Fixes #1840 
- Update to use the actual semver (`3.21.0`)
- Fix hash

Update sqlite to use semver and fix hash

---

bucket/maven.json

I have removed the `M2_HOME` environment variable, it is not used by Maven. Maven uses the `%USERPROFILE%\.m2` directory. The `conf` directory does not have to be persisted. It contains only examples and is not used by Maven. Maven uses configuration files in the `%USERPROFILE%\.m2` directory.

Maven: remove M2_HOME variable, do not persist conf

---

bucket/vbindiff.json

This is another tool I frequently uses to compare binary files in CLI.
I checked it locally with 'scoop install vbindiff.json' and it worked fine.

Adding VBinDiff.

---

bucket/yarn.json

**Notes:**
- Drop `bin` from the prefix location. Yarn add's bin automatically for the bin folder. Currently this results in a bin\bin folder. From docs:
> For example, yarn config set prefix `~/.yarn` will ensure all global packages will have their executables installed to `~/.yarn/bin`.
- Update both configs calls to be relative to `dir` and not `persist_dir`. Yarn generates command shims for global modules that will be relative to the prefix directory. Separately, the current/* folders were being added to the user's path. This means that the command shims were being built relative to the persist dir, but they were being invoked from the current dir. The paths were different and this prevents the global apps from working. Both are now relative to the current dir. This should be …

Update yarn config locations to fix global

---

appveyor.yml
test/Scoop-Alias.Tests.ps1
test/Scoop-Core.Tests.ps1

Merge when pester version 4.0.8 gets approved on [chocolatey](https://chocolatey.org/packages/pester) and tests on appveyor start failing.

Update tests to work with pester version 4.0.8

---

bucket/graphviz.json

- Fix download url 
- Update checkver
- Update autoupdate

Update graphviz 2.38 url

---

bucket/gradle.json

This commit removes the `%GRADLE_HOME%` environment variable. It is not used by Gradle. See this [discussion](https://discuss.gradle.org/t/do-we-really-need-gradle-home-docs-site-inconsistency/21671).

Gradle: remove GRADLE_HOME from manifest

---

buckets.json

I decided to create a public [bucket](https://github.com/oltolm/scoop-nonportable) for normal nonportable apps. Please add it to the list of buckets. I have described some of the advantages of nonportable apps in the [README](https://github.com/oltolm/scoop-nonportable).

add nonportable bucket

---

bucket/mysql.json

* Since [MySQL 5.7.18](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-18.html#mysqld-5-7-18-packaging), my-default file is no longer distributed in package so we can't the line to produce my.ini by copying my-default file.
* In Powershell, Out-file seems to make Byte Order Mark automatically and this occurs following error so this is a temporary commit which changes UTF-8 to ASCII doesn't make BOM.
> mysql: [ERROR] Found option without preceding group in config file …\scoop\apps\mysql\current\my.ini at line 1!
> mysql: [ERROR] Fatal error in defaults handling. Program aborted!

Edit post installation script of MySQL bucket

---

lib/install.ps1
test/Scoop-Install.Tests.ps1

Use `Get-FileHash` instead of `System.Security.Cryptography.HashAlgorithm` if available
This satisfies these two cases:
* PowerShell 3 doesn't support `Get-FileHash`
* PowerShell 6 doesn't support `HashAlgorithm` yet
Related stuff:
* https://github.com/lukesampson/scoop/issues/1722
* https://github.com/PowerShell/PowerShell/issues/4577
* [Get-FileHash](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash?view=powershell-6)

Use Get-FileHash instead of System.Security.Cryptography.HashAlgorithm

---

bucket/mariadb.json

This commit adds a post installation script to initialize data directory by using `initialize-insecure` option like the case of MySQL and shows the command creates service. Unlike MySQL, I don't put lines make `my.ini` file.

Add post installation script for MariaDB

---

bucket/vim.json

Add a new `vi` alias to `vim` so that the following command does not error (as discussed on Gitter 2017/03/22)
```diff
PS scoop> vi /path/to/file
- vi : The term 'vi' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
- At line:1 char:1
-  vi
- ~~
-    + CategoryInfo          : ObjectNotFound: (vi:String) [], CommandNotFoundException
-    + FullyQualifiedErrorId : CommandNotFoundException
```

Update vim aliases

---

bucket/kubectl.json

See [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#multicluster).

kubectl: kubefed will no longer be released as part of Kubernetes

---

libexec/scoop-virustotal.ps1

Before installing packages, I like to check they are clean...  Luckily, the hash of the package can be used to retrieve the status on https://virustotal.com and more often than not, they have been analyzed already.
I don't know what to test for this (I looked at scoop-home.ps1 for inspiration, but it doesn't seem there are any tests either).
Best regards,
Philippe Crama

Initial implementation of command to query virustotal.com

---

bucket/neko.json

We have just updated the archive since the previous one didn't include "neko.lib".
Use https for checkver as well.

update neko 2.2.0 hash

---

bucket/cygwin.json

Removed checkver and autoupdate as these don't work. The version number isn't even in the metadata for setup.exe, so we'll use the date of the file for the version.

Update cygwin to 2.883

---

lib/core.ps1
libexec/scoop-virustotal.ps1

Add * option to check all installed apps
Add --global option to check globally installed apps
Add 60+ sec. pause after 4 queries/min to avoid 429/Too Many Requests
Add immediate abort if query limit is exceeded
Add INFO/WARN/ERROR prefixes to messages
Add DarkGray/DarkCyan/DarkRed colors to INFO/WARN/ERROR messages
Add using apikey if stored via: scoop config virustotal_api_key apikey
Change colors to DarkGreen/DarkYellow/Yellow/Red for 0/1/2/3+ hit count
Remove fragment from URL when submitting to virustotal.com
Standardized INFO/WARN/ERROR messages

Update virustotal command

---

bucket/wkhtmltopdf.json

Using Mingw version, as MSVC version requires installation with admin privileges.

Using Mingw version for wkhtmltopdf

---

lib/shortcuts.ps1

To support https://github.com/lukesampson/scoop-extras/pull/734

Add subdirectories/arguments for shortcuts

---

bucket/cloc.json

The old 64-bit installer is no longer available. 
There is _typically_ only one version released for cloc, not architecture-dependent versions. Details: https://github.com/AlDanial/cloc#building-a-windows-executable-
Removes architecture dependency from the manifest and uses the live URL.

Fix cloc download link

---

bucket/yasm.json

This adds the Yasm modular assembler to the default Scoop bucket.

Add Yasm package

---

bucket/win32-openssh.json

Still flagged in the release notes as `This is a pre-release (non-production ready)` so I've left the notes.

Update win32-openssh to version 1.0.0.0

---

bucket/yasm.json

Patches the checkver included with #1964.
- Change `https` to `http`
- Fix `re` to grab version

Fix yasm checkver

---

bucket/neovim.json

Use path instead of bin to add neovim copy-paste (win32yank) in windows.

Enable win32yank on neovim

---

libexec/scoop-cache.ps1

I think this was just overlooked? `scoop-cache.ps1` doesn't use the `$cachedir` variable, so it doesn't get the SCOOP_CACHE support added in #1364.
The result being that while the install command correctly uses the folder in SCOOP_CACHE, all *scoop cache ...* commands error because they can't find a `...scoop\cache` folder.

Fix: 'scoop cache' command not using SCOOP_CACHE

---

lib/config.ps1

Fixes writing the config to the `~/.scoop` file if that file is hidden. (#1978)
`Out-File` can't write to existing hidden files, even with the `-Force` switch. Using `Set-Content` instead seems to work fine (it doesn't even need the -Force)

Enable writing to hidden .scoop file (#1978)

---

bucket/wixtoolset.json

Checked previous versions, too. File name doesn't include $patchVersion. Update should match versions going forward.

Update wixtoolset to version 3.11.1

---

lib/install.ps1

When directories are being persisted and do not exist already in the source, a couple unnecessary lines are output at the end. Piping this to `out-null` makes it look much better.

Prevent directory creation from being output to console in persistence

---

bucket/lynx.json

Still shows:
````
SSL error:Can't find common name in certificate-Continue? (n)
````
but at least it works with https

Update lynx to 2.8.9dev.16 (supports SSL)

---

bucket/git-with-openssh.json

Patch: https://github.com/git-for-windows/git/commit/60d8d6eae36358696027f95f0dc1a2dffc3b066b

Update git-with-openssh to version 2.16.1.windows.3

---

bucket/latex.json

- Update to version 2.9.6615
- Extract SHA-256 from website; 190 mb download to compute hash!

Update latex to version 2.9.6615

---

lib/core.ps1
lib/install.ps1

Create sh shim

---

bucket/doxygen.json

```
wget https://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.windows.x64.bin.zip
wget https://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.windows.bin.zip
shasum -a 256 doxygen-1.8.14.windows.x64.bin.zip doxygen-1.8.14.windows.bin.zip
e2d635a05fb0516311071cfcc41a3859fa22a912b484ed2c2ddec70248b75845 *doxygen-1.8.14.windows.x64.bin.zip
c08900ffda8ed911746c86ad3354ad86084715cfd39ceca938f7bc2ead7988fc *doxygen-1.8.14.windows.bin.zip
```

Fixed doxygen hashes

---

bucket/colortool.json

https://github.com/Microsoft/Console/tree/master/tools/ColorTool
[Introducing the Windows Console Colortool – Windows Command Line Tools For Developers](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/)

Add ColorTool (Windows Console Colortool)

---

bucket/dotnet-sdk.json

Using `dotnet.exe` through a shim breaks debugging in VS Code.

Add .NET SDK directory to PATH

---

lib/core.ps1

Deal with https://github.com/blog/2507-weak-cryptographic-standards-removed by enabling TLS 1.2 in addition to existing encryption schemes.
Fixes #2040

Enable TLS 1.2 in core.ps1

---

lib/decompress.ps1

7-zip can also extract .bz2 files. This just adds it to the list of known filenames for auto-extraction.

Add .bz2 files to decompression

---

lib/core.ps1

- Fixes #2083 
- Tested on Windows 8.1 and Windows 10
- Also fixes indentation + clarifying comment

Fix "enable-encryptionscheme" for OSes before Windows 10

---

bucket/llvm.json

The installer and uninstaller do not appear to have `/noadmin` options. converting to a 7z and adding bin appears to work. I'm not sure what the installer was attempting to do, so I believe this is an acceptable change.

Converted llvm download to 7z to avoid elevated permissions request

---

bucket/git-annex.json

https://git-annex.branchable.com/publicrepos/ implies there is no public git, so the only way I can see to get the `6.20180219-ge162efdbd` version is running the exe.

Add git-annex at 2018-02-27 (6.20180219-ge162efdbd)

---

bucket/llvm.json

The llvm download rename wasn't quite correct. This fixes it, and has been tested. 
Is there a post-install test that should be run to confirm this works?

Fix llvm download rename to 7z

---

lib/install.ps1

In this patch I make an exclusion for SourceForge. Because of some reason it doesn't like filled `Referer` and blocks GET request.

Added exclusion for sourceforge.

---

bucket/dos2unix.json

There is also an Internationalized version listed [here](https://waterlan.home.xs4all.nl/dos2unix.html), but I assume that's not necessary for scoop's audience at the moment.

Add dos2unix

---

bin/auto-pr.ps1
bin/checkver.ps1
lib/psmodules.ps1
libexec/scoop-depends.ps1
libexec/scoop-install.ps1
libexec/scoop-reset.ps1
libexec/scoop-virustotal.ps1

Cleans up code that outputs error messages:
- Removes the extra 'ERROR' text in the case of `error 'ERROR...`
- Uses the `error` function instead in some cases of `write-host '...' -f Red/DarkRed`...
- ...Except when an `exit` comes after it, in which case it's changed to use `abort` (in some cases this changes the text from darkred to red). The `abort` method doesn't prepend any text.
Haven't touched these cases:
- Code that (effectively) uses write-output instead of write-host to output error messages.
- Code that uses `[console]::error.writeline` instead, since I don't know exactly what this does/why it was used
- Lots of code uses `write-host -f DarkRed "..."`, but I haven't changed them all to use the error function because I don't know if preceding every error message with "ERROR " …

Clean up some error messages

---

libexec/scoop-uninstall.ps1

Sometimes uninstaller removes its own directory by itself. In these cases scoop fails uninstallation process with the following error:
```
PS C:\Users\Chebotarev_V\scoop\apps\scoop\current> scoop uninstall flux
Uninstalling 'flux' (4.66).
Running uninstaller... done.
Removing shim for 'flux'.
Unlinking ~\scoop\apps\flux\current
ERROR Couldn't remove '~\scoop\apps\flux\4.66'; it may be in use.
```
Example:
```
scoop bucket add user https://github.com/excitoon/scoop-user.git
scoop install user/flux
```
This patch fixes it.

Checked if uninstaller removed its directory.

---

lib/core.ps1

Trend AV analyses and lock zip files just after download. I have added 2 retries in case of this event.
At work I can't change antivirus settings so I have no other choice than to modify the unzip function.

Added retry when unzip fail because of AV

---

.gitignore
.vscode/settings.json
PSScriptAnalyzerSettings.psd1
appveyor.yml
bin/checkurls.ps1
bin/install.ps1
lib/autoupdate.ps1
lib/config.ps1
lib/core.ps1
lib/description.ps1
lib/install.ps1
lib/manifest.ps1
lib/versions.ps1
libexec/scoop-cleanup.ps1
libexec/scoop-virustotal.ps1
libexec/scoop-which.ps1
test/00-Project.Tests.ps1
test/Scoop-Linting.Tests.ps1
test/Scoop-Manifest.Tests.ps1
test/Scoop-TestLib.ps1

What does this big pull-request do: we use **[PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer)** for code linting.
1. Improve all current `*.ps1` files to pass PSScriptAnalyzer check. **notes:** some rules have been excluded for special reason, you can take a look at `PSScriptAnalyzerSettings.psd1`.
2. Add PSScriptAnalyzer integration for vscode.
3. Improve tests to ignore Pester generated `TestResults.xml`.
4. Add PSScriptAnalyzer checking into tests, CI included.
There are some opinionated changes, so this pull-request is pending and looking for reviews.

[Pending] Finally we add the code linting and its tests!

---

bucket/vim.json

A standard vim installation on *nix comes with extra commands for
starting vim in various modes.
The following aliases (from the vim man page) are added:
- ex
- view
- rvim
- rview
- vimdiff
- gview
- evim
- eview
- rgvim
- rgview
- gvimdiff

Add aliases for standard vim commands

---

libexec/scoop-alias.ps1

See: https://github.com/lukesampson/scoop/issues/2160
Example output:
```
λ scoop alias list
i       scoop install
test    composer install
u       scoop uninstall
upgrade scoop update *
```
```
λ scoop alias list -v
Name    Command          Summary
----    -------          -------
i       scoop install
test    composer install Run composer install in current directory
u       scoop uninstall
upgrade scoop update *   Updates all apps like brew or apt
```

Improve "scoop alias list" output (#2160)

---

test/00-Project.Tests.ps1
test/Scoop-Install.Tests.ps1

Fix some test on Linux. 
* Currently `Get-Content` on Linux doesn't support `-Encoding` , thus cannot read file as `Byte`. It is still possible to read the test using .NET functionality. 
* Adjust path to use `join-path` in another file

Fix some tests on linux

---

lib/install.ps1

Sometimes [console]::isoutputredirected becomes False when in ISE, so we
need an extra check to prevent the fancy progress bar trying to display
here.

Disable fancy progress when in ISE (fixes #2171)

---

bucket/minishift.json

The `extract_dir` was set to the old version (`1.14.`), so I just switched it to be `1.15.1` to match.

fix minishift version mismatch

---

lib/core.ps1

There exist two size properties in `$host.ui.rawui`: `windowsize` and `buffersize`. PowerShell ISE doesn't support windowsize, causing `wraptext` to incorrectly wrap in ISE. (#2190).
In the modern Windows 10 console (and eg the terminal in vscode), the widths of buffersize and windowsize are always the same.
This change only affects those using pre-Windows 10 conhost, or the Windows 10 conhost in legacy mode; and furthermore only if they have the console window sized narrower than the buffer size (giving a horizontal scroll bar). In this situation, all text in the console is suboptimally displayed anyway.
The code was first added in https://github.com/lukesampson/scoop/commit/a21a2d2f1f7445a85137cd222a6e6349441111b4, 5 years ago

wraptext: use buffer width instead of window width (fixes #2190)

---

bucket/neovim.json

This commit relates to #1985, reverts 3fc87da006e21dad39c13522427a35368ce402e2, and resolves #2021.
Neovim doesn't require win32yank.exe in the user's PATH. The shimexe version of win32yank.exe causes problems with clipboard+=unnamedplus in Neovim. Since it's not required in the PATH, and the shimexe version cause issues, this removes win32yank's shim.
Say the neovim clipboard option is set to set clipboard+=unnamedplus. If the win32yank.exe shim genereated by Scoop exists in the user's PATH, then it will be used. The shimexe [0] version of win32yank leaves dangling window instances, in the foreground, after every yank or paste operation. This indicates an incompatibility between Neovim and the win32yank.exe shimexe.
Neovim does not require win32yank.exe in the user's PATH. This is …

neovim: Do not include win32yank in PATH

---

bucket/msmpi.json

This adds to the path with `env_add_path`, because the `msmpi.dll` is
required to be in the path for MPI programs to properly work.
This replaces lukesampson/scoop-extras#895

Added MSMPI runtime environment

---

bucket/git-annex.json

Fix error message ``Hash check failed ...``. Update file hash to match https://downloads.kitenet.net/git-annex/windows/current/git-annex-installer.exe.info

Fix homepage url and file hash

---

README.md

Gratipay doesn't exist anymore, see:
- https://gratipay.com/
- https://gratipay.news/the-end-cbfba8f50981
Consider an alternative, like:
- https://en.liberapay.com/
- https://www.patreon.com/
- https://opencollective.com/

Remove Gratipay from donation options

---

libexec/scoop-uninstall.ps1

If one uninstalls more than one application and have an error, she will receive pretty random behaviour - scoop will either stops (skipping other applications) or continue to uninstall the current. This is so because `continue` doesn't works with pipes and some `continue` were supposed to exit current iteration of nested loop. When one calls `continue` from `For-Each`, PowerShell simply exits `For-Each` (the same effect as if it was `break`:
```
PS C:\Users\Chebotarev_V\scoop\apps\scoop\current> @(1,2,3,4) | % { echo $_; continue }
1
PS C:\Users\Chebotarev_V\scoop\apps\scoop\current> foreach($_ in @(1,2,3,4)) { echo $_; continue; }
1
2
3
4
```

Better error handling during uninstallation.

---

lib/core.ps1

See #2025.
This is a fix for what was addressed by @stkb.

Fixed passing arguments to ps1 shims.

---

lib/core.ps1
lib/install.ps1

Hi.
Now one can make shims for external applications (system, other applications installed by scoop and so on).
First, `$bin` is to be searched in `$dir`, then globally, then in user and system `PATH`.
Examples:
```
"bin": [ [ "winver.exe", "myver", "" ] ]
```
```
"depends": [ "python" ],
"bin": [
[ "python.exe", "myscript", "$dir/myscript.py" ],
[ "python.exe", "myscript.py", "$dir/myscript.py" ]
]
```
```
"depends": [ "bash" ],
"bin": [
[ "bash.exe", "myscript", "$dir/myscript.sh" ],
[ "bash.exe", "myscript.sh", "$dir/myscript.sh" ]
]
```

Enabled shimming of external applications

---

bucket/minishift.json

It seems that this field keeps getting missed when people are bumping versions, causing the install to fail.  I'm fixing it, but it would be nice if there were more places where you could put in `$version`, but it doesn't seem to be something you can just put anywhere you want, though.

minishift - fix version extract dir (again)

---

bucket/bazel.json
bucket/zip.json

See #2186.
Zip is taken from http://www.paehl.com and repackaged to zip (sic!) in order to avoid `7z` dependency.

Fixed Bazel dependencies and added environment variable.

---

lib/core.ps1

Warn on shim overwrite

---

libexec/scoop-info.ps1

Inspired by `brew info`.
Some tests case that (might) should be handled:
- `scoop info vim`, vim no installed.
- `scoop info vim`, vim installed from main bucket.
- `scoop info vim`, vim installed from `other` bucket.
- `scoop info vim`, vim installed from [url](https://raw.githubusercontent.com/lukesampson/scoop/master/bucket/vim.json).
- `scoop info <$bucket>/vim`, vim no installed.
- `scoop info <$bucket>/vim`, vim installed from main bucket.
- `scoop info <$bucket>/vim`, vim installed from `other` bucket.
- `scoop info <$bucket>/vim`, vim installed from [url](https://raw.githubusercontent.com/lukesampson/scoop/master/bucket/vim.json).
- `scoop info <$bucket>/vim`, vim installed from `<$bucket>` bucket.
more information to be supplemented.

[WIP&RFC] Add scoop info sub-command

---

lib/core.ps1
lib/depends.ps1
lib/install.ps1
lib/manifest.ps1
libexec/scoop-install.ps1
libexec/scoop-reset.ps1
test/Scoop-Core.Tests.ps1

This should fix some issues with the installation from different buckets and also allows specific versions.
It now parses these app names:
- php-bucket/php71-amqp@1.8.0
- php-bucket/php71-amqp
- php71-amqp@1.8.0
- php71-amqp@1.9.0-rc2
Removed:
- is_app_with_specific_version()
- get_app_with_version()
Heavy testing required!

Refactor app() to parse_app() for better "bucket/app@version" handling

---

bucket/vim.json

Currently it fails trying to copy directory vim80. It is now called vim81, because of version 8.1.xxx.

Fix #2264 install vim

---

bucket/postgresql.json

PostgreSQL has a problem to sort some non-latin characters using `ORDER BY` and the known solution is setting `LC_COLLATE` to C.[1][2] Because `LC_COLLATE` is fixed when running `initdb`, it is preclusive to set collation on post installation script for new user.
[1]: https://stackoverflow.com/questions/14191848/postgresql-order-by-is-very-weird
[2]: https://stackoverflow.com/questions/43745639/sort-order-in-postgresql-for-japanese-words-in-hiragana

Adding C collate on initdb

---

bucket/dotnet-sdk.json

With the release of .NET Core 2.1 the text on the download website changed slightly and broke the version check regex.
This updates the regular expression for the new text and updates dotnet-sdk to the latest version.
As far as I can see autoupdate works as expected with these changes. This was the output of `checkver.ps1`:
```
PS> .\bin\checkver.ps1 dotnet-sdk -u
dotnet-sdk: 2.1.300 (scoop version is 2.1.200) autoupdate available
Autoupdating dotnet-sdk
Searching hash for dotnet-sdk-2.1.300-win-x86.zip in https://dotnetcli.blob.core.windows.net/dotnet/checksums/2.1-sdk-sha.txt
Found: sha512:be5da1f6a7aa983d25feed7f1fcddb67d88ce98bacd6ff4b8116737b30e2132a004a93887a7f773818c81abf0ff8e3fc071956a3d08032a65300f1088707bf6a using Extract Mode
Searching hash for dotnet-sdk-2.1.300-win-x64.zip in …
```

dotnet-sdk: Fix autoupdate (and update to version 2.1.300)

---

bucket/postgresql.json

The current post_install script fails and doesn't create a database cluster because the locale "c" is unknown.

Fix lc-collate for postgresql

---

bucket/winpython.json

As discussed in https://github.com/lukesampson/scoop-extras/pull/978, moving this manifest to main bucket. Also, added a short description.

moving winpython from extras to main bucket

---

bucket/winpython.json

Fixed autoupdate hash regex (backslashes before `|` were missing)

winpython - fixed hash autoupdate regex

---

bucket/scons.json

As SCons cannot be cleanly installed using `pip install` (especially on Python 3), this is a more reliable installation method that is just as easy to use as pip.

Add SCons version 3.0.1

---

bucket/jfrog.json

jFrog makes Artifactory, Bintray, and a few other products in the Binary Repository management space. This cli tool is a go executable that interacts with their products.

add jfrog-cli-go to bucket

---

lib/buckets.ps1
lib/core.ps1
lib/install.ps1
libexec/scoop-info.ps1
libexec/scoop-install.ps1
libexec/scoop-update.ps1

- Add `show_app()` function for displaying `app/bucket@version`
- Add option (`-s` | `--skip`) to skip hash validation on `scoop install` and `scoop update` to allow installation when a manifest provides an outdated hash
- Add `new_issue_msg()` function for nicer error messages with a link to the buckets repository. clicking on the link opens a new issue with a predefined title
- Show filename instead of unreadable `robocopy` output when file moving fails and use `new_issue_msg()`
- Handle hash validation errors with `new_issue_msg()`
Hm, maybe I put too much in this pull-request ... one change leads to another. 🤷‍♂️ 😁 
Example output: 
```
λ .\bin\scoop.ps1 install wox
Installing 'wox' (1.3.524) [64bit]
Wox-1.3.524-full.nupkg (5,0 MB) [===========================] 100%
Checking hash of …
```

Option to skip hash validation and error message improvements

---

lib/core.ps1

**Problem**: Scoop uses a hardcoded `powershell -ex unrestricted` call to launch itself. As the WSL needs native end with `.exe`, the script fails.
**Fix**
Just added the `.exe`-extension to the script, as this has no impact on the windows side but enables the usage of scoop inside of the WSL

Add basic WSL support by appending .exe to powershell

---

bucket/imagemagick.json

Imagemagick doesn't need to be added to PATH because all its .exe files are already shimmed.

Change imagemagick to not add its directory to PATH. Fix #2275

---

bucket/mongodb.json

looks like mongoperf is no longer installed by default

removed mongoperf shim

---

bucket/git-annex.json

Fix for:
```
ERROR Hash check failed!
App:       git-annex
URL:       https://downloads.kitenet.net/git-annex/windows/current/git-annex-installer.exe#/dl.7z
Expected:  29bbc450559f1ed901f190d9d44b721fc86f47ab0d13319055b4de6979b3a59c
Actual:    b639796d2c9974bbd35dbfbd9869de2afd5561a7598cd6b745fe8c798d137c52
Please create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=git-annex%406.20180626%3a+hash+check+failed
```

git-annex: Update hash of version 6.20180626

---

bucket/perl.json

This PR fixes issue #2349.
Use `[System.IO.File]::WriteAllBytes()` instead of `Set-Content -Encoding Byte` to fix compatibility issue with PowerShell 6 which has removed `-Encoding Byte` in favor of a new `-AsByteStream` switch.

Perl: Fix install when using PowerShell 6 (fixes #2349)

---

bucket/hub.json

https://github.com/github/hub/releases/tag/v2.5.0

Update hub to 2.5.0

---

lib/install.ps1

Portableapps.com has switched to portableapps.duckduckgo.com as their freeware host and skipping strip_filename is no longer required.
Remove downloads subdomain from sourceforge.net to also support mirror redirect urls (e.g. https://sourceforge.net/projects/portableapps/files/GIMP%20Portable/GIMPPortable_2.10.2.paf.exe/download).

Update strip_filename skips

---

bucket/watchexec.json

This adds [watchexec](https://github.com/mattgreen/watchexec), a tool for executing commands in response to file modifications.

Add watchexec version 1.8.6

---

libexec/scoop-info.ps1

before:
```
Manifest:
C:\Users\<omitted>\scoop\apps\scoop\current\lib\..\bucket\go.json
```
after: 
```
Manifest:
C:\Users\<omitted>\scoop\apps\scoop\current\bucket\go.json
```

scoop-info: Make manifest file path looks better

---

lib/core.ps1

In the app manifest, specifying dependencies with the bucket on which to find that dependency is supported (see the [flutter](https://github.com/lukesampson/scoop-extras/blob/master/flutter.json) manifest for an example). The problem, however, is that when running `scoop status` after installing an app such as flutter, we get an error message that some dependencies are supposedly missing:
This message is however wrong, since oraclejdk8 was successfully installed. The problem is that flutter checks if a dependency is installed by checking whether a directory with the name of that dependency exists in the apps folder. In this case it checks for the folder `java/oraclejdk8`, doesn't find it, since it actually exists as `oraclejdk8` and marks the dependency as being not satisfied.
This small …

Removed the bucket from the app name when checking directories.

---

bucket/resharper-clt.json

Jetbrains [added](https://blog.jetbrains.com/dotnet/2018/03/01/code-cleanup-resharper-command-line-tools/) a code cleanup binary `cleanupcode.exe` to their command line tools. This PR adds this binary to the list of scoop binaries.

Expose resharper cleanupcode binary

---

bucket/haskell.json

The hash can be verified by comparing it with the hash listed on
https://www.haskell.org/platform/windows.html.

haskell: Fix hash (closes #2422)

---

bucket/win32-openssh.json

```
Installing 'win32-openssh' (7.7.2.0p1-Beta) [64bit]
Loading OpenSSH-Win64.zip from cache
Checking hash of OpenSSH-Win64.zip... ERROR Hash check failed!
App:         win32-openssh
URL:         https://github.com/PowerShell/Win32-OpenSSH/releases/download/v7.7.2.0p1-Beta/OpenSSH-Win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    87e0cd468fe36a74bea0e40cee3021f99b38e431b7c8668af4461fdab03031b7
Actual:      8631f00013116388362cb06f3e6fd2c44c8e57d8f857033111f98feb34fa5bce
Please create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=win32-openssh%407.7.2.0p1-Beta%3a+hash+check+failed
```

Fix win32-openssh file hash

---

bucket/vim.json

`xxd` (a hexdump tool) is a tool bundled with `vim`. Unlike other tools bundled with vim (e.g. `diff`). It is a first party vim tool. So even if we were to setup `xxd` as a separate package, we would have to download vim. 
Ref: https://packages.ubuntu.com/source/bionic/vim

expose xxd.exe from vim

---

README.md
lib/config.ps1
lib/core.ps1
lib/install.ps1
libexec/scoop-cache.ps1
libexec/scoop-install.ps1
libexec/scoop-update.ps1
test/Scoop-Config.Tests.ps1

This change adds support for multi-connection downloads via aria2c. (requested in https://github.com/lukesampson/scoop/issues/2306)
Scoop will use aria2 by default if it's installed locally or globally to speed all downloads.
The output changes from the previous progress bar to simply writing the aria2 output.
[still image](https://user-images.githubusercontent.com/432127/41479688-45b3abac-70cc-11e8-8ddb-a26b4995e0a7.png)
Use the following command for constant tests:
`.\bin\scoop.ps1 uninstall godot; .\bin\scoop.ps1 cache rm godot; .\bin\scoop.ps1 install godot`

Add support for multi-connection downloads via aria2c

---

bucket/aria2.json

Build no was hard coded in url and extract_dir. Sometimes aria2 is released with build no >1, for example [1.23.0](https://github.com/aria2/aria2/releases/tag/release-1.23.0).

aria2: Include build no in autoupdate

---

lib/core.ps1

Currently `scoop install exercism-cli` (with the extras bucket added) will fail, because the downloaded .zip file contains files that would be extracted outside of the target directory:
- ../shell/README.md
- ../shell/exercism_completion.bash 
- ../shell/exercism_completion.zsh
This PR adds 7zip fallback functionality when the System.IO.IOException occurs, almost exactly like the handling for System.IO.PathTooLongException. 7zip will safely handle those files by moving them into the target directory.

catch unzip failures from bad file names

---

bin/install.ps1

For AppVeyor CI the `$errorActionPreference` setting is persisting after I install scoop, subsequently causing issues with installing scoop apps (e.g. failing the whole build because an installer executable outputs what looks like an error).

Reset $errorActionPreference to original value

---

bucket/guetzli.json

> [Guetzli](https://github.com/google/guetzli) is a JPEG encoder that aims for excellent compression density at high visual quality. Guetzli-generated images are typically 20-30% smaller than images of equivalent quality generated by libjpeg. Guetzli generates only sequential (nonprogressive) JPEGs due to faster decompression speeds they offer.

Add Guetzli version 1.0.1

---

bucket/graphicsmagick-q16.json
bucket/graphicsmagick-q8.json

GraphicsMagick installers are InnoSetup packages. Use scoop's innosetup extractor to install it, so we don't need to ask for administrative permission. 
Ref: http://hg.code.sf.net/p/graphicsmagick/code/file/5262d45f6dc6/VisualMagick/installer/README.txt

Use innosetup for GraphicsMagick

---

bucket/gcc.json

This also makes them easier to read by splitting them over two lines.

gcc: Improve writing style in post-installation notes

---

bucket/scons.json

Installing `scons` resulted in an error as `$dir` wasn't being expanded (due to the use of single quotes instead of double quotes). PowerShell provides a way to escape nested double quotes (while still being embeddable in JSON), so let's use it :slightly_smiling_face:
This fixes a regression from https://github.com/lukesampson/scoop/commit/5c1e9ba0c54e434f26491f1e33c2381601c38534.

scons: Fix pre_install step by using escaped double quotes

---

bucket/traefik.json

This pull-request adds an app manifest for traefik (https://github.com/containous/traefik).
- Releases from Github.
- Separate binaries for each environment.

Add traefik 

---

lib/install.ps1

In PowerShell Core (6.0+) '-Encoding byte' is replaced by '-AsByteStream', fixed and tested on my Windows 10 Home with PowerShell Core 6.04 stable.
This is my first attempt to contribute back into your amazing project that I highly appreciate, so if something is missing like obligatory tests, waiver, issues etc - feel free to pinpoint and I will try to conform!

Fix PowerShell core crash

---

bucket/bat.json

bat is a replacement for cat
it has:
- support for multiple files
- syntax highlighting
- line numbering by default.
It is written by the same person that maintains fd(which is in scoop). 
atm bat does not have a 32-bit binary.

Add bat.exe to scoop

---

lib/core.ps1

PowerShell on Windows comes with both 2.0 and 3.0+ installed. This is a feature inherited from .NET --  PowerShell 2.0 is based on .NET 2.0 which is installed side-by-side with .NET 3.0-4.7. It is possible to run PowerShell 2.0 by invoking the command `powershell.exe -Version 2.0 -NoProfile`. 
This is fairly useful feature for PowerShell scripters, as one can use PowerShell 2.0 to check for the basic compatibility of scripts without having to run a VM. As such, a user can have scoop apps installed via PowerShell 3.0+, and then launch PowerShell 2.0 for casual testing. 
Currently the scoop shims are broken in PowerShell 2.0, as they use `$PSScriptRoot`. In addition, since PowerShell picks up `{command}.ps1` before `{command}.exe` when looking for `{command}`, this makes using …

make shim support PS 2.0

---

bucket/exercism.json

This pull-request adds an app manifest for [exercism](https://github.com/exercism/cli).
- Releases from Github;
- Separate binaries for each environment.

Add exercism

---

bucket/oxipng.json

This adds [oxipng](https://github.com/shssoichiro/oxipng), a multi-threaded lossless PNG optimizer written in Rust.

Add oxipng version 2.1.2

---

bucket/mingit-busybox.json

add mingit-busybox, another official Windows packaging of git - instead of using MSYS it uses busybox for POSIX shell. 
https://github.com/git-for-windows/git/wiki/MinGit#experimental-busybox-based-mingit

add mingit-busybox, another packaging git-for-windows

---

bucket/qrencode.json

Windows port of `qrencode` command. Unfortunately the guy who ported it hasn't update it for sometime. 
The compiled .exe files are rough-around-the-edges to use, it has encoding issues with Windows Console (ANSI color and UTF8). I wrote a small shim that works around ANSI color.  
Maybe when we get to the point of having our own build stack like Homebrew, we will build it from source.

add qrencode

---

bucket/uncrustify.json

resolves #2521
Latest release lacks 32-bit binary, pulling 32-bit from an older release

Add uncrustify

---

bucket/hugo.json

hugo has changed its repo to another account. 
Fix the path issues when installing.

 Update new repo url of hugo

---

appveyor.yml
test/Scoop-Alias.Tests.ps1
test/Scoop-Config.Tests.ps1
test/Scoop-Core.Tests.ps1
test/Scoop-GetOpts.Tests.ps1
test/Scoop-Install.Tests.ps1
test/Scoop-Linting.Tests.ps1
test/Scoop-Manifest.Tests.ps1
test/Scoop-Versions.Tests.ps1
test/bin/init.ps1
test/bin/test.ps1

Replaces #2572
- Adds `!linter` commit flag to skip PSScriptAnalyzer
- Adds `!manifests` commit flag to skip manifest validation
- Skips manifest validation if no JSON has changed
- Skips tests and linting if no PowerShell script has changed
- Validates only manifests that changed
- Validates all manifests if `schema.json` changed

appveyor: Run tests for PowerShell 5 and 6

---

bucket/git-town.json

As it works will with git installed by native installer.

make git-town does not depends on git

---

bucket/innoextract.json

Alternative to `innounp`. 
Might be useful down the road, as innoextract is cross-platform, while innounp appears to be only available for Windows.

innoextract

---

bucket/cmder-full.json
bucket/cmder.json

- Closes #2628 
Runing something like `Remove-Item \"$dir\\vendor\\git-for-windows\" -Force -Recurse` would save some space.

cmder: Add hash extraction

---

bucket/cloak.json

Added cloak, which is a Command Line OTP (One Time Password) Authenticator application written in Rust that generates time-based and counter-based OTP codes.

Add cloak.

---

bucket/buffalo.json

```
$ scoop install buffalo
Installing 'buffalo' (0.12.7) [64bit]
Loading buffalo_0.12.7_windows_amd64.tar.gz from cache
Checking hash of buffalo_0.12.7_windows_amd64.tar.gz ... ok.
Extracting buffalo_0.12.7_windows_amd64.tar.gz ... done.
Linking ~\scoop\apps\buffalo\current => ~\scoop\apps\buffalo\0.12.7
Creating shim for 'buffalo'.
Can't shim 'buffalo-no-sqlite.exe': File doesn't exist.
```
```
$ 7z.exe l buffalo_0.12.7_windows_amd64.tar
7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 15499776 bytes (15 MiB)
Listing archive: buffalo_0.12.7_windows_amd64.tar
--
Path = buffalo_0.12.7_windows_amd64.tar
Type = tar
Physical Size = 15499776
Headers Size = 2560
Code Page = UTF-8
Date      Time    Attr         Size   Compressed  Name …
```

Fixed issue with buffalo binary name in archive

---

bucket/sass.json

```powershell
$ dart-sass
"WARNING: The dart-sass executable is deprecated, use sass instead."
Compile Sass to CSS.
```
And uniform the app name
```sh
npm install -g sass
choco install sass
```

sass: rename dart-sass to sass

---

bucket/buffalo.json

```
$ scoop update buffalo
buffalo: 0.12.7 -> 0.13.0
Updating one outdated app:
Updating 'buffalo' (0.12.7 -> 0.13.0)
Uninstalling 'buffalo' (0.12.7)
Removing shim for 'buffalo'.
Unlinking ~\scoop\apps\buffalo\current
Installing 'buffalo' (0.13.0) [64bit]
buffalo_0.13.0_windows_amd64.tar.gz (5.9 MB) [===========================================================================================] 100%
Checking hash of buffalo_0.13.0_windows_amd64.tar.gz ... ok.
Extracting buffalo_0.13.0_windows_amd64.tar.gz ... done.
Linking ~\scoop\apps\buffalo\current => ~\scoop\apps\buffalo\0.13.0
Creating shim for 'buffalo'.
Can't shim 'buffalo.exe': File doesn't exist.
```
```
$ 7z.exe l buffalo_0.13.0_windows_amd64.tar
7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the …
```

[Buffalo] Fix executable file name

---

bin/install.ps1

Under certain terminals like cmder, `Get-ExecutionPolicy` will show the scope of `Process`.  This fix explicitly checks the scope of `CurrentUser`.
Signed-off-by: Ben Dang <me@bdang.it>

Fix the check for ExecutionPolicy scope

---

test/Scoop-Core.Tests.ps1

Updated all the tests in `Scoop-Core.Tests.ps1` to use the newer 4.0 Pester syntax.

use pester 4.0 syntax in core tests

---

test/Scoop-Install.Tests.ps1

This PR updates the `should` Pester calls with the 4.0 syntax in the `Scoop-Install.Tests.ps1` file

add pester 4.0 syntax to the install tests

---

bucket/iperf3.json

This adds the command-line network benchmarking tool [iperf3](https://iperf.fr/).

Add iperf3 version 3.1.3

---

lib/core.ps1

Fixes #2740.
Adding .exe suffix to cmd is needed in WSL.
Removing MSYS' slash-escaping from //C is needed in WSL, Cygwin, or anywhere outside MSYS (or Git Bash). Doesn't break MSYS after .exe suffix is added.
See also #1949, #1951

Fixed sh shims

---

lib/psmodules.ps1

The default user PSModulePath is "$home\Documents\WindowsPowerShell\Modules". If the user env variable PSModulePath actually exists the default path is omitted - so we need to explicitly add it.
Related issue #2745

Fix #2745 Workaround microsofts syntactic PSModulePath

---

bin/checkver.ps1

Here's where this came in useful: 
Jdupes's latest binary release is [1.11](https://github.com/jbruchon/jdupes/releases), but they created a 1.11.1 tag for documentation purposes.
To have checkver grab the 1.11 release, we can now do this:
```
checkver.ps1 jdupes -u -v 1.11
```

Add -v option to checkver.ps1

---

bucket/git-istage.json

git-istage is a [dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) that improves the staging experience for git on the command line.
dotnet tools are distributed as platform-independent NuGet packages. The client then creates platform-specific executables out of the NuGet package. This manifest describes exactly that: it's just a wrapper around installing the package with `dotnet tool` (with some quirks I must admit). The advantage is that I can manage git-istage with scoop, as most of my other software. So I don't have to think about which package I installed with which package manager.
There are already [a lot of dotnet tools](https://github.com/natemcmaster/dotnet-tools) that I would like to install with scoop instead and I might imagine that scoop manifests …

Add manifest for git-istage

---

bin/missing-checkver.ps1

- Fix bug presented in https://github.com/lukesampson/scoop/commit/2a2c2059e00e3cca9fd87d1cacf0352bd39cfb0e#diff-67e44d47bfea08ffe769c6adc77f7215R22
- Missed $ before bracket
- Add `App` parameter
- Format

Fix missingcheckver

---

bucket/gnirehtet.json

[gnirehtet](https://github.com/Genymobile/gnirehtet) is a tool for reverse tethering on Android. This is useful if you want to share a PC's connection to a mobile device (e.g. in an area where you cannot connect your device to a Wi-Fi network).

Add gnirehtet version 2.3

---

bucket/pshazz.json

Since current version of pshazz in scoop is 0.2018.04.22, and it is in conflict with PowerShell Core v6.1.x. Recent commits solve this, and this is the update with checkver.

pshazz: Update to version 0.2018.09.25

---

bucket/rcedit.json

[rcedit](https://github.com/electron/rcedit) is a command-line tool that can be used to edit resources embedded in PE executables (such as icons).

Add rcedit version 1.1.1
