ScoopInstaller/Scoop

- bucket/datamash.json
GNU datamash is a command-line program which performs basic numeric, textual and statistical operations on input textual data files
> Add GNU datamash

- bucket/dotnet-sdk.json
fixes #2843 fixes #2846 fixes #2847 fixes #2848 fixes #2853 fixes #2854 fixes #2855
> dotnet-sdk: fix hashes (2.2.100-sdk-sha.txt has bad shas)

- bucket/qemu.json
Hashes did not match - this uses the official sha512 hashes.
```
λ scoop install qemu
Installing 'qemu' (3.1.0-rc3) [64bit]
Loading qemu-w64-setup-20181128.exe from cache
Checking hash of qemu-w64-setup-20181128.exe ... ERROR Hash check failed!
App:         qemu
URL:         https://qemu.weilnetz.de/w64/qemu-w64-setup-20181128.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    7f58c2486ca9d6ab464e9304861b75208031c3e4acc250798fc0fe5312d7e0f2
Actual:      c2286dc73fc1f7f0f274725ab73e713681f7b9eb049e654995dc0879262a409f
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=qemu%403.1.0-rc3%3a+hash+check+failed
```
> qemu: fix hashes and shims for version 3.1.0-rc3

- bucket/git-lfs.json
Binary name was changed to `git-lfs.exe` again by v2.6.1 release.
https://github.com/git-lfs/git-lfs/issues/3361
Ref https://github.com/lukesampson/scoop/issues/2734
> git-lfs: adapt to upstream binary name fix

- bin/checkurls.ps1
> [checkurls] Add SkipValid Parameter

- bucket/lua-for-windows.json
There are three full Lua installations that provide Lua binary for windows users, Lua-for-Windows (this one), LuaDist, and LuaRocks. Changing this bucket's name to lua-for-windows is more appropriate. 
Besides, luarocks doesn't work if `$env:LUA_DEV` is not set, so there is a fix.
> lua: rename to 'lua-for-windows' and fix env

- lib/autoupdate.ps1
sha512 encoded hash length for [Franz](https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.19/latest.yml) is 88 characters length and autoupdate just dont extract it's value.
If anyone have better fix, feel free to edit.
Relate lukesampson/scoop-extras#1487
> [autoupdate] base64 hash extraction length

- bucket/hugo-extended.json
This change adds the configuration to install the extended version of the hugo static site generator.
Hugo comes in two flavors. The base package (which is currently installable through scoop) and the "extended" version.
The extended version adds (among other things) support for using Sass/Cscc, resource minification, fingerprinting, and bundling - [See docs of more](https://gohugo.io/hugo-pipes/).
Note, this is a simple edit of the current hugo.json to pick up a slightly different file name and hash file. Also, the extended version is only supported on 64bit.
> hugo-extended - Add the "extended" version of hugo

- bucket/winpython.json
I had to change the checkver url to get it updated.
Also, since Python 3.7, Winpython switched to innosetup, so I updated the manifest accordingly.
To remove all optional stuff I wanted to use the "extract_dir" as before, but with innosetup I had to write a pre_install script which, I'm afraid, it may not be the best in terms of efficiency... so please be welcome to edit it if you think there's a better way to accomplish that.
> Fix winpython's checkver and switch to innosetup

- bucket/nvs.json
Add nvs v1.5.1, a more powerful Node.js versions tool on Windows than nvm-windows made by @jasongin.
- Name: Node Version Switcher
- Description: A cross-platform tool for switching between versions and forks of Node.js
- Version: 1.5.1
- Homepage: https://github.com/jasongin/nvs
- Basic usage
- To add the latest version of node:
```powershell
$ nvs add latest
```
- Or to add the latest LTS version of node:
```powershell
$ nvs add lts
```
- Then run the `nvs use` command to add a version of node to your PATH for the current shell:
```powershell
$ nvs use lts
PATH += ~/.nvs/node/10.14.2/x64
```
- To add it to PATH permanently, use `nvs link`:
```powershell
$ nvs link lts
```
- Known Issue: Sometimes nvs will show an `EPERM: operation not permitted.` error during first adding some Node.js …
> nvs: Add version 1.5.1

- bucket/cloc.json
Fixes the [`cloc`](https://github.com/AlDanial/cloc/releases/) url. While there still seem to be version tags around for versions including the `v`, the binaries are only attached to the version tags without `v`.
> Fix cloc url and add alias

- lib/buckets.ps1
- Closes #2531 
Actual behaviour is kept and nothing is broken.
If external bucket contains `bucket` folder it's used for finding manifests. This should keep external repositories more friendly for new users to see Readme without additional scrolling.
Feel free to suggest directory name change. I kept same as main bucket.
How to test:
1. Create folder `TestBucket` in `$env:SCOOP\buckets`
1. Create manifest `CosiTest.json` with hello manifest # Or some other name which definitely cannot exists❗
1. execute `.\bin\scoop.ps1 install CosiTest` within this branch
1. Installing done
1. `.\bin\scoop.ps1 uninstall CosiTest`
1. Create folder `bucket` in `TestBucket` directory and copy CosiTest.json as `bucket\CosiTestBucket.json`
1. `.\bin\scoop.ps1 install CosiTest`
1. Installation will failed …
> Support nested bucket folder in external buckets

- bucket/dig.json
Install fails on development version 9.13.5 because missing dig.exe in archive.
> dig: Match stable version, update to 9.12.3-P1

- bucket/exiftool.json
There is no way to stop `exiftool(-k).exe` from pausing without renaming the executable to `exiftool.exe`
> exiftool: add bin file without -k option

- bucket/sqlite.json
sqlite's version is 3.26.0 insqlite.json.
But sqlite's download url still is "sqli...-3250300.zip"
3250300.zip means version 3.25.3
I update it to "sqli...-3260000.zip" also update it sha256sum(hash value)
> update sqlite url and hash from 3.5.3 to 3.6.0

- libexec/scoop-search.ps1
> scoop-search: add config.ps1 to load proxy settings

- bucket/doxygen.json
Doxygen is no longer available on stack.nl but instead on doxygen.nl
> Update doxygen after Domain change

- bucket/nvs.json
The EPERM error seem to be fixed in v1.5.2.
> nvs: Delete note due to author's fix.

- bucket/mls-software-openssh.json
`ssh-agent.exe` requires `tmp` directory.
> mls-software-openssh: fix tmp dir not exist

- bucket/latex.json
Update Miktex from version 2.9.6753 to 2.9.6942.
The URL of the old version (2.9.6753) is down and results in a 404 error.
> Update latex.json - Miktex version 2.9.6942

- lib/core.ps1
See #2907.
Tests for string and null are no longer needed.
> Simplified `last_scoop_update()`.

- bucket/pshazz.json
As of version 0.2019.01.12 (specifically, https://github.com/lukesampson/pshazz/commit/32bce43fcb13aa28c377a084626e5294c2bbf2b6), pshazz does no longer have an askpass.exe binary, which results in an error while shimming:
```
Creating shim for 'askpass'.
Can't shim 'libexec\askpass.exe': File doesn't exist.
```
This PR removes the binary from the manifest.
> Fix pshazz manifest

- bucket/allure.json
Allure distributions are moved to Maven Central. For more details please see https://github.com/allure-framework/allure2/issues/832
> Allure: update distribution url to Maven Central

- bin/auto-pr.ps1
- Add synopsis
- Add Native parameter validation
- Help parameter never worked if you do not have hub installed
- Moved check for hub after help parameter check
- You can now run `auto-pr -Help` without installed hub
- Use heredoc instead of string gluing
- Use markdown syntax for commit message
- Table produced was wrong rendered due to element mismatch
- ![wrong syntax](https://i.imgur.com/CgoXlvo.png)
- Format
> [auto-pr] Fix table syntax, allow help without hub, format

- bucket/mongodb.json
- Add `autoupdate.hash`
- Add `description`
- Change license according to [MongoDB Licensing](https://www.mongodb.com/community/licensing)
[SSPL-1.0](https://www.mongodb.com/licensing/server-side-public-license) is not an identifier found at spdx.org, but a new license introduced by MongoDB based on GPL-3.0. And MongoDB has submitted the SSPL to the OSI for approval. If it is not proper, "Freeware" is another choice.
> mongodb: add autoupdate.hash and fix license

- lib/install.ps1
- libexec/scoop-cleanup.ps1
- libexec/scoop-reset.ps1
- libexec/scoop-uninstall.ps1
- test/Scoop-Install.Tests.ps1
**Data matters, please review**
This is a rework of #2891 #2890 and #2882 . This will also fix #2724 and fix #2900 , close #2779 
**Introduction**
I add a function called `unlink_persist_data($dir)`, which recursively unlink all junction/hard link in the given directory. This affects some sub-commands which have interaction with junction/hard link:
- `scoop-install`: the persisting logic has been improved as follow:
1. if there are data in the `persist` folder, also in app(`source`) folder, rename that one located in app folder (e.g. app's default setting files) with a `original` suffix, then create link from `persist` to  app
2. if there are data in the `persist` folder, but no in app(`source`) folder, just create link from `persist` to  app
3. if there is no data in the `persist` folder …
> rewrite data persisting

- lib/autoupdate.ps1
- lib/core.ps1
- lib/json.ps1
Add [version variables](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#version-variables) to `autoupdate.hash.regex` for some hash extract situations.
The idea is from Atom's nupkg hash extraction. Atom's [releases page](https://github.com/atom/atom/releases/latest) provides nupkg named `atom-1.34.0-full.nupkg` (for i686) and `atom-x64-1.34.0-full.nupkg` (for x64_86), and it also provides [`RELEASES`](https://github.com/atom/atom/releases/download/v1.34.0/RELEASES) and [`RELEASES-x64`](https://github.com/atom/atom/releases/download/v1.34.0/RELEASES-x64) files that give sha1 hash of nupkg files. Unfortunately in `RELEASES-x64` the nupkg file name is `atom-1.34.0-full.nupkg` without `-x64`. 
I haven't found some method to write a regex to extract the hash without …
> Add version variables to autoupdate.hash.regex

- lib/install.ps1
#2897 regression. The empty directory target didn't be created.
> fix(persist): fix the target didn't be created

- lib/json.ps1
Some JSON file ([example](https://mranapi.azurewebsites.net/api/download)) is surrounded by brackets ("[", "]") and cannot be parsed using `[Newtonsoft.Json.Linq.JObject]::Parse()` in `json_path()`. Instead, they could be parsed by `[Newtonsoft.Json.Linq.JArray]::Parse()` and then be treated as normal, e.g., applies a filter (script) expression.
- Add `[Newtonsoft.Json.Linq.JArray]::Parse()` after `[Newtonsoft.Json.Linq.JObject]::Parse()` failed
- Some JArray are handled by `json_path_legacy()` when `json_path()` throw error before, and the JSONPath is illegal when parsed with `JArray::Parse()`. To keep compatibility, add try-catch in this situation and let `json_path_legacy()` handle them still.
- In the above situation, manifest maintainer should use double dots after `$`, i.e., use …
> Add JArray::Parse() to json_path in lib/json.ps1

- bin/auto-pr.ps1
On my end result of `hub status --porcelain -uno` is prefixed with space on left for some reason, which failed test for `startsWith('M  ')` since it's strict match
Alternatively $status could be Trimed before condition
> [auto-pr] Use regex instead of Starts|EndsWith

- bucket/hyperfine.json
Added [`hyperfine`](https://github.com/sharkdp/hyperfine) - a command-line benchmarking tool.
> Add hyperfine manifest

- bucket/empty-recycle-bin.json
Command-line tool to empty the Windows recycle bin. This is complement to the existing [recycle-bin](https://github.com/lukesampson/scoop/blob/master/bucket/recycle-bin.json) tool by the same author.
> Add empty-recycle-bin 1.0.0

- libexec/scoop-update.ps1
There is no need to call scoop using external script, when you can use internal library functions.
This will prevent `Scoop is not recognized as internal command` when updating.
> [scoop-update] Use [g|s]et-config instead of scoop call

- lib/buckets.ps1
- libexec/scoop-bucket.ps1
There is no reason to have it inside lib-exec since, it's all internal functions, which could be used inside other code
- Remove `list_buckets` function.
- It's only function, which call `buckets`
lib-exec scripts should be slimmed as possible, as they are only code runners with some validation
> buckets: Move function into lib from lib-exec

- bin/checkurls.ps1
- bin/checkver.ps1
- lib/core.ps1
- lib/install.ps1
reopen #3051 
Now the code logic: if `SecurityProtocol` is `SystemDefault`, don't change, else change it to `Tls1.2,Tls1.1,Tls1.0`,  never support `Ssl3` anymore.
> refactor: tweak SecurityProtocol usage

- lib/git.ps1
- libexec/scoop-update.ps1
There is not possible to 'hot' change branches. 
If you want to change branch now, you need to delete `.git` folder inside `$env:SCOOP_HOME` to proc clonning of new branch
https://github.com/lukesampson/scoop/blob/4197fa98a5b2b513c627734e3b4aef3df5827e3b/libexec/scoop-update.ps1#L64-L68
Actual behaviour, which is desired I think:
1. `scoop config SCOOP_BRANCH somebranch`
1. `scoop update`  This will checkout to branch and download changes
> [scoop-update] Checkout to branch on change

- bucket/sccache.json
* The tarball has an internal directory named the same as itself
* Add extract_dir to autoupdate for future versions
> Fix sccache

- bucket/rclone.json
- Add `description`
- Use download urls in `downloads.rclone.org` (main site)
- Add `env_set` to persist config in persist_dir of scoop
- Use version file in download site to `checkver`
- Add `autoupdate.hash`
> rclone: Add desc and au.hash, persist config, and use download url in main site

- bin/scoop.ps1
make sure configs have been loaded every time when user run `scoop` command and sub-command.
> source config.ps1 in scoop bin

- bucket/nim.json
Installation fails on missing files c2nim and makelink.  Installation completes with these two lines removed.
> Remove missing files

- lib/autoupdate.ps1
- lib/core.ps1
- Fix broken fosshub.com url handle function. It can handle urls like `https://www.fosshub.com/Calibre.html/calibre-64bit-3.39.1.msi` or `https://www.fosshub.com/Audacity.html?dwl=audacity-win-2.3.0.zip` and get the right download link.
- Add `fosshub` hash extraction mode.
> Fix fosshub.com url handler and add fosshub hash mode

- libexec/scoop-info.ps1
For dual licenses in manifest, e.g. "MIT|GPL", `scoop info` will return wrong URL (`https://spdx.org/licenses/MIT|GPL.html`).
This PR fixes it (return `https://spdx.org/licenses/MIT.html, https://spdx.org/licenses/GPL.html`)
> Fix dual license error in "scoop info"

- libexec/scoop-list.ps1
This is minor fix for #3089, lukesampson/scoop-extras#1720 to confort users, until install is refactored.
Global indication color was changed to DarkGreen. I don't know, if there was some reason to make it DarkRed in first place? This make more sense to me, but feel free to suggest better name / color. I followed `status` naming with failed.
- Closes #3089
- Closes lukesampson/scoop-extras#1720
> scoop-list: Identify failed installation

- bucket/buffalo.json
They changed the name back to `buffalo.exe`. I'm not super familiar with scoop (just started using it yesterday). But making this change on my `C:\Users\$User\scoop\apps\scoop\current\bucket\buffalo.json` seems to have gotten in installed, so I hope this is the right way to do it.
- Update Commit Here:  https://github.com/lukesampson/scoop/commit/b342ddd305455844d91de0d985817bb4b7d8f2de
- Rename Here: https://github.com/gobuffalo/buffalo/commit/7335d7019683031067128937a8493e130e59f89c
> Update name of the buffalo binary for 0.14.0

- lib/core.ps1
- test/Scoop-Core.Tests.ps1
For example: `gcc-x86_64` (this is not host architecture, which can be expressed by `-a`, but target one).
> Allowed underscores in package names.

- lib/core.ps1
Currently it is not possible to uninstall apps that have a `_` in their name. E.g. `uninstall scoop_ruby` uninstalls `scoop`.
Based on https://github.com/lukesampson/scoop/issues/3128#issuecomment-463662715
closes #3128
> Allow uninstall of apps with underscore

- lib/core.ps1
The bash script file generated from scoop should not invoking profile of powershell. The cmd script has already done that, the bash script should follow.
> add -noprofile back when creating bash script shim

- bucket/innounp.json
Commit with update will come after scoopinstaller/binary-mirror#2 is merged
- Closes #3047 
- Closes #3069
> innounp: Add autoupdate and bump to 0.48

- bucket/concfg.json
- bucket/gitignore.json
- bucket/ln.json
- bucket/pshazz.json
- bucket/psutils.json
- bucket/runat.json
- bucket/sudo.json
- bucket/time.json
- bucket/touch.json
- bucket/vimtutor.json
- Using `/commits/master.atom` file in `checkver` to avoid github page load error (get wrong commit date 2016.03.23)
- Modify `checkver` of tools in `psutils` that return last modify date of single `ps1` file.
> pshazz, concfg, psutils: Fix checkver error

- bucket/jdupes.json
[jdupes](https://github.com/jbruchon/jdupes) is a duplicate file finder based on fdupes.
PS: `extract_dir` is not being updated when I run `bin/checkver.ps1 jdupes -Update -f` (unlike `url` and `hash`), why is that? Ideally, I'd like to use the autoupdate information to generate the initial download information (if it's not present), to make it easier to create new manifests.
> Add jdupes version 1.12

- bucket/octave.json
Octave has changed folder structure in latest release. In the new layout binaries for different architectures end up in different folder, and this also means that Scoop's aliases creation defined in for previous version of Octave will not longer work.
Bucket definition was updated to reflect change in binaries structure.
> Octave: fixing aliases

- lib/autoupdate.ps1
- schema.json
Schema is missing property for metalink
See: https://github.com/lukesampson/scoop/blob/57b0b0e1eb2c946ca74541b2464d3e61e195e979/lib/autoupdate.ps1#L213-L218
> [Schema] Add metalink mode to hashmode

- bin/install.ps1
- lib/core.ps1
- lib/decompress.ps1
- lib/install.ps1
- test/Scoop-Core.Tests.ps1
- test/Scoop-Decompress.Tests.ps1
EDITED: Split PR, PART I
- Move Functions (to `decompress.ps1`)
- `extract_zip` and `unzip_old` from `core.ps1`
- `unpack_inno`, `extract_msi`, `lessmsi_config` and `extract_lessmsi` from `install.ps1`
- Modify Test
- Move `unzip_old` test from `Scoop-Core.Tests.ps1` to `Scoop-Decompress.Tests.ps1`
Thanks for @Ash258 #3149, this could be part of it.
> decompress.ps1: Refactored (w/ install.ps1, core.ps1) (edited)

- bucket/premake.json
- bucket/premake4.json
[premake4](https://github.com/scoopinstaller/versions/blob/master/bucket/premake4.json) and [premake5](https://github.com/scoopinstaller/versions/blob/master/bucket/premake5.json) are in versions bucket already.
And since premake's current version is 5 (although still in alpha), rename premake5 to premake and delete premake4 in main bucket.
> premake: Rename premake5 to premake, move premake4 to versions bucket

- libexec/scoop-cleanup.ps1
Add `-k` and `--cache` param in `scoop cleanup` cmd to cleanup outdated download caches when required.
`-k` and `--cache` is following `scoop install`'s param list.
> scoop-cleanup: Add param to cleanup outdated download cache

- libexec/scoop-update.ps1
This is temporary solution for #2220 until whole install.ps1 refactor is done to make this tweak easily, in the best way one-liner. ~~Today i will follow with issue how this refactor should looks like, because there is some inconsistency and could be much more easier to maintain.~~ #3149 
- Closes #2220
- Closes #2343
- Closes #1605 
Co-authored-by: Chawye Hsu <h404bi@outlook.com>
> [Workaround] Download and verify before update

- lib/install.ps1
This will allow us to differentiate files from directories in persist:
```json
"persist": [
"FastCopy2.ini",
"Log/"
],
```
By doing this, we can create the persisted files and directories for the user, if the installer/pre_install fail to create them first.
Here's a (probably incomplete) list of apps in main/extras/versions where we could remove the create file/directory logic from their `pre_install` section:
[main/inadyn-mt](https://github.com/lukesampson/scoop/blob/master/bucket/inadyn-mt.json)
[main/lynx](https://github.com/lukesampson/scoop/blob/master/bucket/lynx.json)
[main/nvm](https://github.com/lukesampson/scoop/blob/master/bucket/nvm.json)
[extras/bandizip](https://github.com/lukesampson/scoop-extras/blob/master/bucket/bandizip.json) …
> Allow persist dirs to have trailing slash

- lib/autoupdate.ps1
- lib/core.ps1
EDITED: No WebRequest, Local URL Treatment
Current `url_remote_filename()` cannot handle redirected urls like "https://www.apache.org/dyn/closer.cgi?action=download&filename=tomcat/tomcat-9/v9.0.14/bin/apache-tomcat-9.0.14-windows-x64.zip", this modified one works in most cases.
- Get filename from PathAndQuery instead of AbsolutePath
- Throw away leading `?=`
- If got `vxx.xx.xx`, fallback to AbsolutePath
- Use fragment name if all above failed
> core.ps1: Fix url_remote_filename (edited)

- bucket/gopass.json
32bit binary is no longer released.
https://github.com/gopasspw/gopass/releases/tag/v1.8.5
https://github.com/gopasspw/gopass/commit/e2a571e518d162a564d291496999e337180a38d3
> gopass: Update to version 1.8.5

- bucket/jom.json
changelog.txt may redirect and give an error, so change to md5sums.txt to check new version
> jom: Fix checkver and au.hash

- bucket/yarn.json
- Yarn's global folder can be set via `yarn config set global-folder` (https://github.com/yarnpkg/yarn/pull/7056) and thus can be persisted. 
- ~~Since yarn's global bin creating procedure is still problematic (https://github.com/yarnpkg/yarn/issues/6902, **fixed by https://github.com/yarnpkg/yarn/pull/6954**),~~ The `.bin` folder in `global\node_modules` is a better path to add to env, and this can avoid the annoying problem when you install scoop in some place except `C:` (that the shims in global bin have wrong relative path pointer).
- If you install yarn via `scoop install yarn`, the `Yarn` folder in `$env:LOCALAPPDATA` is useless, and when you uninstall `yarn`, the `.yarnrc` is unused, so the manifest add `uninstaller.script` to remove them when you uninstall.
- For reconfiguration, …
> yarn: Make `global` persist and fix global bin issue

- lib/buckets.ps1
- Closes lukesampson/scoop-extras#1794
Regression from pretty old PR with bucket folder adoption. 
Now only bucket folder is deleted, when removing bucket (due to bucketdir function).
> [buckets] Fix regression from bucket folder structure

- libexec/scoop-cleanup.ps1
Now `-k` will not give error when you cleanup while installing or updating apps (some `*.download` will be locked).
> scoop-cleanup: Fix '-k' to ignore locked dl cache

- bucket/blat.json
Under active development, [alternatives of `sendmail`](https://www.glob.com.au/sendmail/#alternatives)
> blat: Add version 3.2.19

- bucket/cmake.json
#3253 
https://cmake.org/files/v3.14/cmake-3.14.0-SHA-256.txt
```
97f34f3ce6657a65c5232bfc1ecea41c8e7bf084d35ce5a43c58f02b97143771  cmake-3.14.0-Darwin-x86_64.dmg
a02ad0d5b955dfad54c095bd7e937eafbbbfe8a99860107025cc442290a3e903  cmake-3.14.0-Darwin-x86_64.tar.gz
7f3e227cfd9804ee9931490a83cb7029991bc73573ceb1c8ba11714775e8c334  cmake-3.14.0-Linux-x86_64.sh
91dc9af7345e458eb10c853aa875e591efb7079a045641685ddec8d973c2b2bc  cmake-3.14.0-Linux-x86_64.tar.gz
913b231e189824b679b60d9c9d45549bb047866431cd023afbb0b9d10e579279  cmake-3.14.0-win32-x86.msi
9eb42917f9c5dc30ff86d8197497e4f8e2f4455b4c07841aa3dfb3283902d1ee  cmake-3.14.0-win32-x86.zip
2e61b8d41514b36e7d8de455e5201b5a44d36fb33667a5dba5b5fcb656788d44  cmake-3.14.0-win64-x64.msi
40e8140d68120378262322bbc8c261db8d184d7838423b2e5bf688a6209d3807 …
```
> Cmake 3.14.0: fix hash

- lib/autoupdate.ps1
Enable `$checksum` passthrough BASE64 encoded checksum, e.g. `sha512` of `latest.yml` in many electron released apps (joplin, netron, etc.).
md5:     32 -> 22 + 2
sha1:    40 -> 27 + 1
sha256:  64 -> 43 + 1
sha512: 128 -> 86 + 2
> `autoupdate.ps1`: Fix `$checksum` to allow BASE64

- lib/install.ps1
When run update with aria2 enabled, a wrong file are stored in cache dir.
If target dir is cachedir, dont copy/move
Current Example: `scoop update busybox -f`
```
// without aria2:
busybox#3025-gc01300361#https_frippery.org_files_busybox_busybox-w64-FRP-3025-gc01300361.exe_busybox.exe
// with aria2:
busybox#3025-gc01300361#https_frippery.org_files_busybox_busybox-w64-FRP-3025-gc01300361.exe_busybox.exe
busybox.exe
```
> Fixed cache copy with aria2 when update

- bucket/nunit-console.json
- bucket/nunit-extension-nunit-project-loader.json
- bucket/nunit-extension-nunit-v2-driver.json
- bucket/nunit-extension-nunit-v2-result-writer.json
- bucket/nunit-extension-teamcity-event-listener.json
- bucket/nunit-extension-vs-project-loader.json
Close #3304 
Add seperated extensions, and after installation, NUnit Console Runner could find them automatically.
> nunit-console: Fix manifest and add extensions

- bin/scoop.ps1
- lib/buckets.ps1
- lib/core.ps1
- lib/depends.ps1
- libexec/scoop-bucket.ps1
- libexec/scoop-search.ps1
- libexec/scoop-update.ps1
- Use Verb-Noun naming
Keep `buckets` function for compatibility if someone use it inside manifests.
> [buckets] Optimize buckets function

- lib/buckets.ps1
- libexec/scoop-search.ps1
- Closes #3349 
`Get-LocalBucket` will return $null if folder does not exists, or is empty. So if this function return something, add $null for main. With actual implementaion there was two runs of main bucket when empty `@($null) + @($null)`
> [Regression] Fix search after buckets optimize

- lib/buckets.ps1
- libexec/scoop-search.ps1
Unhandled if case is pretty no go, but this will work unless bucket extraction is done.
> [buckets] Get bach to if

- lib/buckets.ps1
Fix error when hash check failed. `main` is a known bucket and will returned by `Find-Manifest`, so the exception is needless.
> buckets.ps1: Fix new_issue_msg

- lib/git.ps1
- libexec/scoop-update.ps1
close #3368 
The hotfix should also be committed into the develop branch.
> fix(scoop-update): fix branch switching

- libexec/scoop-update.ps1
Add notification.
```
$ scoop update
Updating Scoop...
Checking repo... ok
The main bucket was added successfully.
Updating 'dorado' bucket...
Updating 'extras' bucket...
Updating 'java' bucket...
Updating 'main' bucket...
Updating 'versions' bucket...
```
```
$ scoop update
Updating Scoop...
The main bucket of Scoop has been separated to 'https://github.com/scoopinstaller/scoop-main'
Adding main bucket...
Checking repo... ok
The main bucket was added successfully.
Updating 'dorado' bucket...
Updating 'extras' bucket...
Updating 'java' bucket...
Updating 'main' bucket...
Updating 'versions' bucket...
```
> chore: add notification for new main bucket

- lib/diagnostic.ps1
- libexec/scoop-checkup.ps1
> feat: Check for LongPaths setting

- README.md
- bin/install.ps1
- libexec/scoop-update.ps1
> PowerShell: Update requirement to version 5

- appveyor.yml
- test/Scoop-Decompress.Tests.ps1
- test/bin/init.ps1
- test/bin/test.ps1
- Download `innounp` and `lessmsi` via PowerShell instead of using Scoop
- `7zip` is already available on AppVeyor images
- Doesn't require the main bucket to be added
- Install `innounp`/`lessmsi`/`7zip` if `$env:CI` is false and program is not installed
- Mock `file_path` to return correct path to helper programs
- Add Scoop environment variables `SCOOP` and `SCOOP_HOME`
- Remove newlines from `appveyor.yml`
> decompress(tests): Improve installation of lessmsi and innounp

- lib/core.ps1
- libexec/scoop-cleanup.ps1
- libexec/scoop-uninstall.ps1
- libexec/scoop-update.ps1
> refactor(core): ensure_all_installed() to Confirm-InstallationStatus()

- lib/decompress.ps1
ref: https://github.com/lukesampson/scoop-extras/pull/2021#issuecomment-484182951, https://github.com/lukesampson/scoop/pull/3204#issuecomment-484402074
- Add new param `Overwrite` to `Expand-7ZipArchive`, with following values
- "All": 7z param `-aoa`, overwrite All existing files without prompt, behave the same with default
- "Skip": 7z param `-aos`, Skip extracting of existing files
- "Rename": 7z param `-aou`, aUto rename extracting file
- Add new param `Switches` to `Expand-7ZipArchive` and `Expand-InnoArchive`
- It could pass all unrecognized params to `7z` and `innounp`
- Patch `extract_7zip` and `unpack_inno` to adapt to `Expand-XXX`
Usage: https://github.com/lukesampson/scoop-extras/pull/2021, https://github.com/lukesampson/scoop-extras/pull/2070
> Patch(decompress): Allow other args to be passthrough

- bin/scoop.ps1
- lib/git.ps1
Close #3400 . It's a hotfix and should be merged into master. And then sync it to develop branch.
```
$ scoop status
WARN  The main bucket of Scoop has been separated to 'https://github.com/scoopinstaller/scoop-main'
WARN  You don't have the main bucket added, adding main bucket for you...
Checking repo... ok
The main bucket was added successfully.
$
```
> fix: force to add new main bucket

- lib/core.ps1
- lib/decompress.ps1
- lib/depends.ps1
- lib/install.ps1
- libexec/scoop-install.ps1
- libexec/scoop-update.ps1
- test/Scoop-Core.Tests.ps1
- test/Scoop-Decompress.Tests.ps1
Fixes:
- Prevents installing 7zip/lessmsi/innounp locally if they are already available globally
Additions:
- `Get-HelperPath`
- `Test-HelperInstalled`
- ~`Get-LessmsiPath`~ `Get-HelperPath -Helper Lessmsi`
- ~`Test-LessmsiInstalled`~ `Test-HelperInstalled -Helper Lessmsi`
- ~`Get-InnounpPath`~ `Get-HelperPath -Helper Innounp`
- ~`Test-InnounpInstalled`~ `Test-HelperInstalled -Helper Innounp`
- `Get-HelperPath -Helper Dark`
- `Test-HelperInstalled -Helper Dark`
Added tests for:
- `Get-AppFilePath`
- `Get-HelperPath`
- `Test-HelperInstalled`
- `Test-Aria2Enabled`
- `Test-CommandAvailable`
Refactors:
- `aria2_path` > `Get-HelperPath -Helper Aria2`
- `aria2_installed` > `Test-HelperInstalled -Helper Aria2`
- `aria2_enabled` > `Test-Aria2Enabled`
- `7zip_path` > `Get-HelperPath -Helper 7zip` …
> Refactor function names and fix installing 7zip locally if already globally available

- lib/decompress.ps1
- test/Scoop-Decompress.Tests.ps1
fixes scoopinstaller/scoop-main#19
> Expand-ZipArchive: Compatible with Pscx (was missing tests)

- libexec/scoop-cache.ps1
Countless times I've tried to run `scoop cache clear` wondering why it didn't work. 😶
> 🚸 Display help on incorrect cache command

- README.md
- lib/core.ps1
- lib/unix.ps1
- libexec/scoop-checkup.ps1
Reopen #3116 . ~~This is a breaking change.~~
- ~~revert #3115 , import `config.ps1` in `core.ps1` instead~~
- add support loading env from `~/.config/scoop/config.json` config file, preparing for the new scoop installer (see [scoopinstaller/install#2](https://github.com/scoopinstaller/install/issues/2) and [scoopinstaller/install#4](https://github.com/ScoopInstaller/Install/pull/4))
- drop `$oldscoopdir = "$env:LOCALAPPDATA\scoop"` support, I think nobody use old scoop dir now, it has been 3 years.
> feat(core): support loading basedirs from config

- lib/core.ps1
- lib/decompress.ps1
- lib/depends.ps1
- libexec/scoop-checkup.ps1
- Add `Expand-DarkArchive` helper function
- Allow `dark.exe` from wixtoolset and `7zip-zstd` as valid helpers
- Add warnings to 'scoop checkup' for missing unpackers
- Auto detect dependencies from `pre_install`/`post_install` and `installer.script` by simply searching for the function names.
Should be merge into `develop` before merging `develop` into `master`.
This will allow us to remove the `dark` dependency from some manifests.
`Expand-7zipArchive` is widely used without the manifest actually depending on it. 
The installation will fail with the following message when `Get-HelperPath` returns nothing.
```
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
``` …
> Add Expand-DarkArchive and some other dependency features

- libexec/scoop-update.ps1
Now you can change scoop's tracking repository to your own fork like this:
```
$ scoop config SCOOP_REPO "https://github.com/h404bi/scoop"
$ scoop config SCOOP_BRANCH "patch-17"
$ scoop update
```
This is really helpful for scoop development.
BE CAREFUL: If you changed to a branch/fork which is kinda "older" than the official repo, you probably can not change it back.
> fix(update): support changing scoop tracking repository

- bin/checkver.ps1
- lib/autoupdate.ps1
- schema.json
Close #3451 
TODO list:
*to be supplemented*
> feat(manifest): xpath support in checkver and autoupdate

- bin/checkver.ps1
- lib/autoupdate.ps1
Fix https://github.com/lukesampson/scoop/pull/3458#issuecomment-492570939
> fix(autoupdate): Handle xml namespace in xpath mode

- libexec/scoop-config.ps1
Example input:
`scoop config rm proxy`
Example output:
Before: `'rm' has been removed`
Fixed: `'proxy' has been removed`
> fix(config): show correct output when removing a config value

- lib/core.ps1
- lib/decompress.ps1
- lib/install.ps1
Refactor `run` in `install.ps1`
- Rename to `Invoke-ExternalCommand` and move to `core.ps1`
- Use `Invoke-ExternalCommand` to refactor `Expand-7zipArchive`, `Expand-MsiArchive`, `Expand-InnoArchive`
TODO in next PR: Refactor `Expand-XXXArchive` to use an universal interface, just as `Get-HelperPath`, for further extending.
> refactor(core):  Add more generic 'Invoke-ExternalCommand' instead of 'run'

- lib/decompress.ps1
- lib/install.ps1
Move `$extract_dir` and `$extract_to` to `decompress.ps1` so as to not run `robocopy` so many times.
Tested on
- 'slack'(w/ `extract_dir`, 7z/nupkg)
- 'brackets'(w/ `extract_dir`, msiexec/lessmsi)
- 'atom-portable'(w/ `extract_dir` and `extract_to`)
- 'irfanview'(w/ multi `extract_to`)
- 'unxutils'(w/ `extract_to` overwrite)
> feature(decompress): Add 'ExtractDir' to 'Expand-...' functions

- lib/decompress.ps1
> fix(decompress): '$ExtractDir' remove original extract file by accident.

- lib/decompress.ps1
Sorry for this 2nd fix...
For some `extract_dir` in .zip that has sub-dir, the former one would remove parent dir and get error (flac, flac-1.3.2-win\win64), now use temp dir instead. And also fix .msi, in case of some installer that don't have `SourceDir`.
`Expand-DarkArchive` will be used in wix extraction, so it doesn't need `-ExtractDir`.
`Expand-7zipArchive` and `Expand-InnoArchive` works well.
Tested:
- calibre-normal (msi, PFiles\Calibre2)
- flac (zip, flac-1.3.2-win\win64)
- pkg-config (zip, multiple url and extract_dir)
BTW, `Expand-Archive` has `-PassThru` param in PowerShell 6+, and it will be more convinient to support `-ExtractDir` with it. I'll check function's source code and plan to rewrite `Expand-ZipArchive`.
Fix #3473, ref …
> fix(decompress): '$ExtractDir' error with '.zip' and subdir

- bin/checkhashes.ps1
When there were `url` and `architecture` properties. Architecture properties were considered first, which lead to this:
1. arch_specific 64bit => none, fallback to `url` property on root
1. arch_specific 32bit => none, fallback to `url` property on root
1. Resulted in one URL downloaded twice
Before:
After:
> fix(bin): Checkhashes downloading twice when architecture properties does hot have url property

- README.md
Since main bucket has been moved to [ScoopInstaller/Main](https://github.com/ScoopInstaller/Main).
The url of `runat` on `README.md` should change to https://github.com/ScoopInstaller/Main/blob/master/bucket/runat.json 😃
> fix(readme): adjust url of `runat`

- lib/decompress.ps1
ref: https://github.com/lukesampson/scoop/pull/3466#discussion_r288691859
Now `freedownloadmanager`'s `installer.script` should be simplified to (see https://github.com/lukesampson/scoop-extras/pull/2220)
```json
"installer": {
"script": [
"Expand-InnoArchive -Path \"$dir\\$fname\"",
"Expand-InnoArchive -Path \"$dir\\$fname\" -ExtractDir '{code_CefInstallDir}' -Removal"
]
}
```
> feat(compress): Allow 'Expand-InnoArchive -ExtractDir' to accept '{xxx}'

- README.md
- bin/checkhashes.ps1
Opening to master since, it is not invansive and fast fix
I need to be able to run binaries from linux hosts
https://github.com/Ash258/GithubActionsBucketForTesting/runs/153802813
> fix(checkhashes): Do not call scoop directly

- .editorconfig
https://github.com/lukesampson/scoop/blob/1836edba8857373f56a4332dab81a7030a47fe76/.editorconfig#L15
Miss symbol `}`.
> Fix error matching bat and cmd file

- lib/install.ps1
- lib/psmodules.ps1
COMSPEC commands fail when called with unescaped directory arguments which contain white spaces (typically a compound user name).
This PR
- Closes lukesampson/scoop-extras#1781
- Closes lukesampson/scoop-extras#2389
- Closes #2801
> Escape dir vars when calling COMSPEC cmds

- lib/core.ps1
- Also redirect standard error to log file.
- Fix `-RunAs` error.
- `-RunAs` and `-Log` cannot be used together.
> opt(Invoke-ExternalCommand): Small tweak

- lib/help.ps1
- libexec/scoop-help.ps1
Fix command `scoop help` when alias `help` is declared.
When a user has an alias named help, scoop help does not work anymore.
This PR renames the function `help` to `scoop_help` to prevent collision with a user alias.
Steps to reproduce:
```
PS> Set-Alias help Get-Help
PS> scoop help install
help : The term 'local:help' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\Eric\scoop\apps\scoop\current\libexec\scoop-help.ps1:16 char:13
+     $help = help $file
+             ~~~~
+ CategoryInfo          : ObjectNotFound: (local:help:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
Usage: scoop install …
```
> fix help collision

- lib/decompress.ps1
This fixes the error when `extract_dir` contains spaces, such as "ISLC v1.0.1.2"
(encountered in: https://github.com/lukesampson/scoop-extras/pull/2398)
Please let me know if there are any problems. Thanks.
> fix(decompress): fix bugs on extract_dir

- bin/checkver.ps1
- lib/core.ps1
- lib/versions.ps1
- test/Scoop-Versions.Tests.ps1
fix #3329, fix #2981, fix #2720, fix https://github.com/lukesampson/scoop-extras/issues/2106
Now force updating to manifest's version, despite installed version is greater or less than it.
> fix(versions): Refactor `compare_versions` -> `Compare-Version`

- lib/autoupdate.ps1
Now freecad can extract hash as
```
"hash": {
"url": "$url-SHA256.txt",
"regex": "(?sm):\\s+([a-f\\d\\s]+)CertUtil"
}
```
> fix hash with space

- lib/versions.ps1
- test/Scoop-Versions.Tests.ps1
Hotfix for #3333
Fixed out of bounds error for updates like `1.0.0-beta4 -> 1.0.0`, `1.16.0-rc2 -> 1.16.0`, i.e., one is dashed version with alphabet while another is undashed version. (by L63-L70 in `versions.ps1`)
Also make alpha/beta/rc/prev versions lower than vanilla ones, see new test cases in `Scoop-Versions.Tests.ps1`.
> fix(versions): Hotfix for #3333

- lib/install.ps1
Fix #3588 
Use `$version` as old version indicator in `uninstaller`.
> fix(install): Allow $version to be used in uninstaller scripts

- libexec/scoop-uninstall.ps1
- libexec/scoop-update.ps1
Workaround until #2952 is properly implemented.
No more `taskkill` in `uninstall.script`
> fix(uninstall,update): Do not uninstall when application is running

- lib/core.ps1
- lib/install.ps1
- schema.json
- Fix https://github.com/lukesampson/scoop/issues/3609
Just like `url`, `bin`, `shorcuts`, etc.
For MiKTeX that 64bit and 32bit offer different linked bin folder (which needed to be added to `PATH`)
> feat(install): Add arch support to `env_add_path` and `env_set`

- libexec/scoop-uninstall.ps1
- libexec/scoop-update.ps1
Get-process with path on splited `$dir` resolved to `$env:SCOOP\apps` when application installation was broken.
Broken installations have path `$env:SCOOP\apps\<app>\` and splited result in location of all applications.
Since this is just workaround I splitted path twice to check leaf. Every opinon is welcomed. (Maybe `EndsWith` could work 🤔)
> fix(update,uninstall): Regression from get-process workaround

- lib/install.ps1
Example with vim, reduce the time of 67 seconds to 23 seconds
Command for test: 
```ps1
Measure-Command { .\bin\scoop.ps1 update vim -f }
#output
vim: 8.1.1330 -> 8.1.1330
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'vim' (8.1.1330 -> 8.1.1330)
Downloading new version
Loading gvim_8.1.1330_x64.zip from cache.
Checking hash of gvim_8.1.1330_x64.zip ... ok.
Uninstalling 'vim' (8.1.1330)
Unlinking ~\scoop\apps\vim\current
Loading gvim_8.1.1330_x64.zip from cache.
Extracting gvim_8.1.1330_x64.zip ... done.
Linking ~\scoop\apps\vim\current => ~\scoop\apps\vim\8.1.1330
Creating shortcut for gVim (gvim.exe)
'vim' (8.1.1330) was installed successfully!
```
Measure …
> Use 7zip when available for zip file (more fast)

- README.md
- bin/install.ps1
replace
```ps1
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
```
to
```ps1
iwr -useb get.scoop.sh | iex
```
More elegant, isn't it?
> Shorter installation command

- index.md
replace
```ps1
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
```
to
```ps1
iwr -useb get.scoop.sh | iex
```
More elegant, isn't it?
> docs(gh-pages): Improve installation instructions

- lib/buckets.ps1
IntelliJ is putting a project file in the `buckets` folder when setting up a project there. The bucket lookup then tries to open this as a folder as it lacks directory filter.
> only lookup directories in buckets folder

- libexec/scoop-info.ps1
Before:
```
> scoop info firefox-beta
...
Binaries:
firefox.exe firefox-beta
```
Now:
```
> scoop info firefox-beta
...
Binaries:
firefox-beta.exe
```
> fix scoop info Binaries output

- lib/install.ps1
While working on Actions I encounter problem with aria2 downloading. I can pretty simply [override function `Get-AppFilePath`](https://github.com/Ash258/Scoop-GithubActions/blob/08a2765fc4eb31f380bdefce28251c8b280d3dd0/Entrypoint.ps1#L815-L833) without problem so I can feed it with whatever I want to get correct path, but Aria2 is having problems with mixing `\` and `/`
https://github.com/Ash258/Scoop-GithubActions/issues/38#issuecomment-513490329
https://github.com/Ash258/Scoop-GithubActions/issues/38#issuecomment-513490551
> fix(install): Use Join-Path instead of string gluing.

- bin/checkurls.ps1
Prevent 40x response.
**Before:**
```
Desktop main (master)
$ .\bin\checkurls.ps1 -app apktool
[U]RLs
| [O]kay
|  | [F]ailed
|  |  |
[1][0][1] apktool
> The remote server returned an error: (403) Forbidden. (https://github.com/iBotPeaches/Apktool/releases/download/v2.4.0/apktool_2.4.0.jar#/apktool.jar)
```
**After:**
```
Desktop main (master)
$ .\bin\checkurls.ps1 -app apktool
[U]RLs
| [O]kay
|  | [F]ailed
|  |  |
[1][1][0] apktool
```
> fix(checkurls): Trim renaming suffix in url

- lib/autoupdate.ps1
Firefox, Thunderbird and uget can benefit.
> fix(autoupdate): Decode basename when extract hash

- lib/manifest.ps1
[intptr]::size is 4 in powershell x86 on 64bit system.
> fix(core): Use [Environment]::Is64BitOperatingSystem instead of [intptr]::size

- libexec/scoop-list.ps1
Always display bucket name of installed apps, even main bucket. The list should be more **explicit** by keeping the main bucket name.
The main bucket has been separated into an independent repository. It should be treated the same as other buckets.
> feat(list): Display main bucket name

- lib/git.ps1
Hello,
in my global gitconfig, the option `pull.rebase` is set to `interactive`.
This means that whenever I `git pull`, the editor starts up asking me about rebasing my local branch.
While this functionality is questionable, it exists, and it means that whenever I try to install something with scoop, the editor pops up twice (update scoop and update the package list).
This is mildly annoying, so I fixed it locally by setting the option on the two repositories to `false`, which works.
This PR would fix the issue for everyone (included - or maybe limited to :D - myself in the future).
> fix(git): enforce pull without rebase

- libexec/scoop-info.ps1
When bucket is specified, check if the installed app belong to the same bucket. If app is not installed from the specified bucket, output `Installed: No`
Also fix another bug. When an app hash is wrong there is no manifest.json in app directory. So `$install.bucket` is none. `Find-BucketDirectory` will return main bucket path as default and `manifest_path` will return a wrong path.
> fix(scoop-info): check bucket of installed app

- lib/manifest.ps1
- Closes #3770
Configuration name is subject of change. I am following dash notation for naming, until config is reworked and united (Related #3401)
~~Is boolean enough or it is prefered to go with `scoop config 'default-architecture' '32bit|64bit'` which could be more suitable for additional arch support (arm for example)~~
> feat: Add configuration option for default architecture

- lib/diagnostic.ps1
- libexec/scoop-checkup.ps1
related: https://github.com/h404bi/dorado/issues/78
> feat(checkup): Add check_envs_requirements

- lib/install.ps1
Fix https://github.com/ScoopInstaller/Main/issues/642
This was caused by https://github.com/lukesampson/scoop/blob/cb2ff446e6a3b5367db7ed85c284ac083fd5f450/lib/install.ps1#L603, should be `return $true`... Replace the `failed` function with single line.
> fix(install): fix wrong output of 'install/failed'

- lib/install.ps1
:bangbang: HOTFIX :bangbang:
Sorry, /cc @r15ch13 @Ash258 
Fix #3866 
```
λ  scoop uninstall 7zip-zstd                                                                     
Uninstalling '7zip-zstd' (19.00-v1.4.4-R1).                                                      
Removing shim for '7z'.                                                                          
Removing shim for '7zG'.                                                                         
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\7-Zip.lnk   
Unlinking ~\scoop\apps\7zip-zstd\current                                                         
'7zip-zstd' was uninstalled.                                                                     
λ  rm .\scoop\apps\7zip\* -Force
λ …
```
> fix(install): fix 'failed' function

- lib/install.ps1
In some cases, such as when an HTTPS URL redirects to an HTTP URL, the `HTTPWebRequest` client may not follow 302 error codes. This change explicitly catches that error, and attempts to find another URL for the same file in the body of the 302 response.
This specifically fixes the error when installing or updating [Krita](https://github.com/lukesampson/scoop-extras/blob/master/bucket/krita.json) (from the extras bucket), which has an HTTPS download URL that can redirect to HTTP mirrors.
Closes https://github.com/lukesampson/scoop/issues/3886
Closes https://github.com/lukesampson/scoop/issues/3535
Closes https://github.com/lukesampson/scoop-extras/issues/2728
Closes https://github.com/lukesampson/scoop-extras/issues/2932
Replaces https://github.com/lukesampson/scoop-extras/pull/2933
> feat(install): Follow HTTP redirections when downloading a file

- bin/checkver.ps1
- schema.json
Related #3869
This is usefull when vendors provide complex webpages/requires specific request method / have webpage encoded / or you just want to create simplier structure for matching
I want to keep it simple and support the functionality of matching, so the script should always return the string, which represent the actual page.
Examples:
```json
{
"version": "8.0.3-1",
"homepage": "https://www.swi-prolog.org",
"description": "Comprehensive Prolog environment",
"license": "MIT",
"architecture": {
"64bit": {
"url": "https://www.swi-prolog.org/download/stable/bin/swipl-8.0.3-1.x64.exe#/dl.7z",
"hash": "f3b4783dd05a746219600185e8404238ee451708f3512c601a2c99cf549b0fa5"
},
"32bit": {
"url": "https://www.swi-prolog.org/download/stable/bin/swipl-8.0.3-1.x86.exe#/dl.7z",
"hash": …
```
> feat(checkver): Present script property

- bin/scoop.ps1
which was introduced in #3419
I think it can be removed at this moment.
> chore(scoop): Remove temporary code from the scoop executable

- lib/install.ps1
Close https://github.com/lukesampson/scoop/issues/3960
Do not send referer to portableapps.com.
There are still many software hosted in https://download3.portableapps.com
> core(install): Readd "Don't send referer to portableapps.com"

- lib/install.ps1
Fix https://github.com/lukesampson/scoop/issues/3785
> fix(install): let pathes in 'env_add_path' be added ascendantly

- libexec/scoop-update.ps1
- Removes old depreciation warning for PS5
- fixes broken link for instructions on how to install PowerShell
> chore(update): Update outdated PowerShell 5 warning

- lib/git.ps1
The way the current code works is that it has side effects when trying to execute a git command.
(This comes from the file git.ps1 in the lib directory).
(i.e current code
& "$env:COMSPEC" /c $cmd
)
Without the /d parameter, it also executes code that is in the windows autostart sections of the registry. 
HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun
and/or
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
by adding the /d switch
& "$env:COMSPEC" /d /c $cmd
no extra autorun programs will be executed.
Normally, this does not have any adverse effects (it is just possibly slower), however, if there is an error in the autostart entries, it ends up returning errors to scoop that get interpreted incorrectly. In my case, I also had invalid entries left in the …
> fix(git): Don't execute autostart programs when executing git commands

- test/bin/init.ps1
- Closes lukesampson/scoop-extras#4200
- Closes #4027
Full rework of tests needs to be done to fully adapt v5, but this should make Ci usable again for time being.
Master branch target is intended.
Pipeline failing due to bug in PSScriptAnalyzer PowerShell/PSScriptAnalyzer#1472
> fix(tests): Force pester v4

- lib/install.ps1
I do not remember exact example, but sometimes there is possible the value is negative. Most likely if the terminal is too narrow, which lead to `' ' * -10` and out of range error.
> fix(install): Aria2 inline progress negative values

- lib/core.ps1
- Closes lukesampson/scoop-extras#4249
- Closes lukesampson/scoop-extras#4152
- Closes lukesampson/scoop-extras#4157
- Closes #4050
Have no idea why is it needed now.
Please test Excavator and normal execution
Before
After
It should work in Excavator:
> fix(core): Fosshub download

- lib/core.ps1
get_shim_path return a list `[$ture, $shim_path]` when shim is default. Use `Break` instead.
> fix get_shim_path

- libexec/scoop-reset.ps1
The issue is the same as for #2952, workaround until the proper
solution is implemented. The code is also directly copied from there.
Fixes #4310
> reset: skip when app instance is running

- lib/depends.ps1
- lib/install.ps1
Pansies, a popular PowerShell module, creates an alias from `url` to its [`New-Hyperlink`](https://github.com/PoshCode/Pansies/blob/master/Source/Assembly/Commands/NewHyperlinkCommand.cs) function. This conflicts with usages of the `url` function in [`./lib/manifest.ps1`](https://github.com/lukesampson/scoop/blob/master/lib/manifest.ps1#L114).
This PR specifies the scopes of those usages to the script level so those usages can find the function in the scoop library.
Fixes https://github.com/lukesampson/scoop/issues/4185
> Change `url()` scope to avoid conflict with global aliases (e.g. Pansies)

- bin/checkver.ps1
- lib/autoupdate.ps1
- lib/core.ps1
- lib/manifest.ps1
- schema.json
Inherit #2803 
If hash extraction is different for urls, use array of objects. If hash extraction array's length is less then autoupdate.url's length, latest hash item is reused for the rest.
<details>
<summary>Example Manifest (irfanview)</summary>
```json
{
"version": "4.53",
"license": {
"identifier": "Freeware",
"url": "https://www.irfanview.com/eula.htm"
},
"homepage": "https://www.irfanview.com/",
"architecture": {
"64bit": {
"url": [
"https://www.irfanview.info/files/iview453_x64.zip",
"https://www.irfanview.info/files/iview453_plugins_x64.zip"
],
"hash": [
"941056da4f50df44eeef46ca875255bd3d09c3aaf1bdfffad5f65de0a515ff02",
"d5e8ae1734264287e7b442fc062899c206c54bbd423304e125c4b1d1c58d28b1"
],
"shortcuts": [
[
"i_view64.exe",
"IrfanView"
]
],
"bin": [
[
"i_view64.exe",
"irfanview"
] …
```
> feat(autoupdate): add multiple URL/hash/extract_dir... support for autoupdate

- libexec/scoop-prefix.ps1
Unused imports removed:-
1. manifest.ps1
2. buckets.ps1
Unused function removed:-
1. reset_aliases:- We do not use aliases here.
Load when required
1. help needs to be loaded only when app is not specified
2. core needs to be loaded only when app is specified
Gains:-
1. Improved speed.
> feat(scoop-prefix): remove unused imports and functions

- index.md
This is a small change, but I think it would make a big difference. Most websites like this tend to have the installation instructions immediately visible to the user's eyes, because people today have short attention spans and are quick to enter the first thing they see into a terminal. All your fave CLI apps have web pages that tell you how to install them immediately, but for scoop you have to scroll down. So I think it would be much better like this. Thanks so much for this amazing package manager that keeps me sane.
> gh-pages: move installation guide to top

- README.md
- libexec/scoop-install.ps1
- libexec/scoop-update.ps1
Adds a new config value: `aria2-warning-enabled` (default: true). 
Normally a warning is emitted when running `scoop install` or `scoop install` while `aria2-enabled` is set to true. When `aria2-warning-enabled` is set to false, the warning is suppressed. 
I also added documentation about this new config to the Readme and the warning itself, though I don't know if this might be considered to be cluttering the output even more.
Closes #2482 and the comment on #2479.
> feat(message):  Add config to disable aria2 warning message

- libexec/scoop-install.ps1
- Close #4058
Automatically uninstall previous failed installation when detected, rather then give an error and let user do uninstallation manually.
> fix(scoop-install.ps1): Auto uninstall previous failed installation

- lib/autoupdate.ps1
- lib/core.ps1
Hotfix for #3518, support updating array of arrays correctly.
<details>
<summary>GIMP - autoupdate `bin` and `shortcuts`</summary>
```json
{
"version": "2.10.28",
"description": "GNU Image Manipulation Program",
"homepage": "https://www.gimp.org",
"license": "GPL-3.0-only",
"url": "https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.28-setup.exe",
"hash": "2c2e081ce541682be1abdd8bc6df13768ad9482d68000b4a7a60c764d6cec74e",
"innosetup": true,
"installer": {
"script": [
"Push-Location \"$dir\"",
"Get-ChildItem -Filter '*.debug' -Recurse | Remove-Item -Recurse",
"if ($architecture -eq '64bit') {",
"   Rename-Item 'lib\\gimp\\2.0\\plug-ins\\twain\\twain,3.exe' 'twain.exe'",
"   Remove-Item 'lib\\gimp\\2.0\\plug-ins\\twain\\twain,1.exe'",
"   Get-ChildItem -Filter '*,1*' -Recurse …
```
> fix(autoupdate): Update array of arrays correctly

- libexec/scoop-update.ps1
Bash will parse the '*' on the shell level which results in a strange experience for everyone not familiar with it when trying to update all packages.
This adds -a and --all as alternatives.
> Add flags as an alternative to '*' to update all

- README.md
This better reflect the actual contents of the bucket, rather than just a list of JDKs that varies over time.
> readme: Update Java bucket text

- libexec/scoop-update.ps1
Fixes #4530 
I misunderstood how `:` acts in `getopt`. I have removed it entirely, I assume that the `-q` parameter was also not supposed to get an argument. The error on `-q` was introduced with #2260.
> fix(scoop-update): Fix scoop update -a requiring arguments

- bin/checkver.ps1
- lib/json.ps1
1. Extract multiple versions
2. Reverse versions, especially if regex is absent
3. Support returning single value even if multiple versions were found
This is probably required with regex mode on
4. Simplify data extraction using JValue over JObject/JArray combination. Saves a few function calls
> feat(checkver): improve JSONPath extraction support

- schema.json
- Fix #2454
- Close #2456
- Also make `description`, `homepage` and `license` properties required.
> feat(schema): Enable autoupdate for 'license'

- libexec/scoop-cat.ps1
This will add a command `cat`, which prints the manifest of an app.
Similar pull request: #4272
> Add scoop cat command

- lib/core.ps1
- lib/install.ps1
- libexec/scoop-which.ps1
- test/Scoop-Core.Tests.ps1
The .ps1 shims are now only created when the bin entry itself is a .ps1 script.
Closes #3749 
Closes #2018 
Closes #4486 
Closes #3850
Closes #3795
Closes #4003
Closes #3890
Closes #4216
Closes #4473
Closes #3699
Closes #4413
Closes #4545
Closes #3851
Closes #4333
Closes #3877
Closes #4376
> feat(shim): Rework shimming logic

- lib/core.ps1
`pwsh` has different argument parsing rules than `powershell`, so we need to specify the -Command parameter.
> feat(shim): ps1 shim hotfix

- bin/checkver.ps1
Blocker for https://github.com/ScoopInstaller/Main/pull/2871
This is intentionally targeted to `master`, because this is an essential fix.
Relates to first part of https://github.com/ScoopInstaller/Main/pull/2871#issuecomment-984977671. I will look at rate-limiting headers some other time. For now, this works fine.
How I tested this:
- Ran checkver on Extras bucket: I get "Too many requests" error for around 450 manifests
- Declared an environment variable $Env:SCOOP_CHECKVER_TOKEN
- Ran checkver on Extras bucket: No errors this time
> fix(checkver): Use GitHub token from environment

- lib/install.ps1
Closes https://github.com/lukesampson/scoop/issues/2735
> Show manifest on installation

- lib/core.ps1
- libexec/scoop-alias.ps1
- libexec/scoop-create.ps1
In PowerShell 5, `Out-File -Encoding UTF8` will produce an UTF-BOM file, which may cause some error.
`Out-File -Encoding ASCII` produces UTF file in fact, so 'cos Scoop support PS5, using ASCII encoding is better.
Also some file formatting.
> fix(core): Use '-Encoding ASCII' in 'Out-File'

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Targeting this to master as templates will work only from there.
Closes #4001
> chore: Add issue/PR templates

- lib/install.ps1
Portableapps.com has switched back to hosting freeware under their own download3.portableapps.com mirror.
> install.ps1: Add portableapps.com to strip_filename skips

- lib/diagnostic.ps1
> Check Windows version for LongPaths

- lib/core.ps1
Since the `.` has a special meaning in regex, in needs to be escaped.  Since there is all characters matching (`.*`) just ahead of it, it is safe to assume that author wanted to have the `.json` and not `<any character>json`.
> fix(core): Escape '.' in 'parse_app()'.

- lib/core.ps1
- lib/decompress.ps1
After we added error log in 7zip.log (#4570), nested archive extraction by 7-zip had been broken... This PR fix it.
Besides, output and error logs have some encoding error as in https://github.com/ScoopInstaller/Scoop/issues/4569, and change encoding to `Default` solve my problem (CP936, in PS 7 and PS 5), please test it in different codepage and PowerShell version.
> fix(decompress): Fix 'Expand-7zipArchive()' for nested archive

- lib/install.ps1
Don't show manifest while 'scoop update` (https://github.com/ScoopInstaller/Scoop/pull/4155#issuecomment-993554265)
> fix(install): Don't show manifest while updating

- README.md
- libexec/scoop-config.ps1
> chore(config): Document all configuration options

- CHANGELOG.md
- test/00-Project.Tests.ps1
- test/Import-Bucket-Tests.ps1
- test/Import-File-Tests.ps1
- test/Scoop-Alias.Tests.ps1
- test/Scoop-Config.Tests.ps1
- test/Scoop-Core.Tests.ps1
- test/Scoop-Format-Manifest.Tests.ps1
- test/Scoop-GetOpts.Tests.ps1
- test/Scoop-Install.Tests.ps1
- test/Scoop-Linting.Tests.ps1
- test/Scoop-Manifest.Tests.ps1
- test/Scoop-TestLib.ps1
- test/bin/init.ps1
Format scripts in `test` folder by VS Code's PowerShell extension
This is a pure styling one, and there're some test errors that are not fixed in this PR. They will be fixed later.
Not suitable.
> style(test): Format scripts by VSCode's PowerShell extension

- CHANGELOG.md
- libexec/scoop-prefix.ps1
- schema.json
- test/bin/test.ps1
Only produce test result file while run by CI and fix two styling failure.
When run `test\bin\test.ps1` locally, it will produce `TestResults.xml` file and give a failure on next run.
Also fix duplicate `license` item in `schema.json` and trailing space in `libexec\scoop-prefix.ps1`
Running `test\bin\test.ps1`
Before:
After:
> test(test-bin): Only write output file in CI and fix trailing whitespaces

- CHANGELOG.md
- lib/core.ps1
Fix PS1 shim's content switch, change from `^(.\\[\w]:).*$` to `^(\.\\)?\w:.*$`. Also enclose shim content with @() for a clear look.
PS1 shim went wrong in PowerShell 7 if target is in a different drive other than shim dir. This is introduced by `Resolve-Path -Relative` cmdlet's output.
In PS5:
In PS7:
Other changes are pure refactoring (enclosed raw code in `@()`)
Run `Invoke-Pester ".\test\Scoop-Core.Tests.ps1"`
Before:
After:
> fix(shim): Fix PS1 shim error when in different drive in PS7

- CHANGELOG.md
- bin/test.ps1
- test/00-Project.Tests.ps1
- test/Import-Bucket-Tests.ps1
- test/Scoop-Manifest.Tests.ps1
- test/bin/test.ps1
Skip manifests test since there is no `bucket` directory in scoop core.
`bin\test.ps1` is now an alias to `test\bin\test.ps1`
Before:
After:
> test(manifest): Fix manifests validation

- CHANGELOG.md
- lib/core.ps1
Save config file with `Default` encoding.
Relates to #4629
If users use Unicode characters in `scoop config` command, these characters will not be saved to config file
Before:
After:
> fix(config): Allow `scoop config` use Unicode characters

- lib/diagnostic.ps1
Changed lib\diagnostic.ps1 to specify `sudo` on the Set-ItemProperty call as it won't work without elevated privileges. Also added the line that follows the other sudos about needing to install sudo if you don't have it.
> added sudo to Set-ItemProperty incl note about sudo

- CHANGELOG.md
- bin/checkver.ps1
> build(checkver): Fix output with '-Version'

- CHANGELOG.md
- libexec/scoop-download.ps1
Useful for:
- **Users:** to pre-populate the cache:
- in case they need to install something later (i.e. no internet scenario)
- in case they want to inspect the installer/archive for an application (without installing)
- **Maintainers:** to manually verify:
- hash check failures
- 404 errors (e.g. with aria2, sourceforge etc.)
The second scenario is perhaps the most useful personally because many people open issues about download failures, but I don't really want to install the particular app. So I can just do `scoop download <app>` to rectify the issue.
Closes #1804
Relates to #2293
1. Simple test: 
2. Above test with pre-filled cache: 
3. Test 1 with 32bit download: 
4. Test 3 with skipping hash check: 
5. Test 4 with force download (overwrite cache): 
6. Test with one app with …
> feat(download): Allow downloading without installing

- CHANGELOG.md
- lib/core.ps1
`&>` is bash operator, not sh.
shell file must end with `\n`.
see: 
- https://unix.stackexchange.com/questions/641042/sh-shell-redirect-output-to-both-terminal-and-file-inside-script
- https://www.freebsd.org/cgi/man.cgi?sh
Before:
After:
> fix(shim): Fix `sh` shim error in WSL

- CHANGELOG.md
- lib/decompress.ps1
`Split-Path` in PowerShell 5 don't have `LeafBase` switch, so changed `Split-Path $Path -LeafBase` to `strip_ext (fname $Path)`.
Relates to #4608
Tested by `.\test\bin\test.ps1` in PowerShell 5.1
> fix(decompress): Fix `Split-Path -LeafBase` in PS5

- CHANGELOG.md
- lib/core.ps1
- lib/decompress.ps1
- lib/depends.ps1
- lib/install.ps1
- libexec/scoop-depends.ps1
- libexec/scoop-install.ps1
- libexec/scoop-update.ps1
- libexec/scoop-virustotal.ps1
- test/Scoop-Decompress.Tests.ps1
- test/Scoop-Depends.Tests.ps1
- test/fixtures/format/formated/4-script-block.json
- test/fixtures/format/unformated/4-script-block.json
Refactor Scoop's dependencies resolving functions, and fix some dependencies error
- Closes #3700
- Relates to #3502
Commits are organized as following:
- Remove unused code, i.e., `extract_7zip()`, `extract_msi()`, `extract_zip()`, `unpack_inno()` and zip extraction code that before PowerShell 5
- Simplify `Test-xxxRequirement()` that only one type of param is allowed and add tests
- Refactor `script_deps()` and `install_deps()` to `Get-InstallationHelper()` and add tests (fix #3700 in this step)
- Remove naïve function `runtime_deps()` (wrapper of `$manifest.depends`)
- Refactor `dep_resolve()` to `Get-Dependency()`
- Remove `install_order()` and `deps()` with direct call of `Get-Dependency()`
- Refactor code that introduced in #3685 (move some lines of code to make them more readable) …
> refactor(deps): Rewrite 'depends.ps1'

- CHANGELOG.md
- lib/core.ps1
- Check if `NO_JUNCTIONS` is set
- set: use current version
- unset: use `current`
- Check if there is `install.json` file in versioned directory
Closes #4648
Before:
After:
~- [ ] I have updated the tests accordingly.~
> fix(installed): Fix 'core/installed' that mark failed app as 'installed'

- CHANGELOG.md
- appveyor.yml
- test/Scoop-Decompress.Tests.ps1
- test/bin/init.ps1
- test/bin/test.ps1
Fix Appveyor error caused by wrong `zstd.exe` extraction.
- Update `zstd` to v1.5.1 and change its 7z extraction param (This is why CI cannot find `zstd`)
- Fix `Mock` function in zstd test cases (This is why nested zstd test fails)
- Some unrelated tweaks
- Install helper and set EnvVars on demand (Move from `init.ps1` to `test.ps1`)
- Move helper EnvVars from `appveyor.yml` to `test.ps1`
- ~Change condition of `Mock Get-AppFilePath` to `CI_WINDOWS` so developers could simulate test in CI by setting `$env:CI_WINDOWS = $true` and modifying the helper downloading part of `test.ps1` file~
Relates tohttps://github.com/ScoopInstaller/Scoop/pull/4608#issuecomment-1011022366
https://ci.appveyor.com/project/niheaven/scoop/builds/42177522/job/l8b7kyla9deyiohx
> test(zstd): Fix 'zstd' extraction error in test

- CHANGELOG.md
- libexec/scoop-update.ps1
Skip updating not-git buckets.
Closes #4019
Closes #4668
> fix(scoop-update): Skip updating non git buckets

- CHANGELOG.md
- libexec/scoop-cleanup.ps1
It will remove all subdir except for `current` and its target version.
Closes #4663
Before:
After:
> fix(cleanup): Remove apps other than current version

- CHANGELOG.md
- lib/depends.ps1
- test/Scoop-Depends.Tests.ps1
#4638 changes some logic of installing and updating, and `Get-Dependency()` trimmed bucket from app's name (e.g., `versions/7zip-zstd` -> `7zip-zstd`), this introduces some bug when user installs some apps that duplicated with known buckets.
This PR keeps bucket name with app name while resolving dependencies, so the installation won't be confused.
Besides, #4638 may breaks #4595, and no URL bug is fixed again by allow $null in `Test-xxxRequirement()` functions.
Closes #4662
> fix(depends): Keep bucket in 'Get-Dependency()'

- CHANGELOG.md
- schema.json
Typo in #3518
Relates to #3518
> build(schema): Fix typo ('note' -> 'notes')

- .github/workflows/ci.yml
- CHANGELOG.md
Since PR is required, it needn't run tests when pushing a new branch.
Relates to https://github.com/ScoopInstaller/Scoop/pull/4671#issuecomment-1014831421
> build(ci): Disable CI test on 'push'

- CHANGELOG.md
- lib/versions.ps1
A bug in `versions/Select-CurrentVersion()`, when there is and only is a single version dir under appdir (should be caused by failure uninstallation), the function got wrong version number.
Relates to #3721
Before:
After:
> fix(versions): Fix wrong version number when only one version dir

- CHANGELOG.md
- lib/core.ps1
- lib/install.ps1
- lib/versions.ps1
- libexec/scoop-cleanup.ps1
- libexec/scoop-hold.ps1
- libexec/scoop-install.ps1
- libexec/scoop-unhold.ps1
- libexec/scoop-uninstall.ps1
- libexec/scoop-update.ps1
- Let `core/Confirm-InstallationStatus()` marks failed installation and give a warning
- Let `scoop-cleanup` correctly cleanup failed installation
- Simplify `core/installed()` and `install/failed()` (oh xxxx these two paired functions even are not in same file! Move them to `core`)
- Remove `scoop-install/is_installed()` and move its functionality into main file
- Some minor style fixes
Closes #4674
Relates to #4650
Just as #4674
```powershell
scoop install tests\meson.json
scoop list meson
scoop cleanup *
scoop list meson
scoop install tests\meson.json
scoop list meson
scoop install meson.json
scoop list meson
ls (scoop prefix meson) | findstr 'FAILED_INSTALLATION'
```
> fix(install-status): Correctly handle failed installation of apps

- CHANGELOG.md
- test/Scoop-Decompress.Tests.ps1
#4676 refactor `installed()` by using `Select-CurrentVersion()` so import `versions.ps1` in `Scoop-Decompress.Tests.ps1`
Relates to #4676
Before:
After:
> test(decompress): Import 'versions.ps1'

- CHANGELOG.md
- lib/install.ps1
- lib/psmodules.ps1
- `mklink /j` -> `New-Item -ItemType Junction`
- `mklink /h` -> `New-Item -ItemType HardLink`
Relates to https://github.com/ScoopInstaller/Scoop/pull/4687#issuecomment-1021214702
> refactor(mklink): Use 'New-Item' instead of 'mklink'

- CHANGELOG.md
- lib/install.ps1
Junction is copied as native folder when we copy `apps` folder, and this may break scoop's `reset`, `uninstall`, `cleanup` actions. Use `Remove-Item -Recure` could fix this bug.
```pwsh
❯ Copy-Item D:\Scoop\apps\ag D:\ -Recurse
❯ scoop uninstall ag
Uninstalling 'ag' (2.2.5).
Removing shim 'ag.exe'.
Removing shim 'ag.shim'.
Unlinking D:\Scoop\apps\ag\current
'ag' was uninstalled.
❯ Move-Item D:\ag D:\Scoop\apps
❯ scoop prefix ag
D:\Scoop\apps\ag\current
❯ (Get-Item D:\Scoop\apps\ag\current).GetType()
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    DirectoryInfo                            System.IO.FileSystemInfo
❯ scoop reset ag
```
Before:
```pwsh
❯ (Get-Item …
```
> fix(current): Remove 'current' while it's not a junction

- CHANGELOG.md
- lib/diagnostic.ps1
- lib/git.ps1
- libexec/scoop-checkup.ps1
It is possible that COMSPEC is undefined/empty, or some people even set it to powershell instead of cmd (extremely dangerous). 
We only use COMSPEC in one place now, in lib/git.ps1, so I replaced that with the actual binary name (which will always exist).
Also removed the function which tested COMSPEC's existence.
Closes #3845
No functional changes, so not tested.
> refactor(COMSPEC): Deprecate use of subshell cmd.exe

- CHANGELOG.md
- bin/scoop.ps1
- lib/buckets.ps1
- lib/git.ps1
- libexec/scoop-bucket.ps1
- libexec/scoop-status.ps1
- libexec/scoop-update.ps1
no longer using `Push-Location` to change work directory before executing git operations
Fixes #4358 
Fixes #4675
send ^C(SIGINT) will change current directory to bucket path, when scoop is updating buckets.
solve:
using command options `-C` to specify the work directory for git, then no longer need to change the \<work directory> with `Push-Location` and `Pop-Location`.
before:
```
PS C:\Users\WDAGUtilityAccount> scoop update
Updating Scoop...
Updating 'main' bucket...
^C
PS C:\Users\WDAGUtilityAccount\scoop\buckets\main>
```
after:
```
PS C:\Users\WDAGUtilityAccount> scoop update
Updating Scoop...
Updating 'main' bucket...
^C
PS C:\Users\WDAGUtilityAccount>
```
tested on PS 5.1 and PS Core 7.2 in sandbox, the changes will not affect other areas.
> refactor(git): Use 'git -C' to specify the work directory instead of 'Push-Location'/'Pop-Location'

- CHANGELOG.md
- lib/diagnostic.ps1
- libexec/scoop-checkup.ps1
- Skip `check_windows_defender` when have not admin privileges
- Separate defender issues($defenderIssues), mark as performance problem instead potential problem
- Add a security tips (display when defender issues are found)
- Skip check for ExclusionPath, if defender realtime protect is disabled (there no way to distinguish between temporary and permanen disable, for now)
- Downgrade `check_windows_defender` checks output from `WARN` to `INFO` (it may also be an Upgrade, in some views)
Closes #4098
Relates to #4591 #4551
```
> scoop checkup
No problems identified!
> sudo scoop checkup
INFO  Windows Defender may slow down or disrupt installs with realtime scanning.
Consider running:
sudo Add-MpPreference -ExclusionPath 'C:\Users\HUMOR\scoop'
(Requires 'sudo' command. Run 'scoop install …
```
> refactor(diagnostic,scoop-checkup): Improvements for 'check_windows_defender' and 'scoop-checkup'

- CHANGELOG.md
- lib/autoupdate.ps1
Rename variable from "$response" to "$res"
> fix(autoupdate): rename $response to $res

- CHANGELOG.md
- libexec/scoop-bucket.ps1
show detailed list for buckets.
this is a missing part of `scoop-bucket`, IMO
**before**
```
> scoop bucket list
1ocal
extras
java
main
nuke
tests
versions
```
**after**
```
> scoop bucket list
Name     Source                                     Updated             Manifests
----     ------                                     -------             ---------
1ocal    ~\scoop\buckets\1ocal                      2022-02-02 17:58:02         3
extras   git@github.com:ScoopInstaller/Extras.git   2022-02-03 00:43:11      1380
java     git@github.com:ScoopInstaller/Java.git     2022-02-02 09:58:43       215
main     git@github.com:ScoopInstaller/Main.git     2022-02-02 16:29:48       971
nuke     git@github.com:HUMORCE/nuke.git            2022-02-02 12:09:58       107
tests …
```
> feat(scoop-bucket): List more detailed information for buckets

- CHANGELOG.md
- lib/core.ps1
See https://github.com/ScoopInstaller/Scoop/pull/4718#issuecomment-1031681710
> refactor(shim): Use `-file` instead of `-command` in ps1 script shims

- CHANGELOG.md
- libexec/scoop-list.ps1
Return PSObject instead of printing to terminal.
Allows manipulation, sorting etc. of the list with the help of PowerShell's pipelines.
Closes #3162
Closes #4138
Closes #4179
Homebrew-style output:
Filter apps from a bucket:
> refactor(scoop-list): Allow list manipulation

- CHANGELOG.md
- lib/core.ps1
- lib/install.ps1
- lib/versions.ps1
- libexec/scoop-install.ps1
- libexec/scoop-list.ps1
- libexec/scoop-update.ps1
This PR changes some UX after https://github.com/ScoopInstaller/Scoop/pull/3721, which cause `scoop reset <app>` not works as before (some use cases that I missed)
- `lib\versions.ps1`: `Select-CurrentVersion()` now get version from `current` folder or latest installed version
- `lib\install.ps1`: `ensure_none_failed()` just reset failed app if it is installed successfully before
- `lib\core.ps1`: `failed()` could figure out failed installation with new `Select-CurrentVersion()` function
- `libexec\scoop-list.ps1`: Correctly mark failed app
- `libexec\scoop-install.ps1`: Use `ensure_none_failed()` before installing apps
- `libexec\scoop-update.ps1`: Use `ensure_none_failed()` before updating apps
- Fixes #4573
- Fixes #4684
- Relates to …
> fix(versions): Get current version from failed installation if possible

- CHANGELOG.md
- lib/install.ps1
- libexec/scoop-update.ps1
Hotfix for #4720
If `Get-Dependency()` output `$null`, `(Get-Dependency $app $architecture) -ne $app` gives `$false` while `@(Get-Dependency $app $architecture) -ne $app` gives `$null` which is needed to `ensure_none_failed()`
Also some small fixes.
Relates to #4720
Before:
After:
> fix(scoop-update): Enforce $null array

- CHANGELOG.md
- lib/install.ps1
Hotfix for #4713, stop output wrong message when there is no processes.
> fix(test-running-process): Fix wrong output

- CHANGELOG.md
- libexec/scoop-alias.ps1
Initial empty alias config entries with `PSObject`
- Fixes #3528
- Fixes #4064
- Fixes #4126
- Fixes #4652
> fix(scoop-alias): Fix alias initialization

- CHANGELOG.md
- libexec/scoop-cache.ps1
- Allow passing multiple apps to `scoop cache show` and `scoop cache rm`. 
- Show what is being deleted.
- Show summary of deleted items (count, size).
Closes #3904
> feat(scoop-cache): Handle multiple apps, show more information

- CHANGELOG.md
- bin/scoop.ps1
- libexec/scoop-info.ps1
`scoop-info` was already using Write-Output. This PR just wraps that output in a PSCustomObject.
Closes #4475
> refactor(scoop-info): Use List View for output

- libexec/scoop-info.ps1
> fix(scoop-info): Use pipe to separate bins

- CHANGELOG.md
- lib/core.ps1
- lib/manifest.ps1
- libexec/scoop-config.ps1
Config variables are quite messy. Here are a couple of fixes.
> refactor(scoop-config): Use underscores everywhere

- CHANGELOG.md
- libexec/scoop-bucket.ps1
> fix(scoop-bucket): Check for git before running command

- CHANGELOG.md
- libexec/scoop-bucket.ps1
- libexec/scoop-status.ps1
Relates to https://github.com/ScoopInstaller/Scoop/pull/4756
> fix(scoop-bucket): Fix date formatting issues with git bucket(s)

- CHANGELOG.md
- libexec/scoop-info.ps1
MASSIVE new changes in scoop-info!!!
Show a lot more information, and hide sensitive details behind the 'verbose' flag.
Check the commit messages for more details.
Closes #4448
> feat(scoop-info): Revamp details and show more information

- CHANGELOG.md
- libexec/scoop-cleanup.ps1
`scoop-cleanup` doesn't use `$manifest`
> fix(cleanup): Hotfix for #4681

- CHANGELOG.md
- lib/core.ps1
Enclose app path with double quotes to fix bug while app path has white spaces.
Closes #4728
Only occurred in exe shims, hard to test.
> fix(shim): Fix shim when app path has white spaces

- CHANGELOG.md
- libexec/scoop-config.ps1
Show all configuration options at once.
Closes #4154
> feat(scoop-config): Show all settings

- .github/workflows/ci.yml
- CHANGELOG.md
- test/bin/init.ps1
- test/bin/test.ps1
Use ~https://github.com/actions/cache~ https://github.com/potatoqualitee/psmodulecache to cache PowerShell modules in GitHub Actions. (Really not happy while working with https://github.com/actions/cache)
PowerShell modules installation is the most time-consuming step of CI test, this fix tries to skip them.
It also skips modules installation if there're ones.
~I don't find an effective way to test the PR, but it seems to work~
~From CI results below, it found cache, but doesn't use them. Maybe a little more tweak are needed.~
Use https://github.com/potatoqualitee/psmodulecache to cache PowerShell Modules, it works fine as this PR's two commits.
> build(ci): Use cache in GitHub Actions

- CHANGELOG.md
- lib/core.ps1
- lib/install.ps1
- test/Scoop-Config.Tests.ps1
Use utf8 encoding in scoop's and aria2's config
Fixes #4629
[1]: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-5.1
[2]: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext
New unit tests introduced.
> fix(core): Ensure manipulating config with UTF8 encoding

- CHANGELOG.md
- libexec/scoop-search.ps1
> fix(scoop-search): Remove redundant 'bucket/' in search result

- CHANGELOG.md
- libexec/scoop-shim.ps1
- libexec/scoop-which.ps1
Fix `scoop which` and `scoop shim add` error by newly added double quotes.
Relates to #4734
> fix(shim): Fix `scoop which` error

- CHANGELOG.md
- bin/install.ps1
`installed` now use `Get-CurrentVersion` from `versions.ps1` which is not downloaded during installation. Use `Get-Command` instead (from `ScoopInstall/Install`)
Closes #4783
Tested in Windows SandBox
> fix(install): Use 'Get-Command' to test scoop install status

- CHANGELOG.md
- bin/refresh.ps1
- lib/commands.ps1
- lib/core.ps1
`relpath` seems to be added in PS 2.0 era, using `$PSScriptRoot` instead.
Passed tests.
> refactor(relpath): Use `$PSScriptRoot` instead of `relpath`

- CHANGELOG.md
- libexec/scoop-prefix.ps1
A typo introduced by #4722
Closes #4790
> fix(scoop-prefix): Fix typo that breaks global installed apps

- CHANGELOG.md
- lib/core.ps1
Unintentional deletion in #4650 that breaks `installed <app>` (w/o `$global`) which check both locally and globally installed app.
Closes #4796
Relates to #4650
Install `lua` as global app, before and after this fix:
> fix(installed): If no `$global`, check both local and global installed

- CHANGELOG.md
- lib/core.ps1
- libexec/scoop-alias.ps1
- test/Scoop-Alias.Tests.ps1
Manipulating shims with UTF8 encoding
Closes #4784
Closes #2573
Closes #2230
> fix(shim): Manipulating shims with UTF8 encoding

- CHANGELOG.md
- bin/scoop.ps1
- lib/core.ps1
- libexec/scoop-bucket.ps1
- libexec/scoop-cat.ps1
- libexec/scoop-cleanup.ps1
- libexec/scoop-config.ps1
- libexec/scoop-depends.ps1
- libexec/scoop-download.ps1
- libexec/scoop-export.ps1
- libexec/scoop-help.ps1
- libexec/scoop-hold.ps1
- libexec/scoop-home.ps1
- libexec/scoop-info.ps1
- libexec/scoop-install.ps1
- libexec/scoop-list.ps1
- libexec/scoop-reset.ps1
- libexec/scoop-search.ps1
- libexec/scoop-status.ps1
- libexec/scoop-unhold.ps1
- libexec/scoop-uninstall.ps1
- libexec/scoop-update.ps1
- libexec/scoop-virustotal.ps1
- libexec/scoop-which.ps1
- test/Scoop-Alias.Tests.ps1
- test/Scoop-Core.Tests.ps1
`reset_aliases` is added since scoop uses lots of PS alias (md, cd, gci, etc.) during its early development, and this function reset all alias to PS's default.
Now Verb-Noun form of function names is used, so this is not needed.
The one added in `scoop.ps1` is force use script (scoop) function instead of user-definded alias or function in global environment outsides scoop.
Additionally, `ensure()` is refactored and `mkdir` in test files are replaced by `ensure()`
Passed tests.
> refactor(reset_aliases): Move core function of `reset_aliases` to `scoop`

- CHANGELOG.md
- lib/core.ps1
Correctly quote $@ in sh->ps1 shims
Closes #4808
1. Made the change locally to `~/scoop/apps/scoop/current`
2. Run `scoop update`
3. Verified `~/scoop/shims/scoop` is updated correctly
4. Run `scoop update '*'` from git bash, which succeeded.
> fix: Correctly quote $@ in sh->ps1 shims

- CHANGELOG.md
- lib/core.ps1
- libexec/scoop-download.ps1
- When `scoop-download` catches an error in `dl_with_cache`, now a variable is saved so that the final success message will not appear.
- ~When `aria2` is enabled but not installed, `Test-Aria2Enabled` now warns the user that the standard download method will be used instead of `aria2`~
Closes #4810
I tested running this without internet and the failure was successfully caught, I tested both with aria2 and without so I have tested `dl_with_cache` and `dl_with_cache_aria2`.
This shows both changes in action:
```
❯ scoop config aria2-enabled
True
~
❯ c:\Users\me\Documents\GitHub\Scoop\libexec\scoop-download.ps1 protobuf
INFO  Starting download for protobuf...
WARN  aria2 is enabled but not installed, using standard download instead.
No such host is known. (github.com:443)
ERROR URL …
```
> fix(scoop-download): Add failure check

- CHANGELOG.md
- README.md
- bin/checkver.ps1
- lib/core.ps1
- lib/install.ps1
- libexec/scoop-config.ps1
- Rename `checkver_token` to `gh_token` and `SCOOP_CHECKVER_TOKEN` to `SCOOP_GH_TOKEN`
- Follow up fix for https://github.com/ScoopInstaller/Scoop/pull/4254 (filtering null input in dl function when private_hosts is not set in config)
> Rename checkver_token to gh_token and SCOOP_CHECKVER_TOKEN to SCOOP_GH_TOKEN

- CHANGELOG.md
- lib/buckets.ps1
- lib/install.ps1
- libexec/scoop-bucket.ps1
- libexec/scoop-home.ps1
- libexec/scoop-virustotal.ps1
- test/Import-Bucket-Tests.ps1
`find_manifest()` and `Find-Manifest()` (former `locate()`) have similar functionality and now be merged into `Find-Manifest()`.
Also move `list_buckets()` from `libexec\scoop-bucket.ps1` to `lib\buckets.ps1`.
Discussed with @rashil2000 
`scoop bucket` and `scoop
> refactor(bucket): Move 'Find-Manifest' and 'list_buckets' to 'buckets'

- CHANGELOG.md
- lib/install.ps1
- lib/psmodules.ps1
Fixes installation of scoop in Dockerfile due to https://github.com/docker/for-win/issues/12240
Fixes #4792
Tested in windows docker & windows vm
> fix(install): Fix Junction creation during installation inside containers

- CHANGELOG.md
- README.md
Update installation instruction to reflect adoption of the standalone installer.
> docs(readme): Update installation instruction

- CHANGELOG.md
- bin/checkver.ps1
- lib/core.ps1
- lib/install.ps1
There are multiple usages of GitHub token value in the scoop (in checkver.ps1, core.ps1, install.ps1), but only in once place (in checkver.ps1), there is a logic to try using token value from `SCOOP_GH_TOKEN` environment variable first. This PR unifies the token value obtain logic and puts it into the function, which is used everywhere token value is needed.
Using token in environment variable is needed for GitHub Actions setup (I am setting up GitHub Actions for private bucket right now and token is required for accessing artifacts located in private repository).
Tested with private GitHub repositories using both `gh_token` and `SCOOP_GH_TOKEN` values.
> feat(config): Try SCOOP_GH_TOKEN value first before gh_token value from config

- supporting/shims/kiennq/Makefile
With the new build pipeline in https://github.com/kiennq/scoop-better-shimexe/commit/db29490243810674bfa35c5017fbdc96acede9f9, the artifact name will be `shimexe.zip` only
> fix(shim-kiennq): Update shimexe file name

- CHANGELOG.md
- schema.json
Don't require `description` in manifest since many user made manifests in user bucket may not have it.
Relates to https://github.com/ScoopInstaller/Scoop/pull/4528#issuecomment-1086083652
Not suitable.
> build(schema): Remove 'description' from required fields

- CHANGELOG.md
- bin/auto-pr.ps1
- bin/checkver.ps1
Closes https://github.com/ScoopInstaller/Scoop/issues/4863
This is the core part of the change. The GitHub Action part is at https://github.com/ScoopInstaller/GithubActions/pull/5.
I created a Scoop bucket repo with some manifests in it. One manifest is intentionally old and requires update.
1. Make the manifest's `autoupdate` url wrong so it can't complete the autoupdate process.
2. Run the excavator workflow, observe the run completes successfully, though there is error message in the log (the option is disabled as default).
3. Add `THROW_ERROR` option to excavator.yml, make it '0'. Rerun the workflow. Observe the exact same result (because option is disabled as default).
4. Change `THROW_ERROR` to '1'. Rerun the workflow. Observe the run is now failed and GitHub sends notification to …
> feat(checkver): Add option to throw error as exception

- CHANGELOG.md
- test/Import-Bucket-Tests.ps1
Remove `description` error for `Import-Bucket-Tests`
Relates to https://github.com/ScoopInstaller/Scoop/pull/4853#issuecomment-1097513032
None.
> fix(test): Remove 'description' requirement

- CHANGELOG.md
- lib/manifest.ps1
- libexec/scoop-hold.ps1
- libexec/scoop-install.ps1
- libexec/scoop-unhold.ps1
- libexec/scoop-update.ps1
`json.ps1` that provides `ConvertToPrettyJson()` is missing in some libexec.
Closes https://github.com/ScoopInstaller/Scoop/pull/4839#issuecomment-1106272088
> fix(libs): Add missing 'json.ps1' dependency

- CHANGELOG.md
- lib/buckets.ps1
- lib/core.ps1
- libexec/scoop-alias.ps1
- libexec/scoop-bucket.ps1
1. Return a zero-length list instead of `$null` in `Get-LocalBucket`.
2. Adjust the output message for `scoop alias list` when there is no alias found.
3. Adjust the output message for `scoop cache show` when there is no cache found.
1. I ran into an error when I removed all buckets and was trying to add them back using URLs of mirrors, which means running `scoop bucket list` when there is nothing in `$SCOOP\buckets`:
```
Get-Item: <path_to_scoop>\apps\scoop\current\lib\buckets.ps1:134:32
Line |
134 |              $bucket.Updated = (Get-Item "$path\bucket").LastWriteTime
|                                 ~~~~~~~~~~~~~~~~~~~~~~~
| Cannot find path '<path_to_scoop>\buckets\main\bucket' because it does not exist.
```
The `Get-LocalBucket` returns `$null` in this case, so …
> fix(bucket): Return empty list correctly in `Get-LocalBucket`

- CHANGELOG.md
> docs(changelog): Rearrange CHANGELOG

- CHANGELOG.md
- libexec/scoop-cleanup.ps1
Add `-a`/`--all` switch to `scoop cleanup` just likes the one in `scoop update`
Closes #4887
Sorry that I just cleaned up my cache using the above command...
> feat(scoop-cleanup): Add `-a/--all` switch to cleanup all apps

- CHANGELOG.md
- LICENSE
Just a reimplement of #4870, and some tweaks (since #4870 couldn't be edited by maintainers)
Closes #4868
Closes #4870 
Closes #4892
> feat(relicense): Relicense to dual-license (Unlicense or MIT)

- CHANGELOG.md
- lib/buckets.ps1
- libexec/scoop-update.ps1
1. Add missing 'main' repo URL in `scoop update` when user first install scoop and 'main' is extracted from zip archive.
2. Skip checking remote URL when bucket is a non-git local one.
Closes #4917 
Relates to #4814
All tests passed, and all bugs in original post have been corrected.
> fix(buckets): Don't check remote URL of non-git buckets

- CHANGELOG.md
- lib/buckets.ps1
Don't write message OK before bucket is cloned
Correct the bucket addition message context
No critical changes, no need to update tests.
> fix(buckets): Don't write message OK before bucket is cloned

- CHANGELOG.md
- README.md
Update license badge
Fix badge. Preview: <img src="https://img.shields.io/badge/license-UNLICENSE%20or%20MIT-blue" alt="License" />
docs fix, no tests needed.
> docs(readme): Update license badge [skip ci]

- CHANGELOG.md
- libexec/scoop-info.ps1
Fixes https://github.com/ScoopInstaller/Scoop/issues/4928.
Abort message no longer references the last bucket searched via `Find-Manifest`
Fixes #4928
This is an edge case abort message, and there appear to be no tests that use the string literal `Could not find manifest` which suggests the text is never explicitly matched against during test execution. 
```
$ find . -name "*.ps1" -exec grep -iH "could not find manifest" {} \;
./libexec/scoop-home.ps1:        abort "Could not find manifest for '$app'."
./libexec/scoop-info.ps1:    abort "Could not find manifest for '$(show_app $app)' in any known buckets."
```
My assumption here is that the tests should pass, sadly I don't actually have a powershell build environment, and I wouldn't really know how to start building one to include …
> fix(scoop-info): Fix error message when manifest is not found

- CHANGELOG.md
- libexec/scoop-search.ps1
Change regex in function [`search_remote`](https://github.com/ScoopInstaller/Scoop/blob/aaa726c09f786d2af902d827ae8d0caee964ca1e/libexec/scoop-search.ps1#L59-L71): only matches json files inside 'bucket' directory.
All [known buckets](https://github.com/ScoopInstaller/Scoop/blob/aaa726c09f786d2af902d827ae8d0caee964ca1e/buckets.json) store manifest json files in 'bucket' directory. Current `scoop-search.ps1` use a regex that may match json files in the root directory, which is unnecessary for them. This small change let the 'bucket' directory be required.
Closes #4943
1. Run regression and all tests passed:
```
Tests completed in 38.78s
Tests Passed: 125, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```
2. Try the command in issue #4943 and got output as expected:
```
scoop.ps1 …
```
> fix(scoop-search): Require files in 'bucket' dir for remote known buckets

- CHANGELOG.md
- bin/auto-pr.ps1
- bin/checkver.ps1
- bin/scoop.ps1
- lib/buckets.ps1
- lib/commands.ps1
- lib/install.ps1
- libexec/scoop-update.ps1
- supporting/shimexe/build.ps1
- supporting/validator/build.ps1
- test/Scoop-Alias.Tests.ps1
Get rid of `Invoke-Expression` that may cause problems and may leak some code.
Ref: https://github.com/MicrosoftDocs/PowerShell-Docs/wiki/The-case-for-and-against-Invoke-Expression
- Closes https://github.com/ScoopInstaller/Extras/issues/8494
- Closes https://github.com/ScoopInstaller/Extras/issues/8498
- Closes https://github.com/ScoopInstaller/GithubActions/pull/8
- `scoop -v`
- `scoop update`
- `scoop install gnupg`
- `.\bin\checkver i*` in 'extras' bucket
- `.\test.ps1`
> fix(core): Use Invoke-Command instead of Invoke-Expression

- CHANGELOG.md
- lib/core.ps1
> chore(core): Deprecate tls1 and tls1.1

- CHANGELOG.md
- libexec/scoop-uninstall.ps1
Execute the `pre_uninstall` hook before other uninstallation preparation work, namely `test_running_process`
Closes #4961
Motivations
- `pre_uninstall` script should handle teardown work such as stopping services, so that the uninstallation process isn't blocked by running processes.
- Matches symmetry with `post_uninstall`, which is run at the very end of the uninstallation process.
> fix(scoop-uninstall): run pre_uninstall before testing running processes

- CHANGELOG.md
- lib/buckets.ps1
- lib/core.ps1
- lib/depends.ps1
- lib/install.ps1
- lib/manifest.ps1
- libexec/scoop-cat.ps1
- libexec/scoop-download.ps1
- libexec/scoop-home.ps1
- libexec/scoop-info.ps1
- libexec/scoop-install.ps1
- libexec/scoop-uninstall.ps1
- libexec/scoop-virustotal.ps1
- test/Scoop-Depends.Tests.ps1
- Move `bucket.ps1/Find-Manifest()` to `manifest.ps1/Get-Manifest()`
- Embed `parse_app()` into `Get-Manifest()`
- Enclose `parse_app()`'s RegEx with `^` and `$`
- Closes #4910
- Relates to https://github.com/ScoopInstaller/Scoop/pull/4914#issuecomment-1128677389
- `scoop cat`
- `scoop info`
- `scoop home`
- `scoop install`
- `test.ps1`
> refactor(manifest): Rename 'Find-Manifest()' to 'Get-Manifest()'

- CHANGELOG.md
- libexec/scoop-download.ps1
```
❯ scoop download mpv
INFO  Starting download for /mpv...
Loading mpv-0.34.0-x86_64.7z from cache
Checking hash of mpv-0.34.0-x86_64.7z ... ok.
'/mpv' (0.34.0) was downloaded successfully!
```
The appname appended with `/`(slash), when execute `scoop download <app>`
Closes #XXXX
> fix(scoop-download): Use correct Args when calling `Get-Manifest`

- CHANGELOG.md
- lib/buckets.ps1
Forcing `$buckets` to return as an array.
Fix #4978 
`scoop bucket list` displays installed buckets again.
- [ x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [ x] I have ensured that I am targeting the `develop` branch.
- [ x] I have updated the documentation accordingly.
> fix(buckets): Make sure `list_buckets` return array

- CHANGELOG.md
- lib/depends.ps1
- lib/manifest.ps1
- libexec/scoop-download.ps1
There're some bugs in #4966 and one of them is fixed in #4970. This PR fixes them all.
- 'Get-Dependency()' may return wrong app name when it's a path
- Trim starting "/" if there is no bucket
- Don't return wrong 'versions' bucket for local manifest
- Closes #4984
- Related #4966
- Related #4970
- `scoop install xxx@xxx`
- `scoop install \path\to\json\that\not\existed`
- `scoop install \path\to\json`
> fix(manifest): Fix bugs in 'Get-Manifest()'

- CHANGELOG.md
- libexec/scoop-hold.ps1
- libexec/scoop-unhold.ps1
Support a `-g`/`--global` flag for `scoop hold`/`scoop unhold`, which tells Scoop to hold/unhold globally installed apps.
Closes #4990.
1. Install an app both user-scoped and globally: `scoop install <app>` and `scoop install -g <app>`.
2. Hold/unhold the user-scoped app: `scoop hold <app>`/`scoop unhold <app>`. This does not require admin privileges.
3. Hold/unhold the global app without admin privileges: `scoop hold -g <app>`/`scoop unhold -g <app>`. It shows an error:
```
ERROR You need admin rights to hold a global app.
ERROR You need admin rights to unhold a global app.
```
4. Hold/unhold the global app with admin privileges: `sudo scoop hold -g <app>`/`sudo scoop unhold -g <app>`. It works as expected. (Assuming that `sudo` has been installed properly.)
> feat(scoop-hold,scoop-unhold): Support `-g`/`--global` flag

- CHANGELOG.md
- lib/core.ps1
- libexec/scoop-update.ps1
Support `scoop update scoop`
Closes #4940
Relates to #4811
```
scoop update
scoop update *
scoop update --all
scoop update scoop
scoop update scoop git
```
> feat(scoop-update): Support `scoop update scoop`

- CHANGELOG.md
- bin/checkver.ps1
- bin/describe.ps1
- lib/autoupdate.ps1
- lib/core.ps1
- lib/depends.ps1
- lib/description.ps1
- lib/manifest.ps1
- libexec/scoop-download.ps1
- libexec/scoop-hold.ps1
- libexec/scoop-unhold.ps1
- libexec/scoop-update.ps1
- libexec/scoop-virustotal.ps1
A bug fix version
- **core:** Add `Get-Encoding()` function to fix missing WebClient encoding (#4956)
- **scoop-update:** Support `scoop update scoop` (#4992)
- **scoop-virustotal:** Migrate to VirusTotal API v3 (#4983)
- **scoop-hold,scoop-unhold:** Support `-g`/`--global` flag (#4991)
- **manifest:** Fix bugs in 'Get-Manifest()' (#4986)
- Closes #4911
- Closes #4324
- Closes #4984
- Closes #4965
- Closes #4989
- Closes #4990
- Closes #4940
Thanks to the following contributors (ordered by PR merging time):
@yi-Xu-0100 @niheaven @ClassicDarkChocolate @lewis-yeung @chawyehsu
> chore(release): Bump to version 0.2.2

- CHANGELOG.md
- libexec/scoop-cache.ps1
- libexec/scoop-reset.ps1
- libexec/scoop-virustotal.ps1
> feat(chore): Add missing -a/--all param to all commands

- CHANGELOG.md
- bin/auto-pr.ps1
- bin/checkver.ps1
Allow passing local file paths to checkver utility.
Closes #4606
Relates to #3481
> feat(checkver,auto-pr): Allow passing file path

- CHANGELOG.md
- bin/checkver.ps1
If there is error, continue to next app earlier and not parse a empty page.
- Relates to #4956
Before:
After:
> builds(checkver): Exit routine earlier if error

- CHANGELOG.md
- libexec/scoop-status.ps1
See #5046.
Closes #5046.
Make an app fail to be installed via a separate manifest, and run `scoop status`.
> fix(scoop-status): Correct formatting of `Info` output

- CHANGELOG.md
- lib/install.ps1
When the `--no-cache` flag is specified, the downloaded file should be moved from the cache folder, instead of copying it. 
This was being done in `dl_with_cache_aria2` function, but not in `dl_with_cache` function. 
This PR fixes it.
Closes #5038
> fix(install): Move from cache when `--no-cache`

- CHANGELOG.md
- lib/core.ps1
Remove a deadlock potential in the function `Invoke-ExternalCommand`. See [MS docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=net-6.0#remarks) for details.
> fix(core): Avoid deadlock in `Invoke-ExternalCommand`

- CHANGELOG.md
- lib/core.ps1
- lib/decompress.ps1
Use `ArgumentList` in PowerShell 6.1 and later (built on .NET Core 2.1+), otherwise escape arguments using [the general MSVC Runtime's rules](https://docs.microsoft.com/en-us/previous-versions/17w5ykft(v=vs.85)) in older versions.
In the past, due to the arbitraryness of arguments, we are not able to handle all cases where arguments may contain spaces, quotes or other special characters for every automatic installer script that uses `Invoke-ExternalCommand`. With this change, we don't have to escape arguments manually for most external commands any more. But for the following exceptions who basically don't follow the general MSVC Runtime's rules of parsing command line, just simply concatenate arguments with spaces to build the argument list string, which means we have to escape arguments …
> feat(core): Improve argument concatenation in `Invoke-ExternalCommand`

- CHANGELOG.md
- lib/core.ps1
Support a new `-NoWindow` switch which indicates the process should be started without creating a new window to contain it. **This switch cannot go with `-RunAs`.**
> feat(core): Create no window by default in `Invoke-ExternalCommand`

- CHANGELOG.md
- lib/install.ps1
Display the bucket the app exists in.
Closes #2121
> feat(install): Show bucket name while installing an app

- CHANGELOG.md
- libexec/scoop-status.ps1
The improved status command checks for all outdated buckets. This can lead to slowdowns, so this optional flag disables all remote checking.
Closes #5044
> feat(scoop-status): Add flag to disable remote checking

- CHANGELOG.md
- bin/checkver.ps1
Load `checkver.url`'s page content before running `checkver.script` and `$page` variable could be used in the script.
- Closes https://github.com/ScoopInstaller/Java/issues/412
- Relates to #5025
> builds(checkver): Load page content before running 'script'

- CHANGELOG.md
- libexec/scoop-update.ps1
The `$cmd` in [Pre-Post-(un)install-scripts](https://github.com/ScoopInstaller/Scoop/wiki/Pre-Post-(un)install-scripts) says that the `scoop-update` should support the `pre_uninstall` and the `post_uninstall`, but it did not use the `scoop-uninstall` so that the `pre_uninstall` and the `post_uninstall` were missed.
Add support for `pre_uninstall` and `post_uninstall`.
> feat(scoop-update): Add support for `pre_uninstall` and `post_uninstall`

- CHANGELOG.md
- lib/core.ps1
Use a native way to pass `$null` to `installed`, see [ref](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-5.1#parameters-that-take-true-and-false)
- Relates to #4798
>  fix(installed): Use 'System.Nullable<bool>' for param 'global'

- CHANGELOG.md
- bin/install.ps1
- lib/core.ps1
- libexec/scoop-config.ps1
- libexec/scoop-hold.ps1
- libexec/scoop-unhold.ps1
- libexec/scoop-update.ps1
Support `scoop (un)hold scoop`.
Allow to disable scoop itself updates for one day.
The `scoop` is a app in scoop, but it can not to be hold.
Now it works. 😁
> feat(scoop-(un)hold): Support `scoop (un)hold scoop`

- CHANGELOG.md
- libexec/scoop-config.ps1
- libexec/scoop-update.ps1
Auto stash uncommitted changes of scoop before update.
Now the action is done in scoop core, should this be applied to buckets too?
- Relates to https://github.com/ScoopInstaller/Scoop/pull/5089#issuecomment-1207388756
And this could be tested by checking out this PR, adding some dummy files in scoop dir and running `scoop update`.
> feat(scoop-update): Stash uncommitted changes before update

- CHANGELOG.md
- lib/core.ps1
- libexec/scoop-config.ps1
- libexec/scoop-hold.ps1
- libexec/scoop-unhold.ps1
- libexec/scoop-update.ps1
Rename `update_until` to `hold_update_until` and allow it be set manually in the format such as `YYYY/MM/DD`, `YYYY-MM-DD` or any other forms that accepted by [[System.DateTime]::Parse()](https://docs.microsoft.com/dotnet/api/system.datetime.parse?view=netframework-4.5#StringToParse)
- Relates to https://github.com/ScoopInstaller/Scoop/pull/5089#issuecomment-1211876041
> feat(scoop-config): Allow 'hold_update_until' be set manually

- CHANGELOG.md
- bin/install.ps1
- lib/core.ps1
- lib/decompress.ps1
- lib/depends.ps1
- lib/install.ps1
- lib/manifest.ps1
- lib/unix.ps1
- lib/versions.ps1
- libexec/scoop-cat.ps1
- libexec/scoop-checkup.ps1
- libexec/scoop-config.ps1
- libexec/scoop-export.ps1
- libexec/scoop-hold.ps1
- libexec/scoop-unhold.ps1
- libexec/scoop-update.ps1
- libexec/scoop-virustotal.ps1
- test/Import-File-Tests.ps1
- test/Scoop-Depends.Tests.ps1
Use snake_case in `~/.config/scoop.json` and CREAMING_CASE in Scoop code for config options.
Also change some config options' name:
- lastupdate -> last_update
- 7ZIPEXTRACT_USE_EXTERNAL -> use_external_7zip
- MSIEXTRACT_USE_LESSMSI -> use_lessmsi
- NO_JUNCTIONS -> no_junction
- manifest_review -> show_manifest
- rootPath -> root_path
- globalPath -> global_path
- cachePath -> cache_path
- Relates to #5098
**NOTICE** If someone want to test this PR, please backup `~/.config/scoop.json` 😄 
Local tests (`.\bin\test.ps1`) passed, and `scoop config` gives a warning if use old names. (BTW, PowerShell is case insensitive)
> fix(config): Change config option to snake_case in file and SCREAMING_CASE in code

- CHANGELOG.md
- bin/auto-pr.ps1
- bin/checkhashes.ps1
- bin/checkurls.ps1
- bin/checkver.ps1
- bin/describe.ps1
- bin/formatjson.ps1
- bin/missing-checkver.ps1
- lib/core.ps1
- lib/manifest.ps1
- lib/psmodules.ps1
- lib/unix.ps1
- libexec/scoop-reset.ps1
- test/bin/test.ps1
Use `Convert-Path()` instead of `Resolve-Path()` while the latter will *resolve* the **wildcard** characters in a path (we just want to *convert* a path from a PowerShell path to a PowerShell provider path or *expand* a path)
None
Internal tests passed, all functions should work well, and more tests should be made.
> refactor(path): Use 'Convert-Path()' instead of 'Resolve-Path()'

- CHANGELOG.md
- lib/getopt.ps1
- test/Scoop-GetOpts.Tests.ps1
Support the option terminator `--` in `getopt`, which is compatible with POSIX conventions for command line options (see [reference](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) for details).
This is also a prerequisite for fixing #5094.
Tested locally with updated [test/Scoop-GetOpts.Tests.ps1](https://github.com/ScoopInstaller/Scoop/blob/876d0ee2d1673c316ea14e84872eece1278fe49d/test/Scoop-GetOpts.Tests.ps1). All passed.
> feat(getopt): Support option terminator (`--`)

- CHANGELOG.md
- lib/psmodules.ps1
Add a `-Recurse` parameter to `Remove-Item` cmdlet when unlinking psmodule path.
- Relates to #5126
I've tested my codes by performing update for the same app, everything seems ok 
```powershell
Linking ~\scoop\modules\WhoAteMyRAM => ~\scoop\apps\WhoAteMyRAM\current
WARN  ~\scoop\modules\WhoAteMyRAM already exists. It will be replaced.
Running post_install script...
'WhoAteMyRAM' (1.0.10) was installed successfully!
```
Changes may effect:
https://github.com/ScoopInstaller/Scoop/blob/d63b7d6f01bb33c473172715d1007751baf937de/libexec/scoop-uninstall.ps1#L85
https://github.com/ScoopInstaller/Scoop/blob/4a31bd330244f7f89f16208cdddda3f9edac2d65/lib/install.ps1#L60
> fix(psmodules): Remove folder recursively when unlinking previous module path

- CHANGELOG.md
- lib/json.ps1
If you extract the date and time string with `checkver/jsonpath` in the manifest file, it will be converted to `M/d/yyyy h:m:s tt` format instead of the original string. This is due to Json.net converting to DateTime type, so it suppresses the conversion.
Closes #5129 
1. `scoop bucket add version`
2. modify `goneovim-nightly.json` with https://github.com/ScoopInstaller/Versions/pull/618
3. modify `lib/json.ps1` with this PR
4. `checkver.ps1 goneovim-nightly ~/scoop/bucket/versions/bucket -f`
5. update successful
> fix(jsonpath): Prevent converting date string to DateTime in JSONPath

- CHANGELOG.md
- libexec/scoop-update.ps1
Add `uninstall_psmodule` to update process.
- Closes #5135
Run scoop update in same situation.
> fix(scoop-update): Add uninstall_psmodule to update process

- CHANGELOG.md
- libexec/scoop-shim.ps1
Use `getopt` to parse arguments, which avoids some problems. BTW, add some logic and tweak some error messages.
These problems will be resolved:
1. For example, run `scoop shim add myapp ''`, the second parameter (`<command_path>`) gets an empty value, so Scoop will throw an exception, which is not so friendly. :
```
Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```
2. For example, run `scoop shim list *`, the regex pattern `*` is invalid, so Scoop will throw an exception, which is not so friendly. :
```
Invalid pattern '*' at offset 1. Quantifier {x,y} following nothing.
```
3. The `-g`/`--global` option cannot be parsed in `scoop shim ...`. See #5094.
Now with this:
1. `scoop …
> refactor(scoop-shim): Use `getopt` to parse arguments

- .vscode/settings.json
- CHANGELOG.md
- bin/checkhashes.ps1
- bin/install.ps1
- lib/autoupdate.ps1
- lib/core.ps1
- lib/install.ps1
- libexec/scoop-download.ps1
- libexec/scoop-update.ps1
This PR renames the `dl` and related functions to use more descriptive names that better adhere to PowerShell conventions.
Resolves #3830
Test suite run on local machine and in [CI](https://github.com/examosa/Scoop/actions/runs/3040324142/jobs/4896244634); all remain passing.
> refactor(download): Rename `dl()` to `Invoke-Download()`

- CHANGELOG.md
- bin/checkver.ps1
- schema.json
SourceForge checkver based on @se35710's previous work.
*The following description is copied from #4560 and updated*
In it's most simple form:
```json
"checkver": "sourceforge",
```
This will find the project name from homepage, or if that fails, from the manifest name.
A more comples example:
```json
"checkver": {
"sourceforge": {
"project": "pmt",
"path": "pngcrush-executables"
}
},
```
or simplified version (**newly added, just likes github**)
```json
"checkver": {
"sourceforge": "pmt/pngcrush-executables"
},
```
Here we provide the project name, and a path into the files section (to limit number of downloads). `project` is optional and only needed if `homepage` or manifest name is not equal to the SourceForge project name.
The default regex is `(?!\.)([\d.]+)(?<=\d)` and the actually …
> builds(checkver): Implement SourceForge checkver functionality

- CHANGELOG.md
- bin/checkhashes.ps1
- bin/checkurls.ps1
- bin/checkver.ps1
- bin/describe.ps1
- bin/formatjson.ps1
- bin/missing-checkver.ps1
- lib/autoupdate.ps1
- lib/buckets.ps1
- lib/manifest.ps1
- test/Import-Bucket-Tests.ps1
Allow subdir in buckets' `bucket` directory, e.g., `main/bucket/#/7zip.json`. All scoop command is unchanged (`scoop search <xxx>`, `scoop install <xxx>`, `checkver`, `checkurls`, `checkhashes`, etc.)
There's some discussion before (to avoid GitHub's 1000 files limit).
This PR won't change too much in scoop ecosystem, but the actual change of buckets structure **WILL/MAY** affect scoop manifests search engines. ([PullRequestHandler GHA](https://github.com/ScoopInstaller/Tests/runs/7951004035?check_suite_focus=true) failed because of `checkver` and `checkhashes` which are fixed in this PR)
All tests are passed, and all scoop subcommand and scripts in `bin` are tested. (With ScoopInstaller/Tests#6)
> feat(subdir): Allow subdir in 'bucket'

- CHANGELOG.md
- bin/checkhashes.ps1
- lib/autoupdate.ps1
- lib/install.ps1
- lib/unix.ps1
- supporting/shimexe/build.ps1
- supporting/validator/build.ps1
- test/Scoop-Decompress.Tests.ps1
- test/Scoop-Install.Tests.ps1
PowerShell 5 and later have `Get-FileHash()` and we could use it directly.
Simplify code base.
`scoop install` and `checkver`
> refactor(hash): Use 'Get-FileHash()' directly

- CHANGELOG.md
- lib/decompress.ps1
Added...Removed...Added again...
- Closes #5183
> fix(decompress): Use PS's default 'Expand-Archive()'

- CHANGELOG.md
- bin/checkver.ps1
If XML has default namespace such as `<xxx xmlns="xxxx">`, it could not be added again via `System.Xml.XmlNamespaceManager.AddNamespace()`, so add it with `ns` and add `ns:` to XPath.
- Closes #5187
> builds(checkver): Support XML default namespace

- CHANGELOG.md
- lib/decompress.ps1
Only invoked in PowerShell 5
- Closes #5193
- Closes https://github.com/ScoopInstaller/Java/issues/418
> fix(decompress): Trim ending '/'

- CHANGELOG.md
- PSScriptAnalyzerSettings.psd1
`Invoke-Expression()` has been remove in #4941, and `PSUseDeclaredVarsMoreThanAssignments` seems to work fine now.
Just clean up codes.
PS7:
PS5:
> builds(pssa): Remove unused 'ExcludeRules'

- CHANGELOG.md
- lib/getopt.ps1
- libexec/scoop-import.ps1
Copyedit config description
Fix the error in `scoop import` command
- Closes #5208
- Relates to #5154
> fix(import): Fix `scoop import` command

- CHANGELOG.md
- schema.json
Add back `installer` and `shortcuts` to `schema.json`
- Relates to #5093
`installer` and `shortcuts` are in `autoupdateArch`, but not in `autoupdate`. https://github.com/ScoopInstaller/Versions/blob/master/bucket/gimp-dev.json use autoupdate to change the shortcuts' exe names since it's version related.
Just remove test error log.
> builds(schema): Add 'installer' and 'shortcuts' to 'autoupdate'

- CHANGELOG.md
- test/Import-Bucket-Tests.ps1
- test/bin/test.ps1
Copyedit config description
Using $env:BH* to simplify code.
- Relates to #5222
See https://github.com/niheaven/scoop-nih/pull/7
> tests(bucket): Use BuildHelpers EnvVars

- CHANGELOG.md
- libexec/scoop-config.ps1
> Beginning in PowerShell 6, ConvertTo-Json attempts to convert strings formatted as timestamps to DateTime values.
https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.2#notes
So this fix coerce [DataTime] output to [String] to make uniform output in PS5 and PS7.
- Closes #5229
PS5:
```shell
❯ scoop config last_update
2022-10-30T17:14:47.9357171+08:00
```
PS7 (before):
```shell
❯ scoop config last_update
2022年10月30日 17:14:47
```
PS7 (after):
```shell
❯ scoop config last_update
2022-10-30T17:14:47.9357171+08:00
```
> fix(scoop-config): Output [DateTime] as [String]

- CHANGELOG.md
- bin/checkhashes.ps1
This fix is concerned with GitHubActions, which downloads file twice if there's no autoupdate hash extraction.
When using `checkhashes`, the actual files are downloaded and hash checked, but the version number in cached file is `HASH_CHECK`, and in GHA, `checkhashes` and `checkver` both download files and don't reuse them. So change `checkhashes`'s switch to let reuse.
Before:
After:
> builds(checkhashes): Use correct version number if `UseCache`

- CHANGELOG.md
- bin/scoop.ps1
- lib/buckets.ps1
- lib/core.ps1
- libexec/scoop-info.ps1
- libexec/scoop-status.ps1
- libexec/scoop-update.ps1
- By using the direct path to `$appdir\git\current\mingw64\bin\git.exe` this prevents spawning subprocesses and improves execution time
- This removes calling two shims. `$scoopdir\shims\git.exe` calls `$appdir\git\current\bin\git.exe` which is also a shim.
- Fixes #1615 by replacing `currentuser@` with `:@`
- Spawns cmd.exe only if the `PROXY` config value is set and required by the git command
- Uses PS7 feature `Foreach-Object -Parallel` to run bucket updates in parallel to improve execution time
- Not sure how to show the changelog right now, so I just added `[extras]` behind the commit hash
- Fallback to sequential updates for PS5
- Improve git log output
Using a fixed `git.exe` could be a problem if someone uses git not installed via scoop because this will not detect it with …
> feat(chore): Improve git.exe execution and add parallel bucket updates

- CHANGELOG.md
- libexec/scoop-download.ps1
Show bucket, version, architecture information when downloading app.
- Clearly prompt the user which manifest(app) is downloading
- Consistent with `scoop-install`
> refactor(scoop-download): Output more detailed manifest information

- CHANGELOG.md
- lib/autoupdate.ps1
Fix file hash extraction:
- From `([a-fA-F0-9]{32,128})[\x20\t]+.*$basename(?:[\x20\t]+\d+)?`
- To `([a-fA-F0-9]{32,128})[\x20\t]+.*$basename(?:\s|$)|$basename[\x20\t]+.*?([a-fA-F0-9]{32,128})`
And format the file.
If checksum file has multiple hashes and filenames, the original regex may be failed 'cos there're many filenames that have same prefix, e.g., `aaa.exe` and `aaa.exe.bbb`. In such case, old one may not get the correct hash.
By ending with `\s|$`, the regex will use `$basename` only to find hash.
Also support hash format as `aaa.exe   <hash>`.
<details>
<summary>goreleaser</summary>
```json
{
"version": "1.13.1",
"description": "Release automation tool for Go projects.",
"homepage": "https://goreleaser.com",
"license": "MIT",
"architecture": {
"64bit": {
"url": …
```
> fix(autoupdate): Fix file hash extraction

- CHANGELOG.md
- lib/decompress.ps1
Exclude 0-bit `*.nsis` when extraction
- Closes https://github.com/ScoopInstaller/Main/pull/4233
- Closes https://github.com/ScoopInstaller/Main/pull/4232
- Closes https://github.com/ScoopInstaller/Main/issues/4164
- Closes https://github.com/ScoopInstaller/Main/issues/4185
- Closes https://github.com/ScoopInstaller/Main/issues/4230
- Closes https://github.com/ScoopInstaller/Main/issues/4240
> fix(decompress): Exclude '*.nsis' that may cause error

- CHANGELOG.md
- lib/buckets.ps1
- lib/core.ps1
- libexec/scoop-info.ps1
Fix regression introduced in #5122, i.e. handling of Scoop home paths which have spaces in them.
Run commands like `scoop bucket ...` or `scoop info ...` which use Git internally.
> fix(chore): Handle spaces in git command arguments

- CHANGELOG.md
- bin/checkver.ps1
Checkver does not read the private_hosts config variable. That's mean it is not possible to add a url endpoint which points for example to a text file in a private repository, wherein you can query the current version of your app. 
Relates to https://github.com/ScoopInstaller/Scoop/discussions/5380
Just run the CI Tests.
> builds(checkver): Read the private_host config variable

- CHANGELOG.md
- lib/install.ps1
Fix RegEx in `is_in_dir()` to support Unix `/`
- Relates to #5235
> fix(core): Fix `is_in_dir` under Unix

- CHANGELOG.md
- lib/install.ps1
GitHub has changed the required API headers lately causing download of release assets from private GitHub repositories not to work. See https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28
Closes #5357 
Local tested with public (oh-my-posh package) and private GitHub repository download
> fix Unable to download release assets from private GitHub repositories

- CHANGELOG.md
- lib/core.ps1
Support portable config.json for increased portability.
Relates to #4498
Copy `~/.config/scoop/config.json` to or create an empty config.json in scoop root directory, it will then load the portable config file.
> feat(config): Support portable config file

- CHANGELOG.md
- lib/core.ps1
For example, the following command is used to obtain system environment variables.
```ps1
(Get-Item -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment").GetValue(
"Path",
"",
[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
```
The string obtained by it will not replace the `%%`.
Use the Registry to get the unexpanded environment variable string inspired by PowerShell/PowerShell#17518. 
Fixes #5394
Related to #1813
> fix(env): Avoid automatic expansion of `%%` in env

- CHANGELOG.md
- lib/install.ps1
- libexec/scoop-import.ps1
Direct calling of scoop scripts makes `getopt()` error, since it bypassed PowerShell's arguments parsing.
So use splatting to pass arguments correctly (w/o splitting by space).
- Relates to #5326
- Relates to #5210
Should be fine and tested by `scoop import`
> fix(core): Fix scripts' calling parameters

- CHANGELOG.md
- lib/getopt.ps1
- test/Scoop-GetOpts.Tests.ps1
Currently, getops parse with split space. With this correction, getops is more resilient and can parse in a more robust way with quote. Previously, 'parse this "sort of text"' => parse/this/sort/of/text
Now, 'parse this "sort of text"' => parse/this/sort of text
This correction can now handle parsing path with space (ex: c:\Program Files).
Closes #5313 
Use bug description, test on some other cases
> fix(getopt): Stop split arguments in `getopt()` and ensure array by explicit arguments type

- CHANGELOG.md
- libexec/scoop-info.ps1
Make the file size collection not error on normal use
- Join app path to the base path
- Do not attempt to measure `Length` of directories in the tree
`scoop info [app] --verbose` was failing in two locations.
Only tested locally with `scoop info dos2unix --verbose` and `scoop info llvm --verbose`
> fix(scoop-info) --verbose file size collection

- CHANGELOG.md
- lib/decompress.ps1
See: https://github.com/ScoopInstaller/Install/pull/42
Speeds up decompression of zip files if 7-Zip is not yet installed.
> perf(decompress): disable progress bar to improve Expand-Archive performance

- CHANGELOG.md
- lib/buckets.ps1
Sort buckets and make official buckets first, with order in https://github.com/ScoopInstaller/Scoop/blob/master/buckets.json
Change the function `Get-LocalBucket()` in `buckets.ps1` that should affect all commands related to unknown bucket in app name. (i.e., `app` not `bucket/app`)
- Closes #5131 
- Relates to https://github.com/ScoopInstaller/Main/pull/4409
- Relates to https://github.com/ScoopInstaller/Extras/pull/10396
- Relates to https://github.com/ScoopInstaller/Versions/pull/973
- Others?
Before:
After:
> feat(bucket): Make official buckets higher priority

- CHANGELOG.md
- lib/core.ps1
In function `Invoke-ExternalCommand`, the `$Process.StartInfo.CreateNoWindow` was forcibly set to `$true` by mistake in #5066, which may cause problems in some cases. In this PR, a `-Silent` switch was introduced. The switch controls whether an app should run silently, that means, without any output for a console app or without a window for a GUI app.
> feat(core): Add `-Silent` switch for `Invoke-ExternalCommand`

- CHANGELOG.md
- lib/core.ps1
I just realized that when installing Git through the installer, it puts the `bin` directory in PATH, which contains the bash executable. 
Likewise, when installing Git through Scoop, we create a shim for bash executable: https://github.com/ScoopInstaller/Main/blob/master/bucket/git.json#L40
Closes https://github.com/ScoopInstaller/Main/issues/4564
> fix(shim): Use bash executable directly

- CHANGELOG.md
- lib/core.ps1
Fix the problem caused by the merge of #5395, mentioned in [5424#issuecomment-1479734238](https://github.com/ScoopInstaller/Scoop/pull/5424#issuecomment-1479734238), similar to ScoopInstaller/Install#49.
Use `SendMessageTimeout` in user32 to update the env in explorer.exe, and then the new env will be used in new process of powershell/cmd.
I have tested it in some cases and it works fine. I can't guarantee that all situations will be known to me. For example, a known issue is that if you use Windows Terminal, updating env in one tab does not update env in another tab of the same window, as mentioned in microsoft/terminal#14999.
> fix(env): Apply env immediately by `SendMessageTimeout`

- CHANGELOG.md
- libexec/scoop-checkup.ps1
Get-MpPreference : Provider load failure
Defender is OFF in Sandbox.(default
Closes #XXXX
Relates to https://github.com/ScoopInstaller/Install/commit/c99c2f1d53cf699d1a02af1d5ad0ec897c9b6120
Before:
```
PS C:\Users\WDAGUtilityAccount> scoop checkup
Get-MpPreference : Provider load failure
At C:\Users\WDAGUtilityAccount\scoop\apps\scoop\current\lib\diagnostic.ps1:9 char:14
+         if ((Get-MpPreference).DisableRealtimeMonitoring) { return $t ...
+              ~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Get-MpPreference],
CimException
+ FullyQualifiedErrorId : HRESULT 0x80041013,Get-MpPreference
Get-MpPreference : Provider load failure
At C:\Users\WDAGUtilityAccount\scoop\apps\scoop\current\lib\diagnostic.ps1:9 char:14
+ …
```
> fix(scoop-checkup): Skip defender check in Windows Sandbox

- CHANGELOG.md
- lib/buckets.ps1
Closes #XXXX
Before:
```
❯ scoop bucket list
Get-Item : Cannot find path 'C:\Users\humorce\scoop\buckets\empty_dir\bucket' because it does not exist.
At C:\Users\humorce\scoop\apps\scoop\current\lib\buckets.ps1:114 char:32
+             $bucket.Updated = (Get-Item "$path\bucket").LastWriteTime
+                                ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\humorc...mpty_dir\bucket:String) [Get-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
Name      Source                                     Updated               Manifests
----      ------                                     -------               ---------
main      git@github.com:ScoopInstaller/Main.git …
```
> fix(buckets): Avoid error messages for unexpected dir

- CHANGELOG.md
- libexec/scoop-checkup.ps1
Closes #5613
As https://github.com/ScoopInstaller/Scoop/issues/5613#issuecomment-1685144260
run `scoop checkup`
> fix(scoop-checkup): Change the message level of helpers from ERROR to WARN

- CHANGELOG.md
- README.md
The README file of the project has gotten a series of redaction changes to make it more professional.
Documentation is something that can always be improved in some way. I have attempted to make it more professional.
Changing this document should not break the app or any other integrations.
> docs: update README.md

- CHANGELOG.md
- lib/core.ps1
Added 2 functions to get the subsystem of the shimmed PE binaries and change the subsystem of the shim executable while installing.
Closes #1606 as it is annoying to deal with the Console Window.
I've checked my code changes by installing packages: nvim, vim, wireshark, firefox.
Every GUI app from the above packages (nvim-qt, gvim, gvimdiff, wireshark, firefox) doesn't pop-up a console window and works fine.
The changed code only affects the `subsystem` value in the PE `Optional Headers` of the shim exe.
> fix(#1606): Remove console window for GUI apps, without changing the manifests.

- CHANGELOG.md
- lib/core.ps1
Use relative path as fallback of Scoop root directory.
Fallback to `~\scoop` cause non-standard installations of Scoop to not be recognized properly.
Relates to #5543 https://github.com/ScoopInstaller/Scoop/discussions/5542#discussioncomment-6199111
Before:
```
PS C:\Users\WDAGUtilityAccount> scoop bucket list
Get-ChildItem : Cannot find path 'C:\Users\WDAGUtilityAccount\scoop\buckets' because it does not exist.
At C:\Users\WDAGUtilityAccount\中文\s p a c e\scoop\apps\scoop\current\lib\buckets.ps1:61 char:62
+ ... eneric.List[String]](Get-ChildItem -Path $bucketsdir -Directory).Name
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\WDAGUt...t\scoop\buckets:String) [Get-ChildItem], ItemNotFound
Exception
+ …
```
> fix(core): Use relative path as fallback of `$scoopdir`

- CHANGELOG.md
- lib/core.ps1
Issue:
When delete environment variable during uninstallation, if the environment variable has been deleted before, we will get a error message.
Examples:
1. Same environment variable (name) provide by multiple manifests
2. Delete manually
Before:
```
PS C:\Users\WDAGUtilityAccount> scoop install openssl1 openssl1-light
Installing 'openssl1' (1.1.1u) [64bit] from versions bucket
Loading Win64OpenSSL-1_1_1u.exe from cache
Checking hash of Win64OpenSSL-1_1_1u.exe ... ok.
Extracting Win64OpenSSL-1_1_1u.exe ... done.
Linking ~\scoop\apps\openssl1\current => ~\scoop\apps\openssl1\1.1.1u
Creating shim for 'openssl'.
'openssl1' (1.1.1u) was installed successfully!
Installing 'openssl1-light' (1.1.1u) [64bit] from versions bucket
Loading Win64OpenSSL_Light-1_1_1u.exe from cache
Checking hash of …
```
> fix(core): Avoid error messages when deleting non-existent environment variable

- CHANGELOG.md
- lib/core.ps1
- libexec/scoop-which.ps1
`scoop-which` cannot get path when these case:
- `scoop which <manually creaetd/edited shim missing shimTarget>`
- `scoop which <copied shim>` e.g. moving Scoop root directory from other locations
- `scoop which scoop-<scoop_alias>`
> fix(core): Handle scoop aliases and broken(edited,copied) shim

- CHANGELOG.md
- libexec/scoop-hold.ps1
- libexec/scoop-unhold.ps1
- Abort hold when manifest not found
- Abort hold when app already held
- Abort unhold when app not held
Closes #5485 #5273
Before:
#5485
After:
```
PS C:\Users\WDAGUtilityAccount> scoop hold mysql-workbench
Failed to hold 'mysql-workbench'.
PS C:\Users\WDAGUtilityAccount> scoop unhold mysql-workbench
Failed to unhold 'mysql-workbench'
PS C:\Users\WDAGUtilityAccount> scoop reset mysql-workbench
Resetting mysql-workbench (8.0.31).
Linking ~\scoop\apps\mysql-workbench\current => ~\scoop\apps\mysql-workbench\8.0.31
Creating shim for 'MySQLWorkbench'.
Creating shim for 'mysql'.
Creating shim for 'mysqldump'.
Creating shortcut for MySQLWorkbench (MySQLWorkbench.exe)
PS C:\Users\WDAGUtilityAccount> scoop hold mysql-workbench
mysql-workbench is now held and can not be updated anymore.
PS …
```
> fix(scoop-(un)hold): Correct output the messages when manifest not found, (already|not) held

- CHANGELOG.md
- libexec/scoop-search.ps1
This is another attempt to improve the local search performance.
- Not using the `manifest()` function
- Use only one loop over `$apps`
- Push results to `$list` directly
- Use `[System.IO.File]::ReadAllText()` instead of `Get-Content`
Closes #4239
Relates to #4818
```pwsh
Measure-Command { scoop search telegram }
Measure-Command { .\bin\scoop.ps1 search telegram }
```
> Another attempt to improve the search performance

- CHANGELOG.md
- lib/core.ps1
1. Fix function `Test-GitAvailable`: avoid outputs additional error in powershell 5.x
CAUSE: git's path are `Test-Path` twice.
https://github.com/ScoopInstaller/Scoop/blob/1d140585a4895c533a39b08e17ab615cdbfe323f/lib/core.ps1#L352
https://github.com/ScoopInstaller/Scoop/blob/1d140585a4895c533a39b08e17ab615cdbfe323f/lib/core.ps1#L371-L375
2. Fix function `Get-HelperPath`: fallback git(32bit).
CAUSE: git(32bit) is not expected before.
https://github.com/ScoopInstaller/Scoop/blob/1d140585a4895c533a39b08e17ab615cdbfe323f/lib/core.ps1#L370
Relates to #5122
1. `Test-GitAvailable`
Before:
```
PS C:\Users\WDAGUtilityAccount> $PSVersionTable.PSVersion.Major
5
PS C:\Users\WDAGUtilityAccount> scoop update
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At …
```
> fix(core): Fix detection of Git

- CHANGELOG.md
- lib/core.ps1
- lib/psmodules.ps1
Allow global install of PowerShell modules
- ~~By installing them to $env:ProgramFiles\WindowsPowerShell\Modules which is the folder where both Windows PowerShell and PowerShell core use. (See https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psmodulepath )~~
- By installing them to `basedir\modules` (c:\ProgramData\scoop\modules) 
- And adding that path to system (all users) PSModulePath env var.
Closes #5601 #5597
By installing, updating, uninstalling gsudo.
```
scoop install gsudo -g
scoop uninstall gsudo -g
scoop install gsudo@2.1.0 -g
scoop install gsudo@2.3.0 -g
```
> feat: Allow global install of PowerShell modules 

- CHANGELOG.md
- libexec/scoop-update.ps1
> fix(update): Change error message to a better instruction

- CHANGELOG.md
- lib/core.ps1
Changed a bit of order of operations. What was happening before didn't make any sense with the kinds of input and outputs Resolve-Path uses. Without any documentation to go off, it seems the original creator wanted a relative path ***from*** the shims dir ***to*** the file you are trying to create a shim for because of weird pathname bugs that occur when that file is on a separate drive from your scoop install. The code now reflects that line of logic and produces no error output.
I like to use scoop shims as a centralized way to add programs to my path (Ex: `scoop shim add ols .\ols.exe` where ols was built from source), but that had error output generated by Resolve-Path. It wasn't preventing the creation of my shims in this case, but it was a bug none-the-less.
Closes #5492
I've …
> fix: fixed shim add bug related to #5492

- CHANGELOG.md
- libexec/scoop-shim.ps1
Related: #5568. See my [comment](https://github.com/ScoopInstaller/Scoop/issues/5568#issuecomment-1752724083).
The usage of `scoop shim list` should be more explicit: `scoop shim list [<shim_name>/<regex_pattern>...]`, since regular expression matching is used in this case.
Closes #5568.
Run:
```powershell
scoop shim list scoo*
```
Output:
```
Name       Source   Alternatives IsGlobal IsHidden
----       ------   ------------ -------- --------
scoop-slim External              False    False
scoop      scoop                 False    False
```
> fix(shim): Avoid unexpected output of `list` subcommand

- CHANGELOG.md
- libexec/scoop-shim.ps1
A run of `scoop shim info scoo*` shows this:
```
Name     : scoo*
Path     : <SCOOP_ROOT>\shims\scoo*.ps1
Source   : scoop
Type     : ExternalScript
IsGlobal : False
IsHidden : True
```
Related code:
https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/libexec/scoop-shim.ps1#L82-L89
A name containing wildcard characters (e.g., `*`) is directly passed to `Get-ShimPath` here and the returned path still contains wildcard characters.
This is not expected according to the usage of `scoop shim info <shim_name>`. No characters should be interpreted as wildcard characters here.
Fix the bug.
Run:
```powershell
scoop shim info scoo*
scoop shim info scoo* -g
```
Output:
```
ERROR: Local shim not found: scoo*
ERROR: Global shim not found: scoo*
```
> fix(shim): Check literal path in `Get-ShimPath`

- CHANGELOG.md
- libexec/scoop-create.ps1
- libexec/scoop-download.ps1
- libexec/scoop-install.ps1
- libexec/scoop-virustotal.ps1
Call `scoop` internally instead of calling it externally from inside the code.
Overall, calling "myself" externally, it is bad practice, unless there is a good reason for doing it.  
Closes #5694
```
> scoop create
Usage: scoop create <url>
Create your own custom app manifest
> scoop install make
WARN  Skipping self-update of Scoop Core until 12/31/2023 00:00:00...
WARN  If you want to update Scoop Core immediately, use 'scoop unhold scoop; scoop update'.
Updating Buckets...
Scoop was updated successfully!
Installing 'make' (4.4.1) [64bit] from main bucket
Loading make-4.4.1-without-guile-w32-bin.zip from cache
Checking hash of make-4.4.1-without-guile-w32-bin.zip ... ok.
Extracting make-4.4.1-without-guile-w32-bin.zip ... done.
Linking C:\codew\scoop\apps\make\current => …
```
> fix: do not call `scoop` externally from inside the code

- CHANGELOG.md
- libexec/scoop-reset.ps1
Closes #5686
install autodarkmode-np
run it
scoop reset -a
> fix(scoop-reset): change #2952 fix to be the same with scoop-install

- CHANGELOG.md
- libexec/scoop-checkup.ps1
> fix(scoop-checkup): Don't throw 7zip error when external 7zip is used

- CHANGELOG.md
- lib/install.ps1
Throw warning when user is not authorized to make a GitHub request.
Closes #5449
> fix(config): Warn users about misconfigured token

- CHANGELOG.md
- lib/depends.ps1
- lib/install.ps1
- lib/manifest.ps1
- libexec/scoop-cat.ps1
- libexec/scoop-download.ps1
Correct prompt about source of manifest when not found.
Close #5546
This is the original functionality that was broken when merging new features/refactoring. After the changes, user must explicitly input full filename for local manifests:
```
$manifest = '{
"version": "1",
"url": "http://example.org/#/App.exe"
}'
$manifest | out-file localmanifest.json -Encoding ascii
$manifest | out-file manifest_without_suffix -Encoding ascii
scoop install localmanifest × # This was allowed before.
scoop install localmanifest.json √
scoop install .\localmanifest.json √
scoop install manifest_without_suffix √
```
Example for actual usage:
```
~\Desktop\manifests
❯ ls -name
git
git.json
~\Desktop\manifests
❯ scoop info git
Name        : git
Description : Distributed version control system
Version     : …
```
> fix(manifest): Correct source of manifest

- CHANGELOG.md
- lib/install.ps1
> fix(install): Fix bugs in #5715

- CHANGELOG.md
- lib/install.ps1
- libexec/scoop-update.ps1
Remove PATH correctly.
- Handle '.' in `env_rm_path`
- Remove correct dir if junction is used (a.k.a. remove `...\current` instead of `...\x.x.x` during updating
Relates to #4550
Before:
After:
> fix(update/uninstall): Remove items from PATH correctly

- CHANGELOG.md
- lib/core.ps1
Final PR for stable version (#5424)
Before handling the argument list, it splits by finding spaces that are not in a path or before params (starting with `/` or `-`) and adding them to `Process.StartInfo.ArgumentList` or `Process.StartInfo.Arguments`.
Example: (https://regex101.com/r/HynlRG/1)
- Relates to #5065 
Test with the following manifests, and scoop path with/without spaces.
<details>
<summary>msmpi</summary>
```json
{
"version": "10.1.1",
"description": "Microsoft implementation of the Message Passing Interface standard for developing and running parallel applications on the Windows platform.",
"homepage": "https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi",
"license": "MIT",
"url": "https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpis …
```
> fix(core): Fix arguments parsing method of `Invoke-ExternalCommand()`

- CHANGELOG.md
- bin/uninstall.ps1
- lib/core.ps1
- lib/install.ps1
- lib/psmodules.ps1
- lib/system.ps1
- libexec/scoop-install.ps1
- libexec/scoop-reset.ps1
- libexec/scoop-uninstall.ps1
- libexec/scoop-update.ps1
- test/Scoop-Core.Tests.ps1
- test/Scoop-Install.Tests.ps1
Ed. Separate part of isolate PATH to #5840, this PR is for refactoring now.
~Use config option `use_isolated_path` to separate Scoop apps PATH to `SCOOP_PATH`, and just add `%SCOOP_PATH%` to `$env:Path` when install app with `env_add_path` first time.~
- Prepare for #5840
What the commits do:
- refactor(core): Remove unused `ensure_robocopy_in_path()`
- The function is used when installing scoop itself, and the install script is moved to https://github.com/ScoopInstaller/Install/blob/master/install.ps1
- refactor(system): Move EnvVar-related functions to `system.ps1`
- Move from `core.ps1`: `Publish-Env()`, `env()`, `search_in_path()`, `ensure_in_path()`, `strip_path()`, `add_first_in_path()`, `remove_from_path()`
- Add necessary `system.ps1` importing
- refactor(EnvVar): Separate `env()` …
> refactor(core): Rewrite and separate path-related functions to `system.ps1`

- CHANGELOG.md
- libexec/scoop-shim.ps1
Importi `system.ps1` in `scoop-shim.ps1`. 
The bug was introduced in #5836. Closes #5863
Github Actions. Local manual testing, as automated tests didn' cover it.
> fix(scoop-shim): Import system.ps1

- CHANGELOG.md
- libexec/scoop-virustotal.ps1
To fix that the escape character not available in PowerShell 5.1
Closes #5869
Run the same command `scoop virustotal <package>` and check the warning message.
> fix(scoop-virustotal): escape character not available in PowerShell 5.1

- CHANGELOG.md
- bin/checkhashes.ps1
- lib/autoupdate.ps1
- lib/core.ps1
- lib/install.ps1
- lib/psmodules.ps1
- lib/system.ps1
- libexec/scoop-info.ps1
- libexec/scoop-status.ps1
- libexec/scoop-update.ps1
- test/Scoop-Install.Tests.ps1
Get rid of `fullpath`, just get absolute path when initialing `$globaldir`, `$scoopdir` and `$cachedir`, other dirs are derived from these three root ones.
> refactor(core): Get rid of 'fullpath'

- CHANGELOG.md
- lib/core.ps1
For Java apps, the working directory should be apps' root directory since config files are normally located beside `.jar`.
> fix(shim): Run JAR file from app's root directory

- CHANGELOG.md
- lib/core.ps1
- lib/decompress.ps1
`dark` is removed from WiX 4, and use `wix burn extract` to do the same job.
- Relates to https://github.com/ScoopInstaller/Main/pull/5552
- Relates to https://github.com/ScoopInstaller/Main/pull/5693
After merging to the `master` branch, only use `dark` for machines without .NET 6+ since WiX Toolset requires .NET SDK 6+ (? not tested).
> fix(decompress): Use `wix.exe` in WiX Toolset v4+ as primary extractor of `Expand-DarkArchive()`

- CHANGELOG.md
- lib/core.ps1
- test/Scoop-Decompress.Tests.ps1
- **core:** Fix `Invoke-ExternalCommand` regression ([#5923](https://github.com/ScoopInstaller/Scoop/issues/5923))
- Closes #5911
- Closes https://github.com/ScoopInstaller/Main/issues/5721
- Closes https://github.com/ScoopInstaller/Main/issues/5723 
- Closes https://github.com/ScoopInstaller/Main/issues/5725 
- Closes https://github.com/ScoopInstaller/Main/issues/5726 
- Closes https://github.com/ScoopInstaller/Main/issues/5728 
- Closes https://github.com/ScoopInstaller/Main/issues/5729 
- Closes https://github.com/ScoopInstaller/Main/issues/5730 
- Closes https://github.com/ScoopInstaller/Main/issues/5740 
- Closes https://github.com/ScoopInstaller/Main/issues/5741 
- Closes https://github.com/ScoopInstaller/Extras/issues/13154 
Thanks to the following contributors (ordered by PR …
> chore(release): Bump to version 0.4.1

- CHANGELOG.md
- lib/json.ps1
This may break checkver of some manifests if they leverage the old format of return. We can update those manifests once found.
Closes #5920
> fix(json): Serialize jsonpath return

- CHANGELOG.md
- lib/core.ps1
- libexec/scoop-cache.ps1
- test/Scoop-Core.Tests.ps1
Replaces #4349, with sha1 for shorter output. For a better migration experience and implicit bandwidth saving, old cache files will still be used when available but this check may be removed sometime in the future.
Fixes #4327
Closes #4349
unit tests added
> feat(core): New cache filename format

- CHANGELOG.md
- libexec/scoop-search.ps1
Catch error of parsing invalid manifest
before:
```pwsh
MethodInvocationException: <path_to_scoop>\apps\scoop\current\libexec\scoop-search.ps1:64
Line |
64 |          $json = [System.Text.Json.JsonDocument]::Parse([System.IO.Fil …
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Exception calling "Parse" with "1" argument(s): "The input does not contain any JSON tokens.
| Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 |
| BytePositionInLine: 0."
```
after:
No error thrown, also the invalid manifest can be troubleshooted when turning on debug mode.
Closes #XXXX
> fix(scoop-search): Catch error of parsing invalid manifest

- CHANGELOG.md
- lib/system.ps1
Correct parameter's name, `-Name` to `-Pattern`. Corresponds to the new parameter name -Pattern for the `Split-PathLikeEnvVar` function.
Function `Test-PathLikeEnvVar` is changed to `Split-PathLikeEnvVar` recently, which also updated to provide `-Pattern` parameter with string array type to the function. But `strip_path`, which is now deprecated function and implemented to invoke warning and `Split-PathLikeEnvVar` function with `$dir` and `$orig_path` parameters, is still passing `$dir` parameter as `-Name` to the newer function. So `$Pattern` has `$null` value and causes null-valued expression error.
As we can see, the function could not receive the value to `$Pattern` correctly.
The error was that:
```powershell
WARN  "env" will be deprecated. Please change your code/manifest to use …
```
> fix(system): `$dir` parameter passing to `Split-PathLikeEnvVar` at `strip_path` with `-Pattern` switch

- CHANGELOG.md
- lib/database.ps1
Skip caching deprecated manifest.
It would be more effective to assign a flag to deprecated items, as maintainers often transfer manifests from the main bucket to the deprecated one, and this would allow users to search for them as well.
- Closes #5948
> fix(database): Skip caching 'deprecated' dir

- CHANGELOG.md
- lib/buckets.ps1
- lib/database.ps1
- libexec/scoop-update.ps1
Use `Find-BucketDirectory()` to locate the correct bucket directory, ref: https://github.com/ScoopInstaller/Scoop/pull/5949#issuecomment-2103695799
- Replace #5949
Test with `scoop config use_sqlite_cache true`, `scoop update` and `scoop bucket add xxx`.
> fix(database): Use 'Find-BucketDirectory()' to locate bucket dir

- CHANGELOG.md
- libexec/scoop-info.ps1
In certain scenarios, the estimated download size may be incorrect.
- Closes https://github.com/ScoopInstaller/Scoop/issues/2381#issuecomment-2104082587
> fix(scoop-info): Fix download size estimating

- CHANGELOG.md
- lib/decompress.ps1
- lib/install.ps1
Separate archives extraction function from downloader (`Invoke-ScoopDownload()`)
- Relates to #3502
`scoop install` and `scoop update` work fine.
> refactor(install): Separate archive extraction from downloader

- CHANGELOG.md
- lib/autoupdate.ps1
- lib/core.ps1
Relocate `PSObject.Copy()` to `substitute()` for increased generality.
- Relates to #5934
Same tests as #5934
> fix(core): Add 'PSObject.Copy()' to 'substitute()'

- CHANGELOG.md
- lib/database.ps1
Dispose all SQL commands to release the database file handle.
- Closes #5965
- Relates to #5851
Tested with `scoop update`, `scoop search 7zip`, and `scoop config use_sqlite_cache true`.
> fix(sqlite): Dispose all command to release database file handle

- CHANGELOG.md
- lib/buckets.ps1
- lib/database.ps1
- libexec/scoop-update.ps1
Remove items in cache after removing bucket or manifests
- Closes #5963
- Relates to #5851
Remove bucket:
Remove manifests:
> fix(sqlite): Update cache after removing bucket or manifests

- CHANGELOG.md
- bin/uninstall.ps1
- lib/core.ps1
- lib/install.ps1
- libexec/scoop-info.ps1
- libexec/scoop-uninstall.ps1
- libexec/scoop-update.ps1
- Refactor `run_installer()` and `run_uninstaller()`
- Add hook type `installer` and `uninstaller` to `Invoke-HookScript()`
- Remove one-time used function `args()`
- Relates to #3502
Tested with `scoop install hack-font` and `scoop uninstall hack-font` w/ other manifests.
> refactor(install): Replace 'run_(un)installer()' with 'Invoke-Installer()'

- CHANGELOG.md
- lib/install.ps1
The variable `$fname` might be utilized in both `installer.script` and `post_install`, therefore, it should not be removed as initially considered.
- Relates to #5968
> fix(install): Add back arg `$Name` in `Invoke-Installer()`

- CHANGELOG.md
- lib/core.ps1
- libexec/scoop-install.ps1
added the ability to use the @ symbol when using `scoop install` with a url/file location
Simple change to the regex that matches the name of the app to not require the whole string to be ending with .json. For example you can now do:
```
scoop install https://raw.githubusercontent.com/ScoopInstaller/Main/master/bucket/neovim.json@0.9.0
```
(adds #5977)
This has been tested with all installation methods that have been mentioned in the `scoop install --help`
> feat(install): Added the ability to specify @ version when installing from url/file location

- CHANGELOG.md
- bin/checkver.ps1
> fix(checkver): Correct variable 'regex' to 'regexp'

- CHANGELOG.md
- lib/decompress.ps1
This PR is to fix a regression introduced in the refactoring of #5951 which broke the match between entries of `extract_dir`/`extract_to` lists and files that require unpacking:
https://github.com/ScoopInstaller/Scoop/blob/a5bd2297c6227e5b09869acafaa12cbdc73f6132/lib/decompress.ps1#L22-L26
The directories specified by `extract_dir`/`extract_to` fields in an app manifest are only meaningful for download files that require unpacking, if a download URL of an unpacking-free file is placed before those of archive files, the latter will not be unpacked from/to the specified paths.
Tested by running:
```powershell
scoop install 'https://raw.githubusercontent.com/lewis-yeung/scoop-bucket/a9b9df6f918995d3c6f1323a6133b20a0d7b4c6d/bucket/oh-my-posh.json'
```
It works properly after the fix.
> fix(decompress): Match `extract_dir`/`extract_to` and archives

- CHANGELOG.md
- lib/core.ps1
#5979
Before this commit, if a user had a custom alias or function for `git` specified in their PowerShell profile, `Get-HelperPath` would return path to the PowerShell module where the function is defined instead of path to the actual Git binary.
Tested interactively, the code seems reasonably obvious to me. To test the fix, run the following snippet:
```powershell
New-Module -Script {function git {}}
scoop update
```
Without this PR, the invocation results in the folowing error:
```
> scoop update
&: D:\_custom\scoop\app\apps\scoop\current\lib\core.ps1:273
Line |
273 |          return & $git @ArgumentList
|                   ~~~~
| The term '__DynamicModule_cbe178d9-14c2-494d-8004-fbdc292d59d2' is not recognized as a name of a cmdlet, function, script file, or executable program. Check …
```
> fix(core): Search for Git executable instead of any cmdlet

- CHANGELOG.md
- lib/core.ps1
Since Windows 11 add default `bash.exe` in system folder, there may be bugs when using linux apps. This PR fixes it by converting Windows path using proper utils (`wslpath` in WSL and `cygpath` in Cygwin/MSYS2).
- Closes #5952
- Closes https://github.com/ScoopInstaller/Extras/issues/13385
- Related to https://github.com/ScoopInstaller/Extras/pull/13342
By running neofetch under Powershell, CMD, WSL, Cygwin and MSYS2.
> fix(core): Use correct path in 'bash'

- CHANGELOG.md
- lib/core.ps1
When specify `-CommandType Application`, you get all git commands from `$env:Path`.
Use `TotalCount` to limit the number of commands to get.
Closes #6012
Relates to #5998
Before:
```
$(Get-Command git -CommandType Application -ErrorAction Ignore).Source
C:\Program Files\Git\cmd\git.exe
C:\Program Files\Git\mingw64\bin\git.exe
```
After:
```
$(Get-Command git -CommandType Application -TotalCount 1 -ErrorAction Ignore).Source
C:\Program Files\Git\cmd\git.exe
```
> fix(core): Limit the number of commands to get

- CHANGELOG.md
- bin/checkver.ps1
When checking update and the `$script` is used, an error message should mention `the output of script` instead of `$url`.
> fix(checkver): Correct error messages

- CHANGELOG.md
- lib/core.ps1
Use `pushd` and `popd` to restore cmd path
- Closes #6026
- Relates to #5872
> fix(shim): Restore original path for JAR cmd

- CHANGELOG.md
- lib/database.ps1
`Expand-Archive()` in Windows PowerShell only accept `.zip` extension, so rename the downloaded archive and fix `Move-Item()` error.
- Closes #6041
Tested in PS 5.1
> fix(sqlite): Fix compatibility with Windows PowerShell

- CHANGELOG.md
- lib/install.ps1
- libexec/scoop-reset.ps1
A bug occurs when setting Environment Variables if `$persist_dir` or another script is used within it; therefore, it's necessary to expand the string before setting the Environment Variables.
- Closes #6043
- Relates to #5968
Test with `bazel` and `tesseract`.
Before:
After:
> fix(install): Expand env_set items

- CHANGELOG.md
- libexec/scoop-install.ps1
When `foreach` returns only one value, the type of `$specific_versions_paths` is string.
When the value of `$specific_versions_paths` is a string, the value on the right side of the operator is appended to the string.
Closes #6038
Before:
```
$scoop  install mysql-workbench@8.0.32 firefox
...
Couldn't find manifest for 'mysql-workbench.jsonfirefox'.
```
After:
```
$scoop  install mysql-workbench@8.0.32 firefox
...
Succeed!
```
> fix(install): Fix parsing error when installing multiple apps w/ specific version

- CHANGELOG.md
- libexec/scoop-virustotal.ps1
This PR aims to fix the error introduced in https://github.com/ScoopInstaller/Scoop/issues/5920. It uses the $single arguments in json_path to correctly extract the data instead, as previously they are enclosed with square brackets.
- Closes #6042 
- Related to #5957
Tested using Powershell 7
```
scoop virustotal eza
main/eza: 0/64, see https://www.virustotal.com/gui/file/0c5e596c990e15cbc04dce52ed9629cc8adc9c967d5e79534d6ddea020323cc4
scoop virustotal -a
main/1password-cli: 0/67, see https://www.virustotal.com/gui/file/761f2aa0f8907b397940cb69d9514efbcc4c67de6d64426e99a542edc60d615c
main/7zip: 0/64, see https://www.virustotal.com/gui/file/eb94db7341e59f1871a4d4f60165563f1881e33aef093b7d8427651c2a0f4b6f
```
> fix(scoop-virustotal): Adjust `json_path` parameters to retrieve correct analysis stats

- CHANGELOG.md
- lib/buckets.ps1
- lib/commands.ps1
- lib/database.ps1
- lib/install.ps1
- libexec/scoop-alias.ps1
- libexec/scoop-install.ps1
- libexec/scoop-reset.ps1
- libexec/scoop-virustotal.ps1
- test/Scoop-Commands.Tests.ps1
- **scoop-alias:** Pass options correctly (#6003)
- **scoop-virustotal:** Adjust `json_path` parameters to retrieve correct analysis stats (#6044)
- **bucket:** Implement error handling for failed bucket addition (#6051)
- **database:** Fix compatibility with Windows PowerShell (#6045)
- **install:** Expand `env_set` items before setting Environment Variables (#6050)
- **install:** Fix parsing error when installing multiple apps w/ specific version (#6039)
- Closes #6041
- Closes #6043
- Closes https://github.com/ScoopInstaller/Extras/issues/13600
- Closes #6048
- Closes #6038
- Closes #6042
- Closes #5767
Thanks to the following contributors (ordered by PR merging time):
@niheaven @qwertyhjklxyz @Lutra-Fs @lewis-yeung
> chore(release): Bump to version 0.5.1

- CHANGELOG.md
- libexec/scoop-alias.ps1
Remove comma to allow `--verbose` to be passed to the long option in `getopt` function.
Closes #6061 .
I made the change and ran `scoop alias list --verbose` sucessfully.
> fix(scoop-alias): Fix 'Option --verbose not recognized.'

- CHANGELOG.md
- lib/json.ps1
- libexec/scoop-virustotal.ps1
Using `[System.Linq.Enumerable]::Count()` to count JSON objects.
- Relates to #6044
- Relates to #6066
- Relates to #5593
- Relates to #5921
> fix(json): Fix JSON items counting function

- CHANGELOG.md
- libexec/scoop-hold.ps1
`continue` statement shouldn't be used outside of a loop, switch, or trap.
> Using continue inside a pipeline, such as a ForEach-Object script block, not only exits the pipeline, it potentially terminates the entire runspace.
Ref: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_continue?view=powershell-7.4#do-not-use-continue-outside-of-a-loop-switch-or-trap
- Closes #6077
> fix(scoop-hold): Use 'foreach' loop to allow 'continue' statement

- CHANGELOG.md
- lib/core.ps1
- lib/install.ps1
> fix(core): Use 'Join-Path' to construct cache file path

- CHANGELOG.md
- lib/download.ps1
Try to fallback to default downloader when aria2 download failed.
This make the download with aria2 more stable since there's some download links that doesn't support multi-connection.
Closes #4472
> fix(install): fallback to default downloader when aria2 fails

- CHANGELOG.md
- lib/commands.ps1
Handling aliases that lose script file.
Closes #XXXX
> fix(commands): Handling broken aliases

- CHANGELOG.md
- lib/core.ps1
Do not suppress stderr for commands, only suppress output when checking for `wslpath`/`cygpath` commands first.
Closes #6112
`wcurl` at https://github.com/ScoopInstaller/Main/pull/6117
Before: Error, no output
After: now returns an error with the output
> fix(shim): properly check `wslpath`/`cygpath` command first

- CHANGELOG.md
- libexec/scoop-bucket.ps1
> fix(scoop-bucket): Add missing import for `no_junction` envs

- CHANGELOG.md
- lib/decompress.ps1
Replace deprecated `7ZIPEXTRACT_USE_EXTERNAL` config with new config `USE_EXTERNAL_7ZIP` in `lib/decompress.ps1`.
Fixes bug with 7zip config in `lib/decompress.ps1`
> fix(decompress): Replace deprecated 7ZIPEXTRACT_USE_EXTERNAL config

- lib/core.ps1
- lib/manifest.ps1
- libexec/scoop-cat.ps1
- libexec/scoop-depends.ps1
- libexec/scoop-download.ps1
- libexec/scoop-home.ps1
- libexec/scoop-info.ps1
- libexec/scoop-list.ps1
- libexec/scoop-status.ps1
- libexec/scoop-virustotal.ps1
TODOs:
Relates to #2719, #3441, #3870, #5172, #5709
before: LEFT pane, after: RIGHT pane
f6ce496: Select actual source for manifest
manifests with same name from different bucket:
manifest that installs with URI:
Fallback to installed manifest:
e7155ea: handling deprecated manifest
c525005:
standalone manifest: any query or installation that does not install with app name, e.g. PATH or URI
result of `scoop-info` will drop **Installed** version and **available update** when source of queried and installed are different.
BOTH pane are after effects
c38fc63: depends support for standalone manifest
```
❯ scoop depends .\ack.json
Source                                 Name
------                                 ----
main                                   perl …
```
> refactor(Get-Manifest): Select actual source for manifest
